//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Comunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RutasPreviewRecursos {
        public static string RutaPreviewPoliticaTransversalesPoliticasFuentes;
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RutasPreviewRecursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNP.ServiciosNegocio.Comunes.RutasPreviewRecursos", typeof(RutasPreviewRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CadenaValorPreview.json.
        /// </summary>
        public static string PreviewCadenaValor {
            get {
                return ResourceManager.GetString("PreviewCadenaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\PreguntasPreview.json.
        /// </summary>
        public static string PreviewPreguntas {
            get {
                return ResourceManager.GetString("PreviewPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjusteFocalizacionPoliticasTransversalesAsociacionIndicadoresPreview.json.
        /// </summary>
        public static string RutaAjusteFocalizacionPoliticasTransversalesAsociacionIndicadores {
            get {
                return ResourceManager.GetString("RutaAjusteFocalizacionPoliticasTransversalesAsociacionIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjusteIncluirPoliticasPreview.json.
        /// </summary>
        public static string RutaAjusteIncluirPoliticas {
            get {
                return ResourceManager.GetString("RutaAjusteIncluirPoliticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CostosActividadesPreview.json.
        /// </summary>
        public static string RutaCostosActividades {
            get {
                return ResourceManager.GetString("RutaCostosActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CostosEntregablesPreview.json.
        /// </summary>
        public static string RutaCostosEntregables {
            get {
                return ResourceManager.GetString("RutaCostosEntregables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CartaConceptoDatosDespedida.json.
        /// </summary>
        public static string RutaDatosCartaConceptoDespedida {
            get {
                return ResourceManager.GetString("RutaDatosCartaConceptoDespedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\DiligenciarFuentesPreview.json.
        /// </summary>
        public static string RutaDiligenciarFuentes {
            get {
                return ResourceManager.GetString("RutaDiligenciarFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\EncabezadoPieBasicoPreview.json.
        /// </summary>
        public static string RutaEncabezadoPieBasico {
            get {
                return ResourceManager.GetString("RutaEncabezadoPieBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionPoliticasTransversalesAsociacionIndicadores.json.
        /// </summary>
        public static string RutaFocalizacionPoliticasTransversalesAsociacionIndicadores {
            get {
                return ResourceManager.GetString("RutaFocalizacionPoliticasTransversalesAsociacionIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionPoliticasTransversalesMetas.json.
        /// </summary>
        public static string RutaFocalizacionPoliticasTransversalesMetas {
            get {
                return ResourceManager.GetString("RutaFocalizacionPoliticasTransversalesMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionPoliticasTransversalesRelacionadas.json.
        /// </summary>
        public static string RutaFocalizacionPoliticasTransversalesRelacionadas {
            get {
                return ResourceManager.GetString("RutaFocalizacionPoliticasTransversalesRelacionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionPoliticasTransversalesRelacionadasAjustes.json.
        /// </summary>
        public static string RutaFocalizacionPoliticasTransversalesRelacionadasAjustes {
            get {
                return ResourceManager.GetString("RutaFocalizacionPoliticasTransversalesRelacionadasAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FuentesFinanciacionAjustePreview.json.
        /// </summary>
        public static string RutaFuentesFinanciacionAjuste {
            get {
                return ResourceManager.GetString("RutaFuentesFinanciacionAjuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\IncluirPoliticas.json.
        /// </summary>
        public static string RutaIncluirPolitcas {
            get {
                return ResourceManager.GetString("RutaIncluirPolitcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\IncluirPoliticasPreview.json.
        /// </summary>
        public static string RutaIncluirPoliticasSN {
            get {
                return ResourceManager.GetString("RutaIncluirPoliticasSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\PoliticaRelacionadasPreview.json.
        /// </summary>
        public static string RutaPoliticaRelacionadas {
            get {
                return ResourceManager.GetString("RutaPoliticaRelacionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesCuantificacionBeneficiarioPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesCuantificacionBeneficiario {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesCuantificacionBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesPoliticaTBeneficiarioPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesPoliticaTBeneficiario {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesPoliticaTBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesPoliticaTCategoriaPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesPoliticaTCategoria {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesPoliticaTCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesPoliticaTMetasPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesPoliticaTMetas {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesPoliticaTMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesRegionalizaFuentesPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesRegionalizaFuentes {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesRegionalizaFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesUbicacionPreview.json.
        /// </summary>
        public static string RutaPreviewAjustesUbicacion {
            get {
                return ResourceManager.GetString("RutaPreviewAjustesUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CofinanciacionAgregarPreview.json.
        /// </summary>
        public static string RutaPreviewCofinanciacion {
            get {
                return ResourceManager.GetString("RutaPreviewCofinanciacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CuantificacionBeneficiarioPreview.json.
        /// </summary>
        public static string RutaPreviewCuantificacionBeneficiario {
            get {
                return ResourceManager.GetString("RutaPreviewCuantificacionBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\CuantificacionLocalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewCuantificacionLocalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewCuantificacionLocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\DatosBasicosSGRPreview.json.
        /// </summary>
        public static string RutaPreviewDatosBasicosSGR {
            get {
                return ResourceManager.GetString("RutaPreviewDatosBasicosSGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AlcancePreview.json.
        /// </summary>
        public static string RutaPreviewDefinirAlcance {
            get {
                return ResourceManager.GetString("RutaPreviewDefinirAlcance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\DesagregarRegionalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewDesagregarRegionalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewDesagregarRegionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewFocalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewFocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionCuantificacionLocalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewFocalizacionCuantificacionLocalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewFocalizacionCuantificacionLocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FuenteCofinanciacionPreview.json.
        /// </summary>
        public static string RutaPreviewFuenteCofinanciacion {
            get {
                return ResourceManager.GetString("RutaPreviewFuenteCofinanciacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FuentesPreview.json.
        /// </summary>
        public static string RutaPreviewFuentes {
            get {
                return ResourceManager.GetString("RutaPreviewFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FuentesAgregarPreview.json.
        /// </summary>
        public static string RutaPreviewFuentesAgregar {
            get {
                return ResourceManager.GetString("RutaPreviewFuentesAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\IndicadorProductoAgregarPreview.json.
        /// </summary>
        public static string RutaPreviewIndicadorProductoAgregar {
            get {
                return ResourceManager.GetString("RutaPreviewIndicadorProductoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\LocalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewlocalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewlocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\PoliticaTBeneficiarioPreview.json.
        /// </summary>
        public static string RutaPreviewPoliticaTBeneficiario {
            get {
                return ResourceManager.GetString("RutaPreviewPoliticaTBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\PoliticaTCategoriaPreview.json.
        /// </summary>
        public static string RutaPreviewPoliticaTCategoria {
            get {
                return ResourceManager.GetString("RutaPreviewPoliticaTCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\PriorizacionRecursoPreview.json.
        /// </summary>
        public static string RutaPreviewPriorizacionRecurso {
            get {
                return ResourceManager.GetString("RutaPreviewPriorizacionRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\FocalizacionProyectoPreview.json.
        /// </summary>
        public static string RutaPreviewProyectoFocalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewProyectoFocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\RegionalizacionPreview.json.
        /// </summary>
        public static string RutaPreviewRegionalizacion {
            get {
                return ResourceManager.GetString("RutaPreviewRegionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\RegionalizacionIndicadorAgregarPreview.json.
        /// </summary>
        public static string RutaPreviewRegionalizacionIndicadorAgregar {
            get {
                return ResourceManager.GetString("RutaPreviewRegionalizacionIndicadorAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\RegionalizacionIndicadoresPreview.json.
        /// </summary>
        public static string RutaPreviewRegionalizacionIndicadores {
            get {
                return ResourceManager.GetString("RutaPreviewRegionalizacionIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\RegionalizaFuentesPreview.json.
        /// </summary>
        public static string RutaPreviewRegionalizaFuentes {
            get {
                return ResourceManager.GetString("RutaPreviewRegionalizaFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\ProductoPreview.json.
        /// </summary>
        public static string RutaProducto {
            get {
                return ResourceManager.GetString("RutaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\RegionalizacionMetasyRecursos.json.
        /// </summary>
        public static string RutaRegionalizacionMetasyRecursos {
            get {
                return ResourceManager.GetString("RutaRegionalizacionMetasyRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\AjustesRegionalizacionMetasyRecursosPreview.json.
        /// </summary>
        public static string RutaRegionalizacionMetasyRecursosAjuste {
            get {
                return ResourceManager.GetString("RutaRegionalizacionMetasyRecursosAjuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ObjetosPreview\ValidacionViabilidadCompletarInfo.json.
        /// </summary>
        public static string RutaValidacionViabilidadCompletarInfo {
            get {
                return ResourceManager.GetString("RutaValidacionViabilidadCompletarInfo", resourceCulture);
            }
        }
        //
        public static string RutaPreviewTramitesDistribucionAnteriores
        {
            get
            {
                return ResourceManager.GetString("RutaPreviewTramitesDistribucionAnteriores", resourceCulture);
            }
        }

        public static string RutaPreviewAjustesPoliticaTranversalFuentes { get; set; }
    }
}
