//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Comunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiciosNegocioRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiciosNegocioRecursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNP.ServiciosNegocio.Comunes.ServiciosNegocioRecursos", typeof(ServiciosNegocioRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación no Existe.
        /// </summary>
        public static string AplicacionNoExiste {
            get {
                return ResourceManager.GetString("AplicacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio estado Proyecto.
        /// </summary>
        public static string AuditoriaEstadoProyecto {
            get {
                return ResourceManager.GetString("AuditoriaEstadoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencia proyecto a entidad destino..
        /// </summary>
        public static string AuditoriaTransferencia {
            get {
                return ResourceManager.GetString("AuditoriaTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado validación Transferencia proyecto..
        /// </summary>
        public static string AuditoriaValidacion {
            get {
                return ResourceManager.GetString("AuditoriaValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales invalidas.
        /// </summary>
        public static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del formulario de preguntas solicitado no existe.
        /// </summary>
        public static string ErrorFormularioNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorFormularioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar en caché.
        /// </summary>
        public static string ErrorGuardarCache {
            get {
                return ResourceManager.GetString("ErrorGuardarCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error indefinido.
        /// </summary>
        public static string ErrorIndefinido {
            get {
                return ResourceManager.GetString("ErrorIndefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo mapear la consulta.
        /// </summary>
        public static string ErrorMapear {
            get {
                return ResourceManager.GetString("ErrorMapear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formulario de preguntas no tiene grillas configuradas.
        /// </summary>
        public static string ErrorNoExisteConfiguracionPreguntas {
            get {
                return ResourceManager.GetString("ErrorNoExisteConfiguracionPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible obtener la configuración del formulario de preguntas.
        /// </summary>
        public static string ErrorObtenerConfiguracionFormulario {
            get {
                return ResourceManager.GetString("ErrorObtenerConfiguracionFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan las credenciales.
        /// </summary>
        public static string FaltanCredenciales {
            get {
                return ResourceManager.GetString("FaltanCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardo definitivamente la entidad de tipo {0}.
        /// </summary>
        public static string GuardadoDefinitivo {
            get {
                return ResourceManager.GetString("GuardadoDefinitivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información almacenada correctamente.
        /// </summary>
        public static string GuardadoExitoso {
            get {
                return ResourceManager.GetString("GuardadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardo temporalmente la entidad de tipo {0}.
        /// </summary>
        public static string GuardadoTemporal {
            get {
                return ResourceManager.GetString("GuardadoTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al guardar.
        /// </summary>
        public static string MensajeErrorGuardar {
            get {
                return ResourceManager.GetString("MensajeErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} no existe..
        /// </summary>
        public static string ParametroNoExiste {
            get {
                return ResourceManager.GetString("ParametroNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} no recibido..
        /// </summary>
        public static string ParametroNoRecibido {
            get {
                return ResourceManager.GetString("ParametroNoRecibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} inválido.
        /// </summary>
        public static string ParametroNoValidos {
            get {
                return ResourceManager.GetString("ParametroNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros no recibidos.
        /// </summary>
        public static string ParametrosNoRecibidos {
            get {
                return ResourceManager.GetString("ParametrosNoRecibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro de entrada inválido.
        /// </summary>
        public static string ParametrosNoValidos {
            get {
                return ResourceManager.GetString("ParametrosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado exitoso.
        /// </summary>
        public static string PostExitoso {
            get {
                return ResourceManager.GetString("PostExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado no exitoso.
        /// </summary>
        public static string PostNoExitoso {
            get {
                return ResourceManager.GetString("PostNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Proyecto no tiene Fuentes de Financiación asociadas.
        /// </summary>
        public static string RespuestaSinResultados {
            get {
                return ResourceManager.GetString("RespuestaSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Entidades para los Roles.
        /// </summary>
        public static string RespuestaSinresultadosEntidadesAcciones {
            get {
                return ResourceManager.GetString("RespuestaSinresultadosEntidadesAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no tiene una regionalización asociada.
        /// </summary>
        public static string RespuestaSinResultadosRegionalizacion {
            get {
                return ResourceManager.GetString("RespuestaSinResultadosRegionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio no existe.
        /// </summary>
        public static string ServicioNoExiste {
            get {
                return ResourceManager.GetString("ServicioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se obtuvieron resultados.
        /// </summary>
        public static string SinResultados {
            get {
                return ResourceManager.GetString("SinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Autorizado.
        /// </summary>
        public static string UsuarioAutorizado {
            get {
                return ResourceManager.GetString("UsuarioAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no existe..
        /// </summary>
        public static string UsuarioInexistente {
            get {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no Autorizado.
        /// </summary>
        public static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no Autorizado.
        /// </summary>
        public static string UsuarioNoTienePermisos {
            get {
                return ResourceManager.GetString("UsuarioNoTienePermisos", resourceCulture);
            }
        }
    }
}
