//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternative
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Name { get; set; }
        public bool SendToPreparation { get; set; }
        public int AlternativeStateId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string TechnicalAnalisys { get; set; }
        public string CapacityDescription { get; set; }
        public Nullable<int> CapacityMeasureTypeId { get; set; }
        public Nullable<int> GeneralCapacity { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> ProjectHorizon { get; set; }
        public string Legend { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string UniqueIdentifier { get; set; }
        public bool IsDefault { get; set; }
        public bool IsFromBaseProject { get; set; }
    }
}
