//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bienio
    {
        public int Id { get; set; }
        public string Bienio1 { get; set; }
        public bool EsActual { get; set; }
        public bool EsActivo { get; set; }
        public int Orden { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
    }
}
