//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableCatalog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MeasureTypeId { get; set; }
        public string MeasuredThrough { get; set; }
        public bool IsEnabled { get; set; }
        public string Code { get; set; }
    
        public virtual ProductCatalog ProductCatalog { get; set; }
    }
}
