//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNH_SIIF
    {
        public string VigenciaId { get; set; }
        public short PeriodoId { get; set; }
        public string Sector { get; set; }
        public string EntidadId { get; set; }
        public string UnidadEjecutora { get; set; }
        public short TipoPresupuestoId { get; set; }
        public string Bpin { get; set; }
        public string TipoGasto { get; set; }
        public string ProgramaId { get; set; }
        public string SubprogramaId { get; set; }
        public string Proyecto { get; set; }
        public string Subproyecto { get; set; }
        public string Subordinal { get; set; }
        public short RecursosId { get; set; }
        public string SituacionId { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> ApropiacionInicial { get; set; }
        public Nullable<decimal> Positivas { get; set; }
        public Nullable<decimal> Negativas { get; set; }
        public Nullable<decimal> ApropiacionVigente { get; set; }
        public Nullable<decimal> CDP { get; set; }
        public Nullable<decimal> Compromiso { get; set; }
        public Nullable<decimal> Obligacion { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public Nullable<decimal> Reintegro { get; set; }
        public Nullable<decimal> Aplazamiento { get; set; }
        public Nullable<decimal> ModificacionAplazamiento { get; set; }
        public string ObjetivoPND { get; set; }
        public string EstrategiaPND { get; set; }
        public string ProgramaMGMP { get; set; }
        public string SubprogramaMGMP { get; set; }
        public short TipoFuenteId { get; set; }
        public string Rubro { get; set; }
    }
}
