//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityType()
        {
            this.EntityTypeCatalogOption = new HashSet<EntityTypeCatalogOption>();
            this.ResourceGroupEntityType = new HashSet<ResourceGroupEntityType>();
            this.ResourceType = new HashSet<ResourceType>();
            this.Ejecutor = new HashSet<Ejecutor>();
        }
    
        public string EntityType1 { get; set; }
        public int Id { get; set; }
        public bool IsBankEntity { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityTypeCatalogOption> EntityTypeCatalogOption { get; set; }
        public virtual ResourceGroup ResourceGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceGroupEntityType> ResourceGroupEntityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceType> ResourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ejecutor> Ejecutor { get; set; }
    }
}
