//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroprocesoSeccion
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int FaseId { get; set; }
        public int SeccionId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TipoTramiteId { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
