//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCatalog()
        {
            this.DeliverableCatalog = new HashSet<DeliverableCatalog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MeasureTypeId { get; set; }
        public int ProgramId { get; set; }
        public bool IsEnabled { get; set; }
        public string Description { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> IsTerritorial { get; set; }
        public Nullable<bool> IsDeliverable { get; set; }
        public Nullable<bool> IsNational { get; set; }
    
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverableCatalog> DeliverableCatalog { get; set; }
    }
}
