//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoConpes
    {
        public int Id { get; set; }
        public int ProyectoId { get; set; }
        public int ConpesId { get; set; }
        public string NumeroConpes { get; set; }
        public string NombreConpes { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
    }
}
