//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.ProyectoFuentesPresupuestal = new HashSet<ProyectoFuentesPresupuestal>();
            this.ProyectosRequisitos = new HashSet<ProyectosRequisitos>();
            this.ProyectosValores = new HashSet<ProyectosValores>();
            this.Reprogramacion = new HashSet<Reprogramacion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TramiteId { get; set; }
        public int ProyectoId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> PeriodoProyectoId { get; set; }
        public string Accion { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.Guid> InstanciaId { get; set; }
        public Nullable<System.Guid> FlujoId { get; set; }
        public string TipoProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<bool> EsConstante { get; set; }
        public Nullable<int> AñoBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoFuentesPresupuestal> ProyectoFuentesPresupuestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectosRequisitos> ProyectosRequisitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectosValores> ProyectosValores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reprogramacion> Reprogramacion { get; set; }
    }
}
