//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceGroupEntityType
    {
        public int ID { get; set; }
        public int ResourceGroupId { get; set; }
        public int ResourceTypeId { get; set; }
        public int EntityTypeId { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual ResourceGroup ResourceGroup { get; set; }
        public virtual ResourceType ResourceType { get; set; }
    }
}
