//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceTypeByEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceTypeByEntity()
        {
            this.TransferConfiguration = new HashSet<TransferConfiguration>();
        }
    
        public int Id { get; set; }
    
        public virtual EntityTypeCatalogOption EntityTypeCatalogOption { get; set; }
        public virtual EntityTypeCatalogOption EntityTypeCatalogOption1 { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferConfiguration> TransferConfiguration { get; set; }
    }
}
