//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramite
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string NumeroTramite { get; set; }
        public System.DateTime FechaTramite { get; set; }
        public int TipoSolicitudID { get; set; }
        public int TipoTramiteID { get; set; }
    
        public virtual EntityTypeCatalogOption EntityTypeCatalogOption { get; set; }
    }
}
