//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferConfiguration
    {
        public int Id { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> AnswerSGR { get; set; }
        public Nullable<int> CRTypeId { get; set; }
        public Nullable<int> FlowCatalogId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
        public string Comments { get; set; }
    
        public virtual EntityTypeCatalogOption EntityTypeCatalogOption { get; set; }
        public virtual ResourceTypeByEntity ResourceTypeByEntity { get; set; }
    }
}
