//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    
    public partial class uspGetProyectoFuentePresupuestalPorTramite_Result3
    {
        public Nullable<int> Id { get; set; }
        public Nullable<int> TramiteProyectoId { get; set; }
        public Nullable<int> FuenteId { get; set; }
        public string Nombre { get; set; }
        public string Origen { get; set; }
        public string Accion { get; set; }
        public Nullable<decimal> ValorInicialCSF { get; set; }
        public Nullable<decimal> ValorInicialSSF { get; set; }
        public Nullable<decimal> ValorVigenteCSF { get; set; }
        public Nullable<decimal> ValorVigenteSSF { get; set; }
        public Nullable<decimal> ValorDisponibleCSF { get; set; }
        public Nullable<decimal> ValorDisponibleSSF { get; set; }
        public Nullable<int> idTipoValorContracreditoCSF { get; set; }
        public Nullable<decimal> ValorContracreditoCSF { get; set; }
        public Nullable<int> idTipoValorContracreditoSSF { get; set; }
        public Nullable<decimal> ValorContracreditoSSF { get; set; }
    }
}
