//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.Modelo
{
    using System;
    
    public partial class uspGetPlantillaCarta_Result1
    {
        public int Id { get; set; }
        public int TipoTramiteId { get; set; }
        public int PantillaCartaSeccionId { get; set; }
        public string NombreSeccion { get; set; }
        public int PlantillaCartaSeccionCampoId { get; set; }
        public string NombreCampo { get; set; }
        public int TipoCampoId { get; set; }
        public string NombreTipoCampo { get; set; }
        public int LongitudCampo { get; set; }
        public string TipoCampoDato { get; set; }
        public string FormatoCampo { get; set; }
        public string TituloCampo { get; set; }
        public string TextoDefecto { get; set; }
        public bool Editable { get; set; }
        public int Orden { get; set; }
        public string ConsultaSql { get; set; }
    }
}
