//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.Backbone.Comunes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNP.Backbone.Comunes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación no encontrada..
        /// </summary>
        public static string AplicacionNoExiste {
            get {
                return ResourceManager.GetString("AplicacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el objeto con key igual a {0}.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} no recibido..
        /// </summary>
        public static string ParametroNoRecibido {
            get {
                return ResourceManager.GetString("ParametroNoRecibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros no recibidos..
        /// </summary>
        public static string ParametrosNoRecibidos {
            get {
                return ResourceManager.GetString("ParametrosNoRecibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no ha sido parametrizado para la aplicación..
        /// </summary>
        public static string ServicioNoExiste {
            get {
                return ResourceManager.GetString("ServicioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no existe..
        /// </summary>
        public static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permisos para acceder a la opción solicitada.
        /// </summary>
        public static string UsuarioNoTienePermisos {
            get {
                return ResourceManager.GetString("UsuarioNoTienePermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene tareas pendientes.
        /// </summary>
        public static string UsuarioNoTieneTareasPendientes {
            get {
                return ResourceManager.GetString("UsuarioNoTieneTareasPendientes", resourceCulture);
            }
        }
    }
}
