//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosWBS.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenamientoTemporal
    {
        public System.Guid InstanciaId { get; set; }
        public System.Guid AccionId { get; set; }
        public string Json { get; set; }
    }
}
