//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosWBS.Persistencia.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MGAWebContexto : DbContext
    {
        public MGAWebContexto()
            : base("name=MGAWebContexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlmacenamientoTemporal> AlmacenamientoTemporal { get; set; }
        public virtual DbSet<Capitulo> Capitulo { get; set; }
        public virtual DbSet<MacroprocesoSeccion> MacroprocesoSeccion { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<SeccionCapitulos> SeccionCapitulos { get; set; }
        public virtual DbSet<VGetFase> VGetFase { get; set; }
    
        public virtual ObjectResult<uspGetProductosPorProyecto_Result> uspGetProductosPorProyecto(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetProductosPorProyecto_Result>("uspGetProductosPorProyecto", bPINParameter);
        }
    
        public virtual int uspPostProductosPorProyecto(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProductosPorProyecto", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostCadenaValor(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("Json", json) :
                new ObjectParameter("Json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCadenaValor", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetRecursos_Result> uspGetRecursos(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRecursos_Result>("uspGetRecursos", bPINParameter);
        }
    
        public virtual int uspPostInsertarRecursos(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostInsertarRecursos", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetRecursosRegionalizacion_Result> uspGetRecursosRegionalizacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRecursosRegionalizacion_Result>("uspGetRecursosRegionalizacion", bPINParameter);
        }
    
        public virtual int uspGetFuentesFinanciacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetFuentesFinanciacion", bPINParameter);
        }
    
        public virtual ObjectResult<uspGetCadenaValor_Result> uspGetCadenaValor(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetCadenaValor_Result>("uspGetCadenaValor", bPINParameter);
        }
    
        public virtual ObjectResult<uspGetRecursosFocalizacion_Result> uspGetRecursosFocalizacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRecursosFocalizacion_Result>("uspGetRecursosFocalizacion", bPINParameter);
        }
    
        public virtual ObjectResult<uspGetRecursosFocalizacionVA_Result> uspGetRecursosFocalizacionVA(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRecursosFocalizacionVA_Result>("uspGetRecursosFocalizacionVA", bPINParameter);
        }
    
        public virtual int uspPostRecursosValoresFocalizacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRecursosValoresFocalizacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostRecursosValoresFuentesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRecursosValoresFuentesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostCadenaValorTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCadenaValorTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<uspGetProductosRegionalizacionPorProyecto_Result> uspGetProductosRegionalizacionPorProyecto(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetProductosRegionalizacionPorProyecto_Result>("uspGetProductosRegionalizacionPorProyecto", bPINParameter);
        }
    
        public virtual ObjectResult<uspGetRegionalizacionIndicadoresProgramacion_Result> uspGetRegionalizacionIndicadoresProgramacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRegionalizacionIndicadoresProgramacion_Result>("uspGetRegionalizacionIndicadoresProgramacion", bPINParameter);
        }
    
        public virtual int uspPostRegionalizacionIndicadoresProgramacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionIndicadoresProgramacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostInsertarFocalizacionVA(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostInsertarFocalizacionVA", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostRegionalizacionIndicadoresProgramacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionIndicadoresProgramacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetProyectoFocalizacionVA_Result> uspGetProyectoFocalizacionVA(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetProyectoFocalizacionVA_Result>("uspGetProyectoFocalizacionVA", bPINParameter);
        }
    
        public virtual int uspGetProyectoValoresFocalizacionVA(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetProyectoValoresFocalizacionVA", bPINParameter);
        }
    
        public virtual int uspPostProyectosValoresFocalizacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProyectosValoresFocalizacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<uspGetCuantificacionLocalizacionPoblacion_Result> uspGetCuantificacionLocalizacionPoblacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetCuantificacionLocalizacionPoblacion_Result>("uspGetCuantificacionLocalizacionPoblacion", bPINParameter);
        }
    
        public virtual int uspPostCuantificacionLocalizacionPoblacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionLocalizacionPoblacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostCuantificacionLocalizacionPoblacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionLocalizacionPoblacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostInsertarProyectoFocalizacionVA(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostInsertarProyectoFocalizacionVA", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetFocalizacionCuantificacionLocalizacion_Result> uspGetFocalizacionCuantificacionLocalizacion(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetFocalizacionCuantificacionLocalizacion_Result>("uspGetFocalizacionCuantificacionLocalizacion", bPINParameter);
        }
    
        public virtual int uspPostFocalizacionCuantificacionLocalizacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFocalizacionCuantificacionLocalizacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostFocalizacionCuantificacionLocalizacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFocalizacionCuantificacionLocalizacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetIndicadorProductoAgregar_Result> uspGetIndicadorProductoAgregar(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetIndicadorProductoAgregar_Result>("uspGetIndicadorProductoAgregar", bPINParameter);
        }
    
        public virtual int uspPostIndicadorProductoAgregarTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostIndicadorProductoAgregarTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostIndicadorProductoAgregar(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostIndicadorProductoAgregar", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetRegionalizacionIndicadorAgregar_Result> uspGetRegionalizacionIndicadorAgregar(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetRegionalizacionIndicadorAgregar_Result>("uspGetRegionalizacionIndicadorAgregar", bPINParameter);
        }
    
        public virtual int uspPostRegionalizacionIndicadorAgregarTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionIndicadorAgregarTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostRegionalizacionIndicadorAgregar(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionIndicadorAgregar", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetProyectoCompletarInformacion_Result> uspGetProyectoCompletarInformacion(string bPIN, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetProyectoCompletarInformacion_Result>("uspGetProyectoCompletarInformacion", bPINParameter, usuarioParameter, instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostProyectoCompletarInformacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProyectoCompletarInformacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetCuantificacionBeneficiarios_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetCuantificacionBeneficiarios_JSON", bPINParameter);
        }
    
        public virtual int uspPostCuantificacionBeneficiario(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionBeneficiario", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostCuantificacionBeneficiarioTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionBeneficiarioTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetFuentesFinanciacion_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetFuentesFinanciacion_JSON", bPINParameter);
        }
    
        public virtual int uspPostFuentesFinanciacion_JSON(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFuentesFinanciacion_JSON", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostFuentesFinanciacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFuentesFinanciacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversales_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversales_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> UspGetRegionalizacionMetasRecursos_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetRegionalizacionMetasRecursos_JSON", bPINParameter);
        }
    
        public virtual int uspPostLocalizacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostLocalizacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> UspGetLocalizacion_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetLocalizacion_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasCategorias_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasCategorias_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasCategorias(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasCategorias", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasCategoriasTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasCategoriasTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostLocalizacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostLocalizacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int UspPostRegionalizacionMetasRecursos(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostRegionalizacionMetasRecursos", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesBeneficiarios_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesBeneficiarios_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiario(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiario", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiarioTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiarioTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostPoliticasTransversales(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversales", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesMetas_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesMetas_JSON", bPINParameter);
        }
    
        public virtual int UspPostPoliticasTransversalesMetas(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostPoliticasTransversalesMetas", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int UspPostPoliticasTransversalesMetasTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostPoliticasTransversalesMetasTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int UspPostRegionalizacionMetasRecursosTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostRegionalizacionMetasRecursosTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetAgregarPoliticas_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetAgregarPoliticas_JSON", bPINParameter);
        }
    
        public virtual int uspPostAgregarPoliticas(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAgregarPoliticas", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostAgregarPoliticasTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAgregarPoliticasTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesIndicadores_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesIndicadores_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesIndicadores(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesIndicadores", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesIndicadoresTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesIndicadoresTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetRegionalizaicion_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetRegionalizaicion_JSON", bPINParameter);
        }
    
        public virtual int uspPostRegionalizacion(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacion", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostRegionalizacionTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesBeneficiariosCategorias_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesBeneficiariosCategorias_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiariosCategorias(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiariosCategorias", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiariosCategoriasTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiariosCategoriasTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesRelacionadas_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesRelacionadas_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesRelacionadas(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesRelacionadas", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesRelacionadasTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesRelacionadasTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetLocalizacion_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetLocalizacion_Ajustar_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> UspGetRegionalizacion_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetRegionalizacion_Ajustar_JSON", bPINParameter);
        }
    
        public virtual int uspPostRegionalizacion_Ajustar(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacion_Ajustar", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostRegionalizacionTemp_Ajustar(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegionalizacionTemp_Ajustar", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostFuentesFinanciacion_Ajustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFuentesFinanciacion_Ajustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostFuentesFinanciacion_AjustesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFuentesFinanciacion_AjustesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetFuentesFinanciacion_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetFuentesFinanciacion_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int UspPostRegionalizacionMetasRecursos_AjustesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostRegionalizacionMetasRecursos_AjustesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetRegionalizacionMetasRecursos_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetRegionalizacionMetasRecursos_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int UspPostRegionalizacionMetasRecursos_Ajustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostRegionalizacionMetasRecursos_Ajustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesBeneficiarios_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesBeneficiarios_Ajustar_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiario_Ajustar(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiario_Ajustar", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiarioTemp_Ajustar(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiarioTemp_Ajustar", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual int uspPostAgregarPoliticas_AjustarTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAgregarPoliticas_AjustarTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetAgregarPoliticas_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetAgregarPoliticas_Ajustar_JSON", bPINParameter);
        }
    
        public virtual int uspPostAgregarPoliticas_Ajustar(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAgregarPoliticas_Ajustar", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetCuantificacionBeneficiarios_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetCuantificacionBeneficiarios_Ajustar_JSON", bPINParameter);
        }
    
        public virtual int uspPostCuantificacionBeneficiario_Ajustar(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionBeneficiario_Ajustar", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostCuantificacionBeneficiarioTemp_Ajustar(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCuantificacionBeneficiarioTemp_Ajustar", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesBeneficiariosCategorias_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesBeneficiariosCategorias_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiariosCategorias_Ajustes(string json, string usuario, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiariosCategorias_Ajustes", jsonParameter, usuarioParameter, instanciaIdParameter, accionIdParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesBeneficiariosCategoriasTemp_Ajustes(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesBeneficiariosCategoriasTemp_Ajustes", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesIndicadores_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesIndicadores_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesIndicadores_Ajustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesIndicadores_Ajustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesIndicadores_AjustesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesIndicadores_AjustesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetCadenaValor_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetCadenaValor_Ajustes_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesRelacionadas_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesRelacionadas_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int uspPostPoliticasTransversalesRelacionadasAjustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesRelacionadasAjustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesRelacionadasAjustesTemp(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesRelacionadasAjustesTemp", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetPoliticasTransversalesMetas_Ajustar_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetPoliticasTransversalesMetas_Ajustar_JSON", bPINParameter);
        }
    
        public virtual int UspPostPoliticasTransversalesMetas_Ajustar(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostPoliticasTransversalesMetas_Ajustar", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int UspPostPoliticasTransversalesMetasTemp_Ajustar(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostPoliticasTransversalesMetasTemp_Ajustar", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<string> UspGetCadenaValorEntregables_Ajustes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetCadenaValorEntregables_Ajustes_JSON", bPINParameter);
        }
    
        public virtual int uspPostCadenaValorEntregables_Ajustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCadenaValorEntregables_Ajustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostCadenaValor_Ajustes(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCadenaValor_Ajustes", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> UspGetDesagregarRegionalizacion_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetDesagregarRegionalizacion_JSON", bPINParameter);
        }
    
        public virtual int UspPostDesagregarRegionalizacion(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspPostDesagregarRegionalizacion", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetDatosCartaConceptoDespedida_JSON(Nullable<int> tramiteId, Nullable<int> plantillaCartaSeccionId)
        {
            var tramiteIdParameter = tramiteId.HasValue ?
                new ObjectParameter("tramiteId", tramiteId) :
                new ObjectParameter("tramiteId", typeof(int));
    
            var plantillaCartaSeccionIdParameter = plantillaCartaSeccionId.HasValue ?
                new ObjectParameter("plantillaCartaSeccionId", plantillaCartaSeccionId) :
                new ObjectParameter("plantillaCartaSeccionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetDatosCartaConceptoDespedida_JSON", tramiteIdParameter, plantillaCartaSeccionIdParameter);
        }
    
        public virtual int uspPostActualizaCartaDatosDespedida(Nullable<int> cartaId, Nullable<int> cartaSeccionId, Nullable<int> tramiteId, Nullable<int> tipoTramite, string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var cartaIdParameter = cartaId.HasValue ?
                new ObjectParameter("CartaId", cartaId) :
                new ObjectParameter("CartaId", typeof(int));
    
            var cartaSeccionIdParameter = cartaSeccionId.HasValue ?
                new ObjectParameter("CartaSeccionId", cartaSeccionId) :
                new ObjectParameter("CartaSeccionId", typeof(int));
    
            var tramiteIdParameter = tramiteId.HasValue ?
                new ObjectParameter("TramiteId", tramiteId) :
                new ObjectParameter("TramiteId", typeof(int));
    
            var tipoTramiteParameter = tipoTramite.HasValue ?
                new ObjectParameter("TipoTramite", tipoTramite) :
                new ObjectParameter("TipoTramite", typeof(int));
    
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostActualizaCartaDatosDespedida", cartaIdParameter, cartaSeccionIdParameter, tramiteIdParameter, tipoTramiteParameter, jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesFuentes_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesFuentes_JSON", bPINParameter);
        }
    
        public virtual int uspPostActualizaCapituloModificado(Nullable<int> proyectoId, string usuario, string justificacion, Nullable<System.Guid> instanciaId, Nullable<int> seccionCapituloId, Nullable<int> aplicaJustificacion, Nullable<bool> cuenta, Nullable<bool> modificado)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var justificacionParameter = justificacion != null ?
                new ObjectParameter("Justificacion", justificacion) :
                new ObjectParameter("Justificacion", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var seccionCapituloIdParameter = seccionCapituloId.HasValue ?
                new ObjectParameter("SeccionCapituloId", seccionCapituloId) :
                new ObjectParameter("SeccionCapituloId", typeof(int));
    
            var aplicaJustificacionParameter = aplicaJustificacion.HasValue ?
                new ObjectParameter("AplicaJustificacion", aplicaJustificacion) :
                new ObjectParameter("AplicaJustificacion", typeof(int));
    
            var cuentaParameter = cuenta.HasValue ?
                new ObjectParameter("Cuenta", cuenta) :
                new ObjectParameter("Cuenta", typeof(bool));
    
            var modificadoParameter = modificado.HasValue ?
                new ObjectParameter("Modificado", modificado) :
                new ObjectParameter("Modificado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostActualizaCapituloModificado", proyectoIdParameter, usuarioParameter, justificacionParameter, instanciaIdParameter, seccionCapituloIdParameter, aplicaJustificacionParameter, cuentaParameter, modificadoParameter);
        }
    
        public virtual int uspPostCrucePoliticas(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCrucePoliticas", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostLocalizacion_Ajustes(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostLocalizacion_Ajustes", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetCrucePoliticas_JSON(string bPIN, Nullable<int> fuenteId)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var fuenteIdParameter = fuenteId.HasValue ?
                new ObjectParameter("FuenteId", fuenteId) :
                new ObjectParameter("FuenteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetCrucePoliticas_JSON", bPINParameter, fuenteIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasCategoriasIndicadores_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasCategoriasIndicadores_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspGetResumenDistribucionesAnteriores_JSON(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetResumenDistribucionesAnteriores_JSON", instanciaIdParameter);
        }
    }
}
