//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosWBS.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGetFase
    {
        public string NombreFase { get; set; }
        public Nullable<System.Guid> FaseGUID { get; set; }
        public int Id { get; set; }
    }
}
