//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosTransaccional.Persistencia.ModeloSGR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MGAWebContextoSGR : DbContext
    {
        public MGAWebContextoSGR()
            : base("name=MGAWebContextoSGR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int uspPostCambioEstadoProyectoSgr(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> flujoId, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var flujoIdParameter = flujoId.HasValue ?
                new ObjectParameter("FlujoId", flujoId) :
                new ObjectParameter("FlujoId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCambioEstadoProyectoSgr", bPINParameter, nivelIdParameter, flujoIdParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostGeneraBpinSgr(Nullable<decimal> proyectoId, ObjectParameter exitoso)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostGeneraBpinSgr", proyectoIdParameter, exitoso);
        }
    
        public virtual int uspPostIniciarFlujoSgr(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> flujoId, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var flujoIdParameter = flujoId.HasValue ?
                new ObjectParameter("FlujoId", flujoId) :
                new ObjectParameter("FlujoId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostIniciarFlujoSgr", bPINParameter, nivelIdParameter, flujoIdParameter, usuarioParameter, errorValidacionNegocio);
        }
    }
}
