//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.Backbone.Web.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNP.Backbone.Web.UI.App_GlobalResources.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio consumido no contiene registros para mostrar..
        /// </summary>
        public static string ApiArregloVacio {
            get {
                return ResourceManager.GetString("ApiArregloVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ArchivoGuardado.
        /// </summary>
        public static string ArchivoGuardado {
            get {
                return ResourceManager.GetString("ArchivoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes archivos {0} no tienen categoria asignada..
        /// </summary>
        public static string ArchivosSinCategoria {
            get {
                return ResourceManager.GetString("ArchivosSinCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para subir un archivo haga clic aquí o.
        /// </summary>
        public static string ArrastreAqui1 {
            get {
                return ResourceManager.GetString("ArrastreAqui1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a arrastre el archivo.
        /// </summary>
        public static string ArrastreAqui2 {
            get {
                return ResourceManager.GetString("ArrastreAqui2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar Metadatos.
        /// </summary>
        public static string BotonAsociarMetadatos {
            get {
                return ResourceManager.GetString("BotonAsociarMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BotonBuscarFiltro {
            get {
                return ResourceManager.GetString("BotonBuscarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BotonCancelarCarga {
            get {
                return ResourceManager.GetString("BotonCancelarCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string BotonCargarArchivos {
            get {
                return ResourceManager.GetString("BotonCargarArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar y consultar archivos.
        /// </summary>
        public static string BotonCargarConsultarArchivos {
            get {
                return ResourceManager.GetString("BotonCargarConsultarArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BotonCerrarCarga {
            get {
                return ResourceManager.GetString("BotonCerrarCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string BotonLimpiarFiltro {
            get {
                return ResourceManager.GetString("BotonLimpiarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIGUIENTE.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea cancelar la asociación de los metadatos a los archivos cargados?.
        /// </summary>
        public static string CancelarAsociaciónMetadatos {
            get {
                return ResourceManager.GetString("CancelarAsociaciónMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La carga del archivo se cancelará, ¿Está seguro que desea continuar?.
        /// </summary>
        public static string CancelarCargaArchivos {
            get {
                return ResourceManager.GetString("CancelarCargaArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de archivos a cargar no válido. Número de archivos permitidos: {0}.
        /// </summary>
        public static string CantitadArchivosInvalidos {
            get {
                return ResourceManager.GetString("CantitadArchivosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe categoría sin seleccionar y metadatos obligatorios.
        /// </summary>
        public static string CategoriasMetadatosObligatorias {
            get {
                return ResourceManager.GetString("CategoriasMetadatosObligatorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe categoría sin seleccionar.
        /// </summary>
        public static string CategoriasObligatorias {
            get {
                return ResourceManager.GetString("CategoriasObligatorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de cancelar los cambios realizados?.
        /// </summary>
        public static string ConfirmaCancelar {
            get {
                return ResourceManager.GetString("ConfirmaCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está Seguro de Salir sin Guardar?.
        /// </summary>
        public static string ConfirmaCancelarEdicionFilaPrevisualizar {
            get {
                return ResourceManager.GetString("ConfirmaCancelarEdicionFilaPrevisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea ejecutar el servicio asociado?.
        /// </summary>
        public static string confirmaEjecutarSerivicio {
            get {
                return ResourceManager.GetString("confirmaEjecutarSerivicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea guardar el archivo?.
        /// </summary>
        public static string ConfirmaGuardarArchivo {
            get {
                return ResourceManager.GetString("ConfirmaGuardarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea guardar el formulario temporalmente?.
        /// </summary>
        public static string ConfirmarAccionGuardar {
            get {
                return ResourceManager.GetString("ConfirmarAccionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea guardar el formulario definitivamente?.
        /// </summary>
        public static string ConfirmarAccionSiguiente {
            get {
                return ResourceManager.GetString("ConfirmarAccionSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el registro?.
        /// </summary>
        public static string ConfirmarEliminarRegistro {
            get {
                return ResourceManager.GetString("ConfirmarEliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La siguiente acción va a generar una ficha temporal. &lt;br/&gt;¿Desea continuar?.
        /// </summary>
        public static string ConfirmarFichaBorrador {
            get {
                return ResourceManager.GetString("ConfirmarFichaBorrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de Guardar?.
        /// </summary>
        public static string ConfirmarGuardar {
            get {
                return ResourceManager.GetString("ConfirmarGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea crear un nuevo periodo? Todas las instancias actuales que todavía se encuentren en estado abiertas serán detenidas y se crearan nuevas para el nuevo periodo.
        /// </summary>
        public static string ConfirmarNuevoPeriodoProgramacion {
            get {
                return ResourceManager.GetString("ConfirmarNuevoPeriodoProgramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea iniciar el proceso de creación de instancias masivas?.
        /// </summary>
        public static string ConfirmarProgramacionIniciarProceso {
            get {
                return ResourceManager.GetString("ConfirmarProgramacionIniciarProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar Metadatos.
        /// </summary>
        public static string ConsultarMetadatos {
            get {
                return ResourceManager.GetString("ConsultarMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se ha eliminado exitosamente.
        /// </summary>
        public static string EliminadoExitosoMetadato {
            get {
                return ResourceManager.GetString("EliminadoExitosoMetadato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar este metadato?.
        /// </summary>
        public static string EliminarMetadato {
            get {
                return ResourceManager.GetString("EliminarMetadato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la información en el formulario..
        /// </summary>
        public static string ErrorCargaFormulario {
            get {
                return ResourceManager.GetString("ErrorCargaFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar formulario..
        /// </summary>
        public static string ErrorGuardadoFormulario {
            get {
                return ResourceManager.GetString("ErrorGuardadoFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un problema al momento de guardar. {0} &lt;/br&gt;
        ///Intente nuevamente. Si el problema persiste contacte al administrador..
        /// </summary>
        public static string ErrorGuardadoTemporal {
            get {
                return ResourceManager.GetString("ErrorGuardadoTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer el contenido de la URL..
        /// </summary>
        public static string ErrorLecturaContenido {
            get {
                return ResourceManager.GetString("ErrorLecturaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo problemas para obtener la información.
        /// </summary>
        public static string ErrorObtenerDatos {
            get {
                return ResourceManager.GetString("ErrorObtenerDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene entidades asociadas a ninguno de sus roles.
        /// </summary>
        public static string ErrorRolesSinEntidades {
            get {
                return ResourceManager.GetString("ErrorRolesSinEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Acción del boton no encontrada..
        /// </summary>
        public static string errorTipoAccionCustom {
            get {
                return ResourceManager.GetString("errorTipoAccionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible obtener información de esta URL..
        /// </summary>
        public static string ErrorUrl {
            get {
                return ResourceManager.GetString("ErrorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene opciones habilitadas para su(s) rol(es).
        /// </summary>
        public static string ErrorUsuarioConRolSinOpciones {
            get {
                return ResourceManager.GetString("ErrorUsuarioConRolSinOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene permisos para ejecutar la accion.
        /// </summary>
        public static string ErrorUsuarioSinPermisoAccion {
            get {
                return ResourceManager.GetString("ErrorUsuarioSinPermisoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene permisos para acceder a la aplicación..
        /// </summary>
        public static string ErrorUsuarioSinPermisosAplicacion {
            get {
                return ResourceManager.GetString("ErrorUsuarioSinPermisosAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        public static string EtiquetaFiltro {
            get {
                return ResourceManager.GetString("EtiquetaFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione o arrastre uno o varios archivos a la vez.
        /// </summary>
        public static string EtiquetaSeleccionArchivos {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuestionario enviado satisfactoriamente al siguiente paso.
        /// </summary>
        public static string ExitoGuardadoFormulario {
            get {
                return ResourceManager.GetString("ExitoGuardadoFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficha generada correctamente.
        /// </summary>
        public static string FichaGeneradaCorrectamente {
            get {
                return ResourceManager.GetString("FichaGeneradaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato para la URL debe ser &apos;http://www.pagina.com&apos; o &apos;https://www.pagina.com..
        /// </summary>
        public static string FormatoURL {
            get {
                return ResourceManager.GetString("FormatoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuestionario enviado satisfactoriamente al siguiente paso.
        /// </summary>
        public static string GuardadoDefinitivo {
            get {
                return ResourceManager.GetString("GuardadoDefinitivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario fue guardado temporalmente. .
        /// </summary>
        public static string GuardadoTemporal {
            get {
                return ResourceManager.GetString("GuardadoTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información adicional.
        /// </summary>
        public static string InformacionAdicionalError {
            get {
                return ResourceManager.GetString("InformacionAdicionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        public static string InsertarRegistro {
            get {
                return ResourceManager.GetString("InsertarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos fueron eliminados correctamente.
        /// </summary>
        public static string MensajeExitoBorradoConpesTramiteVF {
            get {
                return ResourceManager.GetString("MensajeExitoBorradoConpesTramiteVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han adicionado líneas de información en la parte inferior de la tabla &apos;Documentos Conpes&apos;.
        /// </summary>
        public static string MensajeExitoConpesTramiteVF {
            get {
                return ResourceManager.GetString("MensajeExitoConpesTramiteVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos fueron agregados y guardados con éxito.
        /// </summary>
        public static string MensajeExitoDatosGuardados {
            get {
                return ResourceManager.GetString("MensajeExitoDatosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensión de archivo no permitida.
        /// </summary>
        public static string MensajeExtensionNoValida {
            get {
                return ResourceManager.GetString("MensajeExtensionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metadatos guardados exitosamente.
        /// </summary>
        public static string MetadatosGuardados {
            get {
                return ResourceManager.GetString("MetadatosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen metadatos obligatorios.
        /// </summary>
        public static string MetadatosObligatorios {
            get {
                return ResourceManager.GetString("MetadatosObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay proyectos disponibles.
        /// </summary>
        public static string NoHayProyectosDisponibles {
            get {
                return ResourceManager.GetString("NoHayProyectosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen resultados aún para esta búsqueda.
        /// </summary>
        public static string NoResultadosBusqueda {
            get {
                return ResourceManager.GetString("NoResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los filtros deseados para obtener resultados.
        /// </summary>
        public static string SeleccioneFiltrosMensaje {
            get {
                return ResourceManager.GetString("SeleccioneFiltrosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione o arrastre el archivo.
        /// </summary>
        public static string SeleccioneOArrastreArchivo {
            get {
                return ResourceManager.GetString("SeleccioneOArrastreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño máximo de carga por archivo no válido. Tamaño máximo por archivo permitido: {0}.
        /// </summary>
        public static string TamañoMáximoPorArchivoInvalido {
            get {
                return ResourceManager.GetString("TamañoMáximoPorArchivoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño total de archivos no válido. Tamaño máximo total permitido: {0}.
        /// </summary>
        public static string TamañoMáximoTotalInvalido {
            get {
                return ResourceManager.GetString("TamañoMáximoTotalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string TextoAcciones {
            get {
                return ResourceManager.GetString("TextoAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string TextoBotonContinuar {
            get {
                return ResourceManager.GetString("TextoBotonContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Tarea.
        /// </summary>
        public static string TextoCrearTarea {
            get {
                return ResourceManager.GetString("TextoCrearTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una entidad.
        /// </summary>
        public static string TextoDebeSeleccionarEntidad {
            get {
                return ResourceManager.GetString("TextoDebeSeleccionarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        public static string TextoEntidad {
            get {
                return ResourceManager.GetString("TextoEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen resultados aún para esta búsqueda.
        /// </summary>
        public static string TextoNoResultadosBusqueda {
            get {
                return ResourceManager.GetString("TextoNoResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Entidad.
        /// </summary>
        public static string TextoSeleccionarEntidad {
            get {
                return ResourceManager.GetString("TextoSeleccionarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los filtros deseados para obtener resultados.
        /// </summary>
        public static string TextoSeleccioneFiltrosMensaje {
            get {
                return ResourceManager.GetString("TextoSeleccioneFiltrosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar metadatos.
        /// </summary>
        public static string TooltipBotonAsociarMetadatos {
            get {
                return ResourceManager.GetString("TooltipBotonAsociarMetadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar cargar de archivos.
        /// </summary>
        public static string TooltipBotonCancelarCarga {
            get {
                return ResourceManager.GetString("TooltipBotonCancelarCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url no asignada..
        /// </summary>
        public static string UrlNoAsignada {
            get {
                return ResourceManager.GetString("UrlNoAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos seleccionados serán eliminados.
        /// </summary>
        public static string ValidacionBorradoConpesTramiteVF {
            get {
                return ResourceManager.GetString("ValidacionBorradoConpesTramiteVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de continuar?.
        /// </summary>
        public static string ValidacionBorradoConpesTramiteVFCuerpo {
            get {
                return ResourceManager.GetString("ValidacionBorradoConpesTramiteVFCuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo {0} ya se encuentra listo para cargar..
        /// </summary>
        public static string YaExisteNombreParaCargar {
            get {
                return ResourceManager.GetString("YaExisteNombreParaCargar", resourceCulture);
            }
        }
    }
}
