//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosEnrutamiento.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Object { get; set; }
        public Nullable<int> ProjectTypeId { get; set; }
        public int ProcessId { get; set; }
        public int SectorId { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> BankTypeId { get; set; }
        public Nullable<int> AdministrativeSectorId { get; set; }
        public Nullable<int> NationalEntityId { get; set; }
        public Nullable<int> ResourceTypeId { get; set; }
        public string ParticipantsCoordination { get; set; }
        public Nullable<int> AffectedPeople { get; set; }
        public string AffectedPeopleSource { get; set; }
        public Nullable<int> ObjectivePeople { get; set; }
        public string ObjectivePeopleSource { get; set; }
        public Nullable<bool> BenefitCostEvaluation { get; set; }
        public Nullable<bool> CostEfficiencyEvaluation { get; set; }
        public Nullable<bool> MultiCriteriaEvaluation { get; set; }
        public string BPIN { get; set; }
        public int Status { get; set; }
        public string ProjectSite { get; set; }
        public string Description { get; set; }
        public Nullable<int> PeriodZero { get; set; }
        public string Localization { get; set; }
        public Nullable<double> OpportunityInterestRate { get; set; }
        public string OpportunityRateDescription { get; set; }
        public Nullable<int> ObjectivePeoplePopulationType { get; set; }
        public Nullable<int> AffectedPeoplePopulationType { get; set; }
        public string OCAD { get; set; }
        public string Formulator { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsCapture { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> SpecificExpenseTypeId { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> MGAProjectId { get; set; }
        public Nullable<int> VersionType { get; set; }
        public Nullable<System.DateTime> VersionCreatedDate { get; set; }
        public bool IsBaseProject { get; set; }
        public Nullable<int> BaseProjectId { get; set; }
        public Nullable<decimal> IdProjectMGA { get; set; }
        public Nullable<int> IsViabled { get; set; }
        public Nullable<bool> isInitiativeForPeace { get; set; }
        public Nullable<bool> isInitiativeForPeaceFromBaseProject { get; set; }
        public Nullable<int> CRTypeId { get; set; }
        public bool PorCerrar { get; set; }
        public Nullable<int> ExpenseTypeId { get; set; }
        public Nullable<int> FinancingSubProgramId { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
    }
}
