//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.ModeloSGR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MGAWebContextoSGR : DbContext
    {
        public MGAWebContextoSGR()
            : base("name=MGAWebContextoSGR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parametros> Parametros { get; set; }
    
        public virtual ObjectResult<string> uspGetSGR_Transversal_LeerParametro(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("Parametro", parametro) :
                new ObjectParameter("Parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Transversal_LeerParametro", parametroParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Acuerdo_LeerProyecto(Nullable<int> proyectoId, Nullable<System.Guid> nivelId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Acuerdo_LeerProyecto", proyectoIdParameter, nivelIdParameter);
        }
    
        public virtual int uspPostSGR_Acuerdo_GuardarProyecto(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_Acuerdo_GuardarProyecto", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_LeerListas(Nullable<System.Guid> nivelId, Nullable<int> proyectoId, string nombreLista)
        {
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("nivelId", nivelId) :
                new ObjectParameter("nivelId", typeof(System.Guid));
    
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(int));
    
            var nombreListaParameter = nombreLista != null ?
                new ObjectParameter("nombreLista", nombreLista) :
                new ObjectParameter("nombreLista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_LeerListas", nivelIdParameter, proyectoIdParameter, nombreListaParameter);
        }
    
        public virtual ObjectResult<uspGetEjecutoresAsociados_Result> uspGetEjecutoresAsociados(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetEjecutoresAsociados_Result>("uspGetEjecutoresAsociados", proyectoIdParameter);
        }
    
        public virtual ObjectResult<uspGetTipoEjecutor_Result> uspGetTipoEjecutor(string nit, Nullable<int> tipoEntidadId, Nullable<int> entidadId)
        {
            var nitParameter = nit != null ?
                new ObjectParameter("nit", nit) :
                new ObjectParameter("nit", typeof(string));
    
            var tipoEntidadIdParameter = tipoEntidadId.HasValue ?
                new ObjectParameter("tipoEntidadId", tipoEntidadId) :
                new ObjectParameter("tipoEntidadId", typeof(int));
    
            var entidadIdParameter = entidadId.HasValue ?
                new ObjectParameter("entidadId", entidadId) :
                new ObjectParameter("entidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetTipoEjecutor_Result>("uspGetTipoEjecutor", nitParameter, tipoEntidadIdParameter, entidadIdParameter);
        }
    
        public virtual int uspPostEjecutoresAsociados(Nullable<int> proyectoId, Nullable<int> ejecutorId, string usuario, Nullable<int> tipoEjecutorId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(int));
    
            var ejecutorIdParameter = ejecutorId.HasValue ?
                new ObjectParameter("ejecutorId", ejecutorId) :
                new ObjectParameter("ejecutorId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var tipoEjecutorIdParameter = tipoEjecutorId.HasValue ?
                new ObjectParameter("tipoEjecutorId", tipoEjecutorId) :
                new ObjectParameter("tipoEjecutorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostEjecutoresAsociados", proyectoIdParameter, ejecutorIdParameter, usuarioParameter, tipoEjecutorIdParameter);
        }
    
        public virtual int uspPostEliminarEjecutorAsociado(Nullable<int> ejecutorAsociadoId, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var ejecutorAsociadoIdParameter = ejecutorAsociadoId.HasValue ?
                new ObjectParameter("EjecutorAsociadoId", ejecutorAsociadoId) :
                new ObjectParameter("EjecutorAsociadoId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostEliminarEjecutorAsociado", ejecutorAsociadoIdParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspGetCrucePoliticas_JSONSgr(string bPIN, Nullable<int> fuenteId)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var fuenteIdParameter = fuenteId.HasValue ?
                new ObjectParameter("FuenteId", fuenteId) :
                new ObjectParameter("FuenteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetCrucePoliticas_JSONSgr", bPINParameter, fuenteIdParameter);
        }
    
        public virtual int DatosGeneralesProyectoSGR(Nullable<int> proyectoId, Nullable<System.Guid> nivelId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DatosGeneralesProyectoSGR", proyectoIdParameter, nivelIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesFuentes_JSONSgr(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesFuentes_JSONSgr", bPINParameter);
        }
    
        public virtual int uspGetPoliticasTransversalesCategorias_JSONSgr(string bPIN, Nullable<int> fuenteId, Nullable<int> politicaId)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var fuenteIdParameter = fuenteId.HasValue ?
                new ObjectParameter("FuenteId", fuenteId) :
                new ObjectParameter("FuenteId", typeof(int));
    
            var politicaIdParameter = politicaId.HasValue ?
                new ObjectParameter("PoliticaId", politicaId) :
                new ObjectParameter("PoliticaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetPoliticasTransversalesCategorias_JSONSgr", bPINParameter, fuenteIdParameter, politicaIdParameter);
        }
    
        public virtual int uspGetPoliticasTransversalesFuentesIndicadores_JSONSgr(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetPoliticasTransversalesFuentesIndicadores_JSONSgr", bPINParameter);
        }
    
        public virtual ObjectResult<string> UspGetDesagregarRegionalizacion_JSONSgr(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetDesagregarRegionalizacion_JSONSgr", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspGetCrucePoliticasAjustes_JSONSgr(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetCrucePoliticasAjustes_JSONSgr", instanciaIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasCategoriasIndicadores_JSONSgr(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasCategoriasIndicadores_JSONSgr", instanciaIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversales_Ajustes_JSONSgr(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversales_Ajustes_JSONSgr", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesCategorias_Ajustes_JSONSgr(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesCategorias_Ajustes_JSONSgr", instanciaIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPoliticasTransversalesCategorias_Ajustes_Resumen_JSONSgr(string instanciaId)
        {
            var instanciaIdParameter = instanciaId != null ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPoliticasTransversalesCategorias_Ajustes_Resumen_JSONSgr", instanciaIdParameter);
        }
    
        public virtual int uspPostAgregarPoliticas_ajustesSgr(string json, string usuario, Nullable<System.Guid> formularioId, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var formularioIdParameter = formularioId.HasValue ?
                new ObjectParameter("FormularioId", formularioId) :
                new ObjectParameter("FormularioId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAgregarPoliticas_ajustesSgr", jsonParameter, usuarioParameter, formularioIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostCategoriasIndicadoresSgr(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCategoriasIndicadoresSgr", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostEliminarCategoriasProyectoSgr(Nullable<int> proyectoId, Nullable<int> politicaId, Nullable<int> dimensionId, ObjectParameter errorValidacionNegocio)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var politicaIdParameter = politicaId.HasValue ?
                new ObjectParameter("PoliticaId", politicaId) :
                new ObjectParameter("PoliticaId", typeof(int));
    
            var dimensionIdParameter = dimensionId.HasValue ?
                new ObjectParameter("DimensionId", dimensionId) :
                new ObjectParameter("DimensionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostEliminarCategoriasProyectoSgr", proyectoIdParameter, politicaIdParameter, dimensionIdParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostPoliticasTransversalesProyectoEliminarSgr(Nullable<int> proyectoId, Nullable<int> politicaId, ObjectParameter errorValidacionNegocio)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var politicaIdParameter = politicaId.HasValue ?
                new ObjectParameter("PoliticaId", politicaId) :
                new ObjectParameter("PoliticaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPoliticasTransversalesProyectoEliminarSgr", proyectoIdParameter, politicaIdParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetObtenerPreguntasEspecificasComponenteCustom_Result> uspGetObtenerPreguntasEspecificasComponenteCustom(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, string nombreComponentePregunta, string listaRoles_Json)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var nombreComponentePreguntaParameter = nombreComponentePregunta != null ?
                new ObjectParameter("NombreComponentePregunta", nombreComponentePregunta) :
                new ObjectParameter("NombreComponentePregunta", typeof(string));
    
            var listaRoles_JsonParameter = listaRoles_Json != null ?
                new ObjectParameter("ListaRoles_Json", listaRoles_Json) :
                new ObjectParameter("ListaRoles_Json", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerPreguntasEspecificasComponenteCustom_Result>("uspGetObtenerPreguntasEspecificasComponenteCustom", bPINParameter, nivelIdParameter, instanciaIdParameter, nombreComponentePreguntaParameter, listaRoles_JsonParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerPreguntasGeneralesComponenteCustom_Result> uspGetObtenerPreguntasGeneralesComponenteCustom(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, string nombreComponentePregunta, string listaRoles)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var nombreComponentePreguntaParameter = nombreComponentePregunta != null ?
                new ObjectParameter("NombreComponentePregunta", nombreComponentePregunta) :
                new ObjectParameter("NombreComponentePregunta", typeof(string));
    
            var listaRolesParameter = listaRoles != null ?
                new ObjectParameter("ListaRoles", listaRoles) :
                new ObjectParameter("ListaRoles", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerPreguntasGeneralesComponenteCustom_Result>("uspGetObtenerPreguntasGeneralesComponenteCustom", bPINParameter, nivelIdParameter, instanciaIdParameter, nombreComponentePreguntaParameter, listaRolesParameter);
        }
    
        public virtual ObjectResult<uspGetSGR_Viabilidad_LeerInformacionGeneral_Result> uspGetSGR_Viabilidad_LeerInformacionGeneral(Nullable<int> proyectoId, Nullable<System.Guid> instanciaId, string tipoConceptoViabilidadCode)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var tipoConceptoViabilidadCodeParameter = tipoConceptoViabilidadCode != null ?
                new ObjectParameter("TipoConceptoViabilidadCode", tipoConceptoViabilidadCode) :
                new ObjectParameter("TipoConceptoViabilidadCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_Viabilidad_LeerInformacionGeneral_Result>("uspGetSGR_Viabilidad_LeerInformacionGeneral", proyectoIdParameter, instanciaIdParameter, tipoConceptoViabilidadCodeParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Viabilidad_LeerParametricas(Nullable<int> proyectoId, Nullable<System.Guid> nivelId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Viabilidad_LeerParametricas", proyectoIdParameter, nivelIdParameter);
        }
    
        public virtual int uspPostSGR_Viabilidad_GuardarInformacionBasica(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_Viabilidad_GuardarInformacionBasica", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetObtenerPreguntasEspecificasComponenteCustomSGR_Result> uspGetObtenerPreguntasEspecificasComponenteCustomSGR(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, string nombreComponentePregunta, string listaRoles_Json)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var nombreComponentePreguntaParameter = nombreComponentePregunta != null ?
                new ObjectParameter("NombreComponentePregunta", nombreComponentePregunta) :
                new ObjectParameter("NombreComponentePregunta", typeof(string));
    
            var listaRoles_JsonParameter = listaRoles_Json != null ?
                new ObjectParameter("ListaRoles_Json", listaRoles_Json) :
                new ObjectParameter("ListaRoles_Json", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerPreguntasEspecificasComponenteCustomSGR_Result>("uspGetObtenerPreguntasEspecificasComponenteCustomSGR", bPINParameter, nivelIdParameter, instanciaIdParameter, nombreComponentePreguntaParameter, listaRoles_JsonParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerPreguntasGeneralesComponenteCustomSGR_Result> uspGetObtenerPreguntasGeneralesComponenteCustomSGR(string bPIN, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, string nombreComponentePregunta, string listaRoles)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var nombreComponentePreguntaParameter = nombreComponentePregunta != null ?
                new ObjectParameter("NombreComponentePregunta", nombreComponentePregunta) :
                new ObjectParameter("NombreComponentePregunta", typeof(string));
    
            var listaRolesParameter = listaRoles != null ?
                new ObjectParameter("ListaRoles", listaRoles) :
                new ObjectParameter("ListaRoles", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerPreguntasGeneralesComponenteCustomSGR_Result>("uspGetObtenerPreguntasGeneralesComponenteCustomSGR", bPINParameter, nivelIdParameter, instanciaIdParameter, nombreComponentePreguntaParameter, listaRolesParameter);
        }
    
        public virtual int uspPostGeneracionCuestionarioPreguntasPersonalizadasCustomSGR(string jsonData, Nullable<System.Guid> instanciaId, Nullable<int> seccionCapituloId, string usuario, ObjectParameter resultado)
        {
            var jsonDataParameter = jsonData != null ?
                new ObjectParameter("JsonData", jsonData) :
                new ObjectParameter("JsonData", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var seccionCapituloIdParameter = seccionCapituloId.HasValue ?
                new ObjectParameter("SeccionCapituloId", seccionCapituloId) :
                new ObjectParameter("SeccionCapituloId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostGeneracionCuestionarioPreguntasPersonalizadasCustomSGR", jsonDataParameter, instanciaIdParameter, seccionCapituloIdParameter, usuarioParameter, resultado);
        }
    
        public virtual ObjectResult<uspGetSGR_TipoDocumentosSoportePorRol_Result> uspGetSGR_TipoDocumentosSoportePorRol(Nullable<int> tipoTramiteId, string rol, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<int> tramiteId)
        {
            var tipoTramiteIdParameter = tipoTramiteId.HasValue ?
                new ObjectParameter("tipoTramiteId", tipoTramiteId) :
                new ObjectParameter("tipoTramiteId", typeof(int));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("nivelId", nivelId) :
                new ObjectParameter("nivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("instanciaId", instanciaId) :
                new ObjectParameter("instanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(System.Guid));
    
            var tramiteIdParameter = tramiteId.HasValue ?
                new ObjectParameter("tramiteId", tramiteId) :
                new ObjectParameter("tramiteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_TipoDocumentosSoportePorRol_Result>("uspGetSGR_TipoDocumentosSoportePorRol", tipoTramiteIdParameter, rolParameter, nivelIdParameter, instanciaIdParameter, accionIdParameter, tramiteIdParameter);
        }
    
        public virtual int uspPostProyectoViabilidadInvolucrados(string jsonData, Nullable<int> proyectoId, string usuario, ObjectParameter resultado)
        {
            var jsonDataParameter = jsonData != null ?
                new ObjectParameter("JsonData", jsonData) :
                new ObjectParameter("JsonData", typeof(string));
    
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProyectoViabilidadInvolucrados", jsonDataParameter, proyectoIdParameter, usuarioParameter, resultado);
        }
    
        public virtual int uspPostProyectoViabilidadInvolucradosEliminar(Nullable<int> id, ObjectParameter errorValidacionNegocio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProyectoViabilidadInvolucradosEliminar", idParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspPostPoliticasTransversalesCategoriasAjustesSgr(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspPostPoliticasTransversalesCategoriasAjustesSgr", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetObtenerProyectoViabilidadInvolucradosFirma_Result> uspGetObtenerProyectoViabilidadInvolucradosFirma(Nullable<System.Guid> instanciaId, Nullable<int> tipoConceptoViabilidadId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var tipoConceptoViabilidadIdParameter = tipoConceptoViabilidadId.HasValue ?
                new ObjectParameter("TipoConceptoViabilidadId", tipoConceptoViabilidadId) :
                new ObjectParameter("TipoConceptoViabilidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerProyectoViabilidadInvolucradosFirma_Result>("uspGetObtenerProyectoViabilidadInvolucradosFirma", instanciaIdParameter, tipoConceptoViabilidadIdParameter);
        }
    
        public virtual int uspPostFirmaUsuarioViabilidadSgr(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostFirmaUsuarioViabilidadSgr", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspGetMensajeEstadoProyectoSgr(Nullable<System.Guid> instanciaId, ObjectParameter mensaje)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetMensajeEstadoProyectoSgr", instanciaIdParameter, mensaje);
        }
    
        public virtual ObjectResult<uspGetEntidadesSolicitarCtus_Result> uspGetEntidadesSolicitarCtus(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetEntidadesSolicitarCtus_Result>("uspGetEntidadesSolicitarCtus", proyectoIdParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerProyectoCtus_Result> uspGetObtenerProyectoCtus(Nullable<int> proyectoId, Nullable<System.Guid> instancia)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaParameter = instancia.HasValue ?
                new ObjectParameter("Instancia", instancia) :
                new ObjectParameter("Instancia", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerProyectoCtus_Result>("uspGetObtenerProyectoCtus", proyectoIdParameter, instanciaParameter);
        }
    
        public virtual int uspPostProyectoSolicitarCTUS(string jsonData, Nullable<int> proyectoId, string usuario, ObjectParameter resultado)
        {
            var jsonDataParameter = jsonData != null ?
                new ObjectParameter("JsonData", jsonData) :
                new ObjectParameter("JsonData", typeof(string));
    
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostProyectoSolicitarCTUS", jsonDataParameter, proyectoIdParameter, usuarioParameter, resultado);
        }
    
        public virtual int uspPostSGR_CTUS_GuardarProyectoCtusConcepto(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_CTUS_GuardarProyectoCtusConcepto", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetSGR_CTUS_LeerProyectoCtusConcepto_Result> uspGetSGR_CTUS_LeerProyectoCtusConcepto(Nullable<int> proyectoCtusId)
        {
            var proyectoCtusIdParameter = proyectoCtusId.HasValue ?
                new ObjectParameter("ProyectoCtusId", proyectoCtusId) :
                new ObjectParameter("ProyectoCtusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_CTUS_LeerProyectoCtusConcepto_Result>("uspGetSGR_CTUS_LeerProyectoCtusConcepto", proyectoCtusIdParameter);
        }
    
        public virtual ObjectResult<uspGetSGR_CTUS_LeerProyectoCtusUsuarioEncargado_Result> uspGetSGR_CTUS_LeerProyectoCtusUsuarioEncargado(Nullable<int> proyectoCtusId, Nullable<System.Guid> instanciaId)
        {
            var proyectoCtusIdParameter = proyectoCtusId.HasValue ?
                new ObjectParameter("ProyectoCtusId", proyectoCtusId) :
                new ObjectParameter("ProyectoCtusId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_CTUS_LeerProyectoCtusUsuarioEncargado_Result>("uspGetSGR_CTUS_LeerProyectoCtusUsuarioEncargado", proyectoCtusIdParameter, instanciaIdParameter);
        }
    
        public virtual int uspPostSGR_CTUS_GuardarResultadoConceptoCtus(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_CTUS_GuardarResultadoConceptoCtus", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetConceptosEmitidos_JSON(string bPIN, Nullable<int> tipoConcepto)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var tipoConceptoParameter = tipoConcepto.HasValue ?
                new ObjectParameter("TipoConcepto", tipoConcepto) :
                new ObjectParameter("TipoConcepto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetConceptosEmitidos_JSON", bPINParameter, tipoConceptoParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerRolDirectorProyectoCtus_Result> uspGetObtenerRolDirectorProyectoCtus(Nullable<int> proyectoId, Nullable<System.Guid> instanciaId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerRolDirectorProyectoCtus_Result>("uspGetObtenerRolDirectorProyectoCtus", proyectoIdParameter, instanciaIdParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerProyectoViabilidadInvolucrados_Result> uspGetObtenerProyectoViabilidadInvolucrados(Nullable<int> proyectoId, Nullable<int> tipoConceptoViabilidadId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var tipoConceptoViabilidadIdParameter = tipoConceptoViabilidadId.HasValue ?
                new ObjectParameter("TipoConceptoViabilidadId", tipoConceptoViabilidadId) :
                new ObjectParameter("TipoConceptoViabilidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerProyectoViabilidadInvolucrados_Result>("uspGetObtenerProyectoViabilidadInvolucrados", proyectoIdParameter, tipoConceptoViabilidadIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> uspPostAutorizacionAccionesPorInstanciaSubFlujoOCADPaz(Nullable<System.Guid> instanciaId, Nullable<System.Guid> rolId, string usuario)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("uspPostAutorizacionAccionesPorInstanciaSubFlujoOCADPaz", instanciaIdParameter, rolIdParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_ValidarAsignacionTecnicoOcadPaz(Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("instanciaId", instanciaId) :
                new ObjectParameter("instanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_ValidarAsignacionTecnicoOcadPaz", instanciaIdParameter, accionIdParameter);
        }
    
        public virtual ObjectResult<UspValidacionOCADPazSgr_Result> UspValidacionOCADPazSgr(string proyectoId, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, Nullable<System.Guid> flujoId)
        {
            var proyectoIdParameter = proyectoId != null ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var flujoIdParameter = flujoId.HasValue ?
                new ObjectParameter("FlujoId", flujoId) :
                new ObjectParameter("FlujoId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspValidacionOCADPazSgr_Result>("UspValidacionOCADPazSgr", proyectoIdParameter, nivelIdParameter, instanciaIdParameter, flujoIdParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerProyectosVerificacionOcadPazSgr_Result> uspGetObtenerProyectosVerificacionOcadPazSgr(Nullable<System.Guid> idTipoObjetoNegocio, string idUsuarioDNP, string listRol, string listNivel, string listSubPasos, Nullable<int> validarActual)
        {
            var idTipoObjetoNegocioParameter = idTipoObjetoNegocio.HasValue ?
                new ObjectParameter("IdTipoObjetoNegocio", idTipoObjetoNegocio) :
                new ObjectParameter("IdTipoObjetoNegocio", typeof(System.Guid));
    
            var idUsuarioDNPParameter = idUsuarioDNP != null ?
                new ObjectParameter("IdUsuarioDNP", idUsuarioDNP) :
                new ObjectParameter("IdUsuarioDNP", typeof(string));
    
            var listRolParameter = listRol != null ?
                new ObjectParameter("listRol", listRol) :
                new ObjectParameter("listRol", typeof(string));
    
            var listNivelParameter = listNivel != null ?
                new ObjectParameter("listNivel", listNivel) :
                new ObjectParameter("listNivel", typeof(string));
    
            var listSubPasosParameter = listSubPasos != null ?
                new ObjectParameter("listSubPasos", listSubPasos) :
                new ObjectParameter("listSubPasos", typeof(string));
    
            var validarActualParameter = validarActual.HasValue ?
                new ObjectParameter("validarActual", validarActual) :
                new ObjectParameter("validarActual", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerProyectosVerificacionOcadPazSgr_Result>("uspGetObtenerProyectosVerificacionOcadPazSgr", idTipoObjetoNegocioParameter, idUsuarioDNPParameter, listRolParameter, listNivelParameter, listSubPasosParameter, validarActualParameter);
        }
    
        public virtual ObjectResult<uspGetObtenerUsuariosVerificacionOcadPazSgr_Result> uspGetObtenerUsuariosVerificacionOcadPazSgr(Nullable<System.Guid> rolId, Nullable<int> entidadId)
        {
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(System.Guid));
    
            var entidadIdParameter = entidadId.HasValue ?
                new ObjectParameter("EntidadId", entidadId) :
                new ObjectParameter("EntidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetObtenerUsuariosVerificacionOcadPazSgr_Result>("uspGetObtenerUsuariosVerificacionOcadPazSgr", rolIdParameter, entidadIdParameter);
        }
    
        public virtual int uspPostSGR_OCADPaz_GuardarAsignacionUsuarioEncargado(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_OCADPaz_GuardarAsignacionUsuarioEncargado", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<Nullable<int>> uspGetExisteInstanciaCTUSNoFinalizada(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("uspGetExisteInstanciaCTUSNoFinalizada", proyectoIdParameter);
        }
    
        public virtual int uspPostSGR_Viabilidad_GuardarAsignacionUsuarioEncargado(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_Viabilidad_GuardarAsignacionUsuarioEncargado", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Viabilidad_LeerProyectoUsuarioEncargado(Nullable<int> proyectoId, Nullable<System.Guid> instanciaId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Viabilidad_LeerProyectoUsuarioEncargado", proyectoIdParameter, instanciaIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_LeerEntidadesAdscritas(Nullable<int> proyectId, string tipoEntidad)
        {
            var proyectIdParameter = proyectId.HasValue ?
                new ObjectParameter("proyectId", proyectId) :
                new ObjectParameter("proyectId", typeof(int));
    
            var tipoEntidadParameter = tipoEntidad != null ?
                new ObjectParameter("tipoEntidad", tipoEntidad) :
                new ObjectParameter("tipoEntidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_LeerEntidadesAdscritas", proyectIdParameter, tipoEntidadParameter);
        }
    
        public virtual int uspPostSGR_Proyectos_ActualizarEntidadAdscrita(Nullable<int> proyectId, Nullable<int> entityId, string user, Nullable<bool> delegado, ObjectParameter result)
        {
            var proyectIdParameter = proyectId.HasValue ?
                new ObjectParameter("proyectId", proyectId) :
                new ObjectParameter("proyectId", typeof(int));
    
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var delegadoParameter = delegado.HasValue ?
                new ObjectParameter("delegado", delegado) :
                new ObjectParameter("delegado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_Proyectos_ActualizarEntidadAdscrita", proyectIdParameter, entityIdParameter, userParameter, delegadoParameter, result);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_ValidarEntidadDelegada(Nullable<int> proyectId, string tipo)
        {
            var proyectIdParameter = proyectId.HasValue ?
                new ObjectParameter("proyectId", proyectId) :
                new ObjectParameter("proyectId", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_ValidarEntidadDelegada", proyectIdParameter, tipoParameter);
        }
    
        public virtual ObjectResult<string> uspGetValidarInstanciaCTUSNoFinalizada_JSON(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetValidarInstanciaCTUSNoFinalizada_JSON", proyectoIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetDatosAdicionalesCTEI_JSON(Nullable<int> proyectoId, Nullable<System.Guid> instanciaId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetDatosAdicionalesCTEI_JSON", proyectoIdParameter, instanciaIdParameter);
        }
    
        public virtual int uspPostDatosAdicionalesCTEI_JSON(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostDatosAdicionalesCTEI_JSON", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<UspObtenerInformacionNotificacionInvolucrados_Result> UspObtenerInformacionNotificacionInvolucrados(Nullable<System.Guid> instanciaId, string usuarioFirma)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var usuarioFirmaParameter = usuarioFirma != null ?
                new ObjectParameter("UsuarioFirma", usuarioFirma) :
                new ObjectParameter("UsuarioFirma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspObtenerInformacionNotificacionInvolucrados_Result>("UspObtenerInformacionNotificacionInvolucrados", instanciaIdParameter, usuarioFirmaParameter);
        }
    
        public virtual ObjectResult<UspObtenerUsuariosNotificacionViabilidad_Result> UspObtenerUsuariosNotificacionViabilidad(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspObtenerUsuariosNotificacionViabilidad_Result>("UspObtenerUsuariosNotificacionViabilidad", instanciaIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Transversal_LeerListaParametros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Transversal_LeerListaParametros");
        }
    
        public virtual int uspPostRegistrarAvalUso_JSON(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostRegistrarAvalUso_JSON", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetAvalUsoSgr_JSON(Nullable<int> proyectoId, Nullable<System.Guid> instanciaId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetAvalUsoSgr_JSON", proyectoIdParameter, instanciaIdParameter);
        }
    
        public virtual int uspPostSGR_Proyectos_ActualizarEntidadAdscritaCTUS(Nullable<int> proyectId, Nullable<int> entityId, string tipo, string user, ObjectParameter result)
        {
            var proyectIdParameter = proyectId.HasValue ?
                new ObjectParameter("proyectId", proyectId) :
                new ObjectParameter("proyectId", typeof(int));
    
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_Proyectos_ActualizarEntidadAdscritaCTUS", proyectIdParameter, entityIdParameter, tipoParameter, userParameter, result);
        }
    
        public virtual int uspPostSGR_CTUS_GuardarAsignacionUsuarioEncargado(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostSGR_CTUS_GuardarAsignacionUsuarioEncargado", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual int uspPostEliminarFirmaUsuarioViabilidadSgp(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostEliminarFirmaUsuarioViabilidadSgp", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<uspGetSGR_ListaTipoDocumentosSoportePorRol_Result> uspGetSGR_ListaTipoDocumentosSoportePorRol(Nullable<int> tipoTramiteId, string rol, Nullable<System.Guid> nivelId, Nullable<System.Guid> instanciaId, Nullable<System.Guid> accionId, Nullable<int> tramiteId)
        {
            var tipoTramiteIdParameter = tipoTramiteId.HasValue ?
                new ObjectParameter("tipoTramiteId", tipoTramiteId) :
                new ObjectParameter("tipoTramiteId", typeof(int));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("nivelId", nivelId) :
                new ObjectParameter("nivelId", typeof(System.Guid));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("instanciaId", instanciaId) :
                new ObjectParameter("instanciaId", typeof(System.Guid));
    
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("accionId", accionId) :
                new ObjectParameter("accionId", typeof(System.Guid));
    
            var tramiteIdParameter = tramiteId.HasValue ?
                new ObjectParameter("tramiteId", tramiteId) :
                new ObjectParameter("tramiteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_ListaTipoDocumentosSoportePorRol_Result>("uspGetSGR_ListaTipoDocumentosSoportePorRol", tipoTramiteIdParameter, rolParameter, nivelIdParameter, instanciaIdParameter, accionIdParameter, tramiteIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> uspGetCumplimentoFlujoSGR(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("uspGetCumplimentoFlujoSGR", instanciaIdParameter);
        }
    
        public virtual int uspPostAplicarFlujoSgr(string objetoNegocioId, Nullable<System.Guid> instanciaId, string usuario)
        {
            var objetoNegocioIdParameter = objetoNegocioId != null ?
                new ObjectParameter("ObjetoNegocioId", objetoNegocioId) :
                new ObjectParameter("ObjetoNegocioId", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAplicarFlujoSgr", objetoNegocioIdParameter, instanciaIdParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_MostrarEstadosPriorizacion(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_MostrarEstadosPriorizacion", proyectoIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_MostrarEstadosAprobacion(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_MostrarEstadosAprobacion", proyectoIdParameter);
        }
    
        public virtual int uspPostDevolverFlujoSgr(string objetoNegocioId, Nullable<System.Guid> instanciaId, string usuario)
        {
            var objetoNegocioIdParameter = objetoNegocioId != null ?
                new ObjectParameter("ObjetoNegocioId", objetoNegocioId) :
                new ObjectParameter("ObjetoNegocioId", typeof(string));
    
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostDevolverFlujoSgr", objetoNegocioIdParameter, instanciaIdParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<uspGetConfiguracionReportesPorInstancia_Result> uspGetConfiguracionReportesPorInstancia(Nullable<System.Guid> instanciaId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetConfiguracionReportesPorInstancia_Result>("uspGetConfiguracionReportesPorInstancia", instanciaIdParameter);
        }
    
        public virtual ObjectResult<uspGetSGR_Encabezado_LeerEncabezado_Result> uspGetSGR_Encabezado_LeerEncabezado(Nullable<System.Guid> idInstancia, Nullable<System.Guid> idFlujo, Nullable<System.Guid> idNivel, string idProyecto, string tramite)
        {
            var idInstanciaParameter = idInstancia.HasValue ?
                new ObjectParameter("idInstancia", idInstancia) :
                new ObjectParameter("idInstancia", typeof(System.Guid));
    
            var idFlujoParameter = idFlujo.HasValue ?
                new ObjectParameter("idFlujo", idFlujo) :
                new ObjectParameter("idFlujo", typeof(System.Guid));
    
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("idNivel", idNivel) :
                new ObjectParameter("idNivel", typeof(System.Guid));
    
            var idProyectoParameter = idProyecto != null ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(string));
    
            var tramiteParameter = tramite != null ?
                new ObjectParameter("tramite", tramite) :
                new ObjectParameter("tramite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_Encabezado_LeerEncabezado_Result>("uspGetSGR_Encabezado_LeerEncabezado", idInstanciaParameter, idFlujoParameter, idNivelParameter, idProyectoParameter, tramiteParameter);
        }
    
        public virtual ObjectResult<string> uspGetAprobacionCredito(Nullable<System.Guid> instanciaId, Nullable<int> entityTypeCatalogOptionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var entityTypeCatalogOptionIdParameter = entityTypeCatalogOptionId.HasValue ?
                new ObjectParameter("EntityTypeCatalogOptionId", entityTypeCatalogOptionId) :
                new ObjectParameter("EntityTypeCatalogOptionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetAprobacionCredito", instanciaIdParameter, entityTypeCatalogOptionIdParameter);
        }
    
        public virtual int uspPostAprobacionCredito(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostAprobacionCredito", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetResumenEstadoAprobacionCredito(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetResumenEstadoAprobacionCredito", proyectoIdParameter);
        }
    
        public virtual ObjectResult<uspGetSGR_Procesos_ConsultarEjecutorbyTipo_Result> uspGetSGR_Procesos_ConsultarEjecutorbyTipo(Nullable<int> proyectoId, Nullable<int> tipoEjecutorId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(int));
    
            var tipoEjecutorIdParameter = tipoEjecutorId.HasValue ?
                new ObjectParameter("tipoEjecutorId", tipoEjecutorId) :
                new ObjectParameter("tipoEjecutorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSGR_Procesos_ConsultarEjecutorbyTipo_Result>("uspGetSGR_Procesos_ConsultarEjecutorbyTipo", proyectoIdParameter, tipoEjecutorIdParameter);
        }
    
        public virtual ObjectResult<string> uspGetPuntajeProyecto(Nullable<System.Guid> instanciaId, Nullable<int> entityTypeCatalogOptionId)
        {
            var instanciaIdParameter = instanciaId.HasValue ?
                new ObjectParameter("InstanciaId", instanciaId) :
                new ObjectParameter("InstanciaId", typeof(System.Guid));
    
            var entityTypeCatalogOptionIdParameter = entityTypeCatalogOptionId.HasValue ?
                new ObjectParameter("EntityTypeCatalogOptionId", entityTypeCatalogOptionId) :
                new ObjectParameter("EntityTypeCatalogOptionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetPuntajeProyecto", instanciaIdParameter, entityTypeCatalogOptionIdParameter);
        }
    
        public virtual int uspPostPuntajeProyecto(string json, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostPuntajeProyecto", jsonParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetProyectoLeerValorAprobacionSGR(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("proyectoId", proyectoId) :
                new ObjectParameter("proyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetProyectoLeerValorAprobacionSGR", proyectoIdParameter);
        }
    
        public virtual int UspDeleteOperacionesCredito(Nullable<int> proyectoId, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspDeleteOperacionesCredito", proyectoIdParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> uspGetSGR_Proyectos_MostrarEstadosAprobacionCreditoParcial(Nullable<int> proyectoId)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetSGR_Proyectos_MostrarEstadosAprobacionCreditoParcial", proyectoIdParameter);
        }
    }
}
