//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.ServiciosNegocio.Persistencia.ModeloSGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int Id { get; set; }
        public string Parametro { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> SStorage { get; set; }
    }
}
