// <auto-generated />
namespace DNP.Backbone.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pruebaDetalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pruebaDetalle));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181617592_pruebaDetalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
