// <auto-generated />
namespace DNP.Backbone.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajustetamano : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustetamano));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181621036_ajustetamano"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
