//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.Backbone.Comunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackboneRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackboneRecursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNP.Backbone.Comunes.BackboneRecursos", typeof(BackboneRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación no Existe.
        /// </summary>
        public static string AplicacionNoExiste {
            get {
                return ResourceManager.GetString("AplicacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido inválido. No se encontró un objeto para guardar..
        /// </summary>
        public static string ContenidoInvalido {
            get {
                return ResourceManager.GetString("ContenidoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales invalidas.
        /// </summary>
        public static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la información en el formulario. .
        /// </summary>
        public static string ErrorCargaFormulario {
            get {
                return ResourceManager.GetString("ErrorCargaFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en la ejecución del flujo.
        /// </summary>
        public static string ErrorEjecucionFlujo {
            get {
                return ResourceManager.GetString("ErrorEjecucionFlujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar en caché.
        /// </summary>
        public static string ErrorGuardarCache {
            get {
                return ResourceManager.GetString("ErrorGuardarCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error indefinido.
        /// </summary>
        public static string ErrorIndefinido {
            get {
                return ResourceManager.GetString("ErrorIndefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo mapear la consulta.
        /// </summary>
        public static string ErrorMapear {
            get {
                return ResourceManager.GetString("ErrorMapear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan las credenciales.
        /// </summary>
        public static string FaltanCredenciales {
            get {
                return ResourceManager.GetString("FaltanCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardo definitivamente la entidad de tipo {0}.
        /// </summary>
        public static string GuardadoDefinitivo {
            get {
                return ResourceManager.GetString("GuardadoDefinitivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información almacenada correctamente.
        /// </summary>
        public static string GuardadoExitoso {
            get {
                return ResourceManager.GetString("GuardadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado no exitoso.
        /// </summary>
        public static string GuardadoNoExitoso {
            get {
                return ResourceManager.GetString("GuardadoNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardo temporalmente la entidad de tipo {0}.
        /// </summary>
        public static string GuardadoTemporal {
            get {
                return ResourceManager.GetString("GuardadoTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado temporal no exitoso.
        /// </summary>
        public static string GuardadoTemporalNoExitoso {
            get {
                return ResourceManager.GetString("GuardadoTemporalNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al guardar.
        /// </summary>
        public static string MensajeErrorGuardar {
            get {
                return ResourceManager.GetString("MensajeErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de servicio no válido o disponible..
        /// </summary>
        public static string MetodoServicioNoDisponible {
            get {
                return ResourceManager.GetString("MetodoServicioNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} no existe..
        /// </summary>
        public static string ParametroNoExiste {
            get {
                return ResourceManager.GetString("ParametroNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} no recibido..
        /// </summary>
        public static string ParametroNoRecibido {
            get {
                return ResourceManager.GetString("ParametroNoRecibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro {0} inválido.
        /// </summary>
        public static string ParametroNoValido {
            get {
                return ResourceManager.GetString("ParametroNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros no recibidos.
        /// </summary>
        public static string ParametrosNoRecibidos {
            get {
                return ResourceManager.GetString("ParametrosNoRecibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro de entrada inválido.
        /// </summary>
        public static string ParametrosNoValidos {
            get {
                return ResourceManager.GetString("ParametrosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado exitoso.
        /// </summary>
        public static string PostExitoso {
            get {
                return ResourceManager.GetString("PostExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationId debe ser un objeto Guid..
        /// </summary>
        public static string PowerBI_ApplicationIdTienesSerGuid {
            get {
                return ResourceManager.GetString("PowerBI.ApplicationIdTienesSerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de autenticación en Power BI..
        /// </summary>
        public static string PowerBI_ErrorDeAutenticación {
            get {
                return ResourceManager.GetString("PowerBI.ErrorDeAutenticación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún dashboard con el ID proporcionado en el espacio de trabajo. Asegúrese de que sea válido..
        /// </summary>
        public static string PowerBI_NoEncontroDashboardID {
            get {
                return ResourceManager.GetString("PowerBI.NoEncontroDashboardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún reporte con el ID proporcionado en el espacio de trabajo. Asegúrese de que ReportId sea válido..
        /// </summary>
        public static string PowerBI_NoEncontroReporteID {
            get {
                return ResourceManager.GetString("PowerBI.NoEncontroReporteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo generar el embed token..
        /// </summary>
        public static string PowerBI_NoPudoGenerarToken {
            get {
                return ResourceManager.GetString("PowerBI.NoPudoGenerarToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationId está vacío. .
        /// </summary>
        public static string PowerBI_NoTienesApplicationId {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave secreta de la aplicación está vacío.
        /// </summary>
        public static string PowerBI_NoTienesClaveSecreta {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesClaveSecreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron dashboards en el espacio de trabajo..
        /// </summary>
        public static string PowerBI_NoTienesDashboards {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login del Usuário está vacío..
        /// </summary>
        public static string PowerBI_NoTienesLoginUsuarioMaster {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesLoginUsuarioMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron reportes en el espacio de trabajo..
        /// </summary>
        public static string PowerBI_NoTienesReportes {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña del Usuário está vacío..
        /// </summary>
        public static string PowerBI_NoTienesSenaUsuarioMaster {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesSenaUsuarioMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temat de la aplicación está vacío..
        /// </summary>
        public static string PowerBI_NoTienesTenat {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesTenat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ID está vacío.
        /// </summary>
        public static string PowerBI_NoTienesWorkaspaceId {
            get {
                return ResourceManager.GetString("PowerBI.NoTienesWorkaspaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationId debe ser un objeto Guid..
        /// </summary>
        public static string PowerBI_WorkspaceTienesSerGuid {
            get {
                return ResourceManager.GetString("PowerBI.WorkspaceTienesSerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Proyecto no tiene Fuentes de Financiación asociadas.
        /// </summary>
        public static string RespuestaSinResultados {
            get {
                return ResourceManager.GetString("RespuestaSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no tiene una regionalización asociada.
        /// </summary>
        public static string RespuestaSinResultadosRegionalizacion {
            get {
                return ResourceManager.GetString("RespuestaSinResultadosRegionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio no existe.
        /// </summary>
        public static string ServicioNoExiste {
            get {
                return ResourceManager.GetString("ServicioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se obtuvieron resultados.
        /// </summary>
        public static string SinResultados {
            get {
                return ResourceManager.GetString("SinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Autorizado.
        /// </summary>
        public static string UsuarioAutorizado {
            get {
                return ResourceManager.GetString("UsuarioAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no existe..
        /// </summary>
        public static string UsuarioInexistente {
            get {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no Autorizado.
        /// </summary>
        public static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no Autorizado.
        /// </summary>
        public static string UsuarioNoTienePermisos {
            get {
                return ResourceManager.GetString("UsuarioNoTienePermisos", resourceCulture);
            }
        }
    }
}
