
(function () {
    'use strict';
    // ReSharper disable once UndeclaredGlobalVariableUsing
    angular.module('backbone').constant("constantesBackbone", {
        keySTSApplication: 'WebAppBackbone',
        keySTSApplicationMGA: 'STSAPPNameMGA',
        apiIdentidadObtenerUsuarioPorId: 'api/Identidad/obtenerUsuarioPorId?id=',
        apiIdentidadVerificarExistenciaUsuarioSTSAplicacion: 'api/Identidad/verificarExistenciaUsuarioSTSAplicacion?pAplicacion={{aplicacion}}&pTD={{tipoDocumento}}&pNumeroDocumento={{numeroDocumento}}',
        apiIdentidadObtenerAplicacionesExistenciaUsuarioSTS: 'api/Identidad/obtenerAplicacionesExistenciaUsuarioSTS?pAplicacion={{aplicacion}}&pTD={{tipoDocumento}}&pNumeroDocumento={{numeroDocumento}}',
        apiIdentidadObtenerAplicacionesConfiablesExistenciaUsuarioSTS: 'api/Identidad/obtenerAplicacionesConfiablesExistenciaUsuarioSTS?pAplicacion={{aplicacion}}&pTD={{tipoDocumento}}&pNumeroDocumento={{numeroDocumento}}',
        apiIdentidadRegistrarUsuarioAPPSTS: 'api/Identidad/registrarUsuarioAPPSTS',
        apiIdentidadRegistrarUsuarioSTS: 'api/Identidad/registrarUsuarioSTS',
        apiIdentidadEnviarCorreoInvitacionSTS: 'api/Identidad/enviarCorreoInvitacionSTS',
        apiIdentidadValidarContrasenaActualSTS: 'api/Identidad/validarContrasenaActualSTS',
        apiIdentidadCambiarContrasenaSTS: 'api/Identidad/cambiarContrasenaSTS',
        apiAutorizacionObtenerUsuarioPorIdUsuarioDnp: 'api/Autorizacion/ObtenerUsuarioPorIdUsuarioDnp?idUsuarioDnp=',
        apiAutorizacionObtenerUsuarioPorIdUsuario: 'api/Autorizacion/ObtenerUsuarioPorIdUsuario?id=',
        apiAutorizacionObtenerUsuarioPorCorreoDNP: 'api/Autorizacion/ObtenerUsuarioPorCorreoDNP?correo=',
        apiAutorizacionObtenerDatosUsuarioPorNombre: 'api/Autorizacion/ObtenerCuentaUsuario?nomeCuenta=',
        apiAutorizacionObtenerOpcionesConFiltro: 'api/AutorizacionNegocio/ObtenerOpcionesConFiltro',
        apiAutorizacionObtenerListaEntidad: 'api/Autorizacion/ObtenerListaEntidad',
        apiBackboneObtenerUsuarios: 'api/Usuario/ObtenerUsuarios',
        apiBackboneObtenerListadoEntidadesXUsuarioAutenticado: 'api/Entidad/ObtenerListadoEntidadesXUsuarioAutenticado',
        apiBackboneObtenerListadoEntidadesXTipoEntidadYUsuarioAutenticado: 'api/Entidad/ObtenerListadoEntidadesXTipoEntidadYUsuarioAutenticado',
        apiBackboneObtenerListadoPerfilesXEntidadBanco: 'api/Entidad/ObtenerListadoPerfilesXEntidadBanco',
        apiBackboneObtenerListadoPerfilesXEntidad: 'api/Entidad/ObtenerListadoPerfilesXEntidad',
        apiBackboneObtenerListadoPerfilesXEntidadYUsuario: `api/Usuario/ObtenerListadoPerfilesXEntidadYUsuario?idEntidad={{idEntidad}}&idUsuario={{idUsuario}}`,
        apiBackboneObtenerListadoPerfilesXUsuarioTerritorio: `api/Usuario/ObtenerListadoPerfilesXUsuarioTerritorio?idUsuario={{idUsuario}}`,
        apiBackboneObtenerEntidadesInviteUsuarios: 'api/Usuario/ObtenerEntidadesInviteUsuario',
        apiBackboneInvitarUsuario: 'api/Usuario/InvitarUsuario',
        apiBackboneRegistrarUsuarioPIIP: 'api/Usuario/RegistrarUsuarioPIIP',
        apiBackboneRegistrarUsuarioTerritorioPIIP: 'api/Usuario/RegistrarUsuarioTerritorioPIIP',
        apiBackboneCrearUsuarioPerfil: 'api/Usuario/CrearUsuarioPerfil',
        apiBackboneObtenerTodosPerfiles: 'api/Usuario/ObtenerTodosPerfiles',
        apiBackboneObtenerTodasEntidades: 'api/Usuario/ObtenerTodasEntidades',
        apiBackboneObtenerEntidadesConRoleVisualizador: 'api/Entidad/ObtenerEntidadesConRoleVisualizador',
        apiBackboneObtenerPerfilesPorAplicacion: 'api/Usuario/ObtenerPerfilesPorAplicacion',
        apiBackboneObtenerPerfilesAutorizadosPorAplicacion: 'api/Usuario/ObtenerPerfilesAutorizadosPorAplicacion',
        apiBackboneObtenerDatosUsuario: 'api/Usuario/ObtenerDatosVisualizacion?usuarioGuid=',
        apiBackboneObtenerUsuarioPorIdUsuarioDnp: 'api/Usuario/ObtenerUsuarioPorIdUsuarioDnp?usuarioDnp=' + usuarioDNP,
        apiBackboneObtenerPerfiles: 'api/Usuario/ObtenerPerfiles?perfilFiltro=',
        apiBackboneObtenerRolesDePerfil: 'api/Usuario/ObtenerRolesDePerfil',
        apiBackboneGuardarPerfil: 'api/Usuario/GuardarPerfil',
        apiBackboneEditarUsuario: 'api/Usuario/EditarUsuario',
        apiBackboneEditarUsuarioTerritorio: 'api/Usuario/EditarUsuarioTerritorio',
        apiBackboneSetActivoUsuarioPerfilPorEntidad: 'api/Usuario/SetActivoUsuarioPerfilPorEntidad',
        apiBackboneSetActivoUsuarioPerfil: 'api/Usuario/SetActivoUsuarioPerfil',
        apiBackboneSetActivoUsuarioEntidad: 'api/Usuario/SetActivoUsuarioEntidad',
        apiBackboneGuardarRol: 'api/Usuario/GuardarRol',
        apiBackboneEliminarRol: 'api/Usuario/EliminarRol',
        apiBackboneObtenerOpciones: 'api/Usuario/ObtenerOpciones',
        apiBackboneObtenerOpcionesDeRol: 'api/Usuario/ObtenerOpcionesDeRol',
        apiBackboneEliminarPerfil: 'api/Usuario/EliminarPerfil',
        apiBackboneEliminarPerfilUsuario: 'api/Usuario/EliminarUsuarioPerfil',
        apiBackboneObtenerRoles: 'api/Usuario/ObtenerRoles',
        apiBackboneObtenerPerfilesUsuario: 'api/Usuario/ObtenerPerfilesUsuario?usuarioDnp=' + usuarioDNP + '&tipoEntidad=',
        apiBackboneObtenerPerfilesUsuarioXUsuarioAutenticado: `api/Usuario/ObtenerPerfilesUsuarioXUsuarioAutenticado?usuarioDnp=${usuarioDNP}&tipoEntidad={{tipoEntidad}}`,
        apiBackboneObtenerUsuariosPorEntidad: 'api/Usuario/ObtenerUsuariosPorEntidad?tipoEntidad=',
        apiBackboneObtenerUsuariosXEntidad: 'api/Usuario/ObtenerUsuariosXEntidad?tipoEntidad=',
        apiBackboneObtenerUsuariosXEntidadTerritorio: 'api/Usuario/ObtenerUsuariosXEntidadTerritorio?tipoEntidad=',
        apiBackboneObtenerUsuariosPorNombre: 'api/Usuario/ObtenerUsuariosPorNombre?nombre=',
        apiBackboneObtenerUsuarioDominio: 'api/Usuario/ObtenerUsuarioDominio?usuarioDnp=',
        apiBackboneObtenerUsuariosPorNombreIdentificacion: 'api/Autorizacion/ObtenerUsuariosPorNombreIdentificacion',
        apiBackboneObtenerSectoresPorUsuarioEntidad: 'api/Autorizacion/ObtenerSectoresPorUsuarioEntidad',
        apiBackboneGuardarSectoresPorUsuarioEntidad: 'api/Autorizacion/GuardarSectoresPorUsuarioEntidad',
        apiBackboneObtenerProyectosDePerfil: 'api/Usuario/ObtenerProyectosDePerfil',
        apiBackboneObtenerProyectosPorEntidad: 'api/Proyecto/ObtenerProyectosPorEntidad?usuarioDnp=' + usuarioDNP,
        apiBackboneAsociarProyectosAUsuarioPerfil: 'api/Usuario/AsociarProyectosAUsuarioPerfil?usuarioDnp=' + usuarioDNP,
        apiBackboneObtenerExcelPerfiles: 'api/Usuario/ObtenerExcelPerfiles',
        apiBackboneObtenerExcelRoles: 'api/Usuario/ObtenerExcelRoles',
        apiBackboneObtenerProyectos: 'api/Proyectos/ObtenerProyectoPorResponsable?usuarioResponsable=' + usuarioDNP,
        apiBackbonevalidarPermisoInactivarUsuario: 'api/Usuario/validarPermisoInactivarUsuario',


        apiBackboneObtenerProyectoListaLocalizaciones: 'api/Proyecto/ObtenerProyectoListaLocalizaciones',
        apiBackboneGuardarLocalizacion: 'api/Localizacion/GuardarLocalizacion',

        apiBackboneObtenerTramites: 'api/Proyectos/ObtenerTramitesPorResponsable?usuarioResponsable=' + usuarioDNP,
        apiBackboneInsertarAuditoriaProyecto: 'api/ConsolaProyecto/InsertarAuditoria',
        apiBackboneObtenerAuditoriaProyecto: 'api/ConsolaProyecto/ObtenerAuditoriaEntidad',
        apiBackboneActualizarPrioridadTramite: 'api/Proyectos/ActualizarPrioridadTramite',
        apiBackboneObtenerNotificacionesPorResponsable: 'api/Proyectos/ObtenerNotificacionesPorResponsable?usuarioResponsable=' + usuarioDNP,
        apiBackboneActualizarEstadoProyecto: 'api/Proyectos/ActualizarEstadoProyecto',
        apiBackboneObtenerTramite: 'api/Tramite/ObtenerTramites',
        apiBackboneObtenerTramiteProgramacion: 'api/Tramite/ObtenerTramitesProgramacion',
        apiBackboneObtenerInbox: 'api/Inbox/ObtenerInbox',
        apiBackboneObtenerExcelProyectos: 'api/Proyecto/ObtenerExcel',
        apiBackboneObtenerExcelTramites: 'api/Tramite/ObtenerTramitesExcel',
        apiBackboneObtenerExcelTramitesProyectos: 'api/Tramite/ObtenerProyectosExcel',
        apiBackboneExcelConsolaProyectos: 'api/ConsolaProyecto/ExcelConsolaProyectos',
        apiBackboneObtenerProyectosPdfInbox: 'api/Inbox/ObtenerInfoPDF',
        apiBackboneObtenerProyectosPorTramite: 'api/Tramite/ObtenerProyectos',
        apiBackboneProyectosImprimirPDF: 'PDF/ProyectosPDF',
        apiBackboneProyectosConsolaImprimirPDF: 'PDF/ProyectosPDFConsola',
        apiBackboneColsaProyectosPDF: 'PDF/ConsolaProyectosPDF',
        apiBackbonePerfilesImprimirPDF: 'PDF/PerfilesPDF',
        apiBackboneRolesImprimirPDF: 'PDF/RolesPDF',
        apiBackboneTramitesObtenerPdfInbox: 'api/Tramite/ObtenerInfoPDF',
        apiBackboneTramitesImprimirPDF: 'PDF/TramitesPDF',
        apiBackboneTramitesProyectosPdfInbox: 'api/Tramite/ObtenerProyectos',
        apiBackboneTramitesProyectosImprimirPDF: 'PDF/TramitesProyectosPDF',
        apiBackboneInflexibilidadImprimirPDF: 'PDF/InflexibilidadesPDF',
        apiBackboneObtenerInboxListaEntidades: 'api/Inbox/ObtenerListaEntidades',
        apiBackboneObtenerInboxListaSectores: 'api/Inbox/ObtenerListaSectores',
        apiBackboneObtenerInboxListaCriticidad: 'api/Inbox/ObtenerListaCriticidad',
        apiBackboneObtenerInboxListaEstadoProyecto: 'api/Inbox/ObtenerListaEstadoProyecto',
        apiBackboneObtenerProyectosEntidadesPorUsuario: 'api/BackboneMock/ObtenerProyectosEntidadesPorUsuarioRoles?usuarioDnp=',
        apiFlujosCrearInstancia: 'api/Flujo/CrearInstancia',
        apiFlujosCrearTrazaAccionesPorInstancia: 'api/Flujo/CrearTrazaAccionesPorInstancia',
        apiFlujosObtenerTrazaAccionesPorInstancia: 'api/Flujo/ObtenerTrazaInstancia',
        apiFlujosObtenerFlujoPorId: 'api/Flujo/ObtenerFlujoPorId?flujoId=',
        apiFlujosObtenerFlujoInstanciaActivaTarea: 'api/Flujos/ObtenerFlujoInstanciaActivaTarea',
        apiFlujosObtenerFlujoPorInstanciaTarea: 'api/Flujos/ObtenerFlujoPorInstanciaTarea',
        apiFlujosObtenerValidacionVerAccion: 'api/Flujos/ObtenerValidacionVerAccion',
        apiPiipCoreObtenerFormularioPorIdUri: 'api/Formulario/ObtenerFormulariosporId?id=',
        apiAccionesDevolucion: 'api/Flujo/ObtenerDevolucionesPorIdInstanciaYIdAccion?idInstancia=',
        apiInstanciaProyecto: 'api/Flujo/ObtenerInstanciaProyecto?idInstancia=',
        apiDevolverFlujo: 'api/Flujos/DevolverFlujo',
        apiBackboneValidacionDevolucionPaso: 'api/Proyecto/ValidacionDevolucionPaso',
        apiEjecutarFlujo: 'api/Flujos/EjecutarFlujo',
        urlPDFBackbone: urlPDFBackbone,
        eventoInstanciaCreada: 'instancia.creada',
        apiBackboneObtenerProyecto: 'api/Proyecto/ObtenerProyectos',
        apiBackboneObtenerMacroProcesosCantidad: 'api/ConsolaProyecto/ObtenerMacroProcesosCantidad',
        apiBackboneObtenerMacroProcesos: 'api/ConsolaProyecto/ObtenerMacroProcesos',
        apiBackboneObtenerProcesos: 'api/ConsolaProyecto/ObtenerProcesos',
        apiBackboneObtenerProyectoTodos: 'api/Proyecto/ObtenerProyectosTodos',
        apiBackboneObtenerProyectoListaEntidades: 'api/Proyecto/ObtenerListaEntidades',
        apiBackboneObtenerProyectoListaEntidadesTotal: 'api/Proyecto/ObtenerListaEntidadesTotal',
        apiBackboneObtenerProyectoListaTiposRecursos: 'api/Proyecto/ObtenerListaTiposRecursos',
        apiBackboneObtenerListaTiposRecursosxEntidad: 'api/Proyecto/ObtenerListaTiposRecursosxEntidad',
        //Migracion servicio - fuentes de financiación
        apiBackboneObtenerListaTiposRecursosxEntidadSgp: 'api/SGP/Proyecto/ObtenerListaTiposRecursosxEntidadSgp',
        apiBackboneObtenerListaTipoCofinanciador: 'api/Proyecto/ObtenerListaTipoCofinanciador',
        apiBackboneObtenerListaFondos: 'api/Proyecto/ObtenerListaFondo',
        apiBackboneObtenerListaRubros: 'api/Proyecto/ObtenerListaRubro',
        apiBackboneObtenerProyectosBpin: 'api/Proyecto/ObtenerProyectosBpin',
        apiBackboneObtenerListaProyectosFuentes: 'api/TramitesProyectos/ObtenerListaProyectosFuentes',

        apiBackboneObtenerProyectoListaEtapas: 'api/Proyecto/ObtenerListaEtapas',
        apiBackboneObtenerProyectoTipoEntidad: 'api/Proyecto/ObtenerListaTipoEntidad',
        apiBackboneObtenerProyectoListaSectores: 'api/Proyecto/ObtenerListaSectores',
        apiBackboneObtenerProyectoListaSectoresEntity: 'api/Proyecto/ObtenerListaSectoresEntity',
        apiBackboneObtenerProyectoListaCriticidad: 'api/Proyecto/ObtenerListaCriticidad',
        apiBackboneObtenerProyectoListaEstadoProyecto: 'api/Proyecto/ObtenerListaEstadoProyecto',
        apiBackboneObtenerProyectosPdfProyecto: 'api/Proyecto/ObtenerInfoPDF',
        apiBackboneObtenerConsolaMonitoreo: 'api/Monitoreo/ConsolaMonitoreo',
        apiBackboneObtenerProyectosPdfConsolaMonitoreo: 'api/Monitoreo/ObtenerInfoPDF',
        apiBackboneConsolaMonitoreoImprimirPDF: 'PDF/ConsolaMonitoreoProyectosPDF',
        apiBackboneObtenerExcelConsolaMonitoreo: 'api/Monitoreo/ObtenerExcel',
        apiBackboneObtenerMonitoreoReportes: 'api/Monitoreo/ObtenerReportes',
        apiBackboneObtenerMonitoreoDashboards: 'api/Monitoreo/ObtenerDashboard',
        apiBackboneDescargarReportesPowerBI: 'api/Monitoreo/DescargarReportes',
        obtenerReportesPowerBI: 'api/Monitoreo/ObtenerListaReportes',
        apiBackboneobtenerReporteGantt: 'api/Monitoreo/ObtenerReporteGantt',
        apiBackboneobtenerReporteEstructuraActividades: 'api/Monitoreo/ObtenerReporteEstructuraActividades',
        apiBackboneObtenerConsolaAlertas: 'api/Monitoreo/AlertasConfig',
        apiBackboneCrearConsolaAlertas: 'api/Monitoreo/AlertasConfig/Crear',
        apiBackboneActualizarConsolaAlertas: 'api/Monitoreo/AlertasConfig/Actualizar',
        apiBackboneEliminarConsolaAlertas: 'api/Monitoreo/AlertasConfig/Eliminar',
        apiBackboneConsolaAlertasListaTipoAlerta: 'api/Monitoreo/AlertasConfig/ListaTipoAlerta',
        apiBackboneConsolaAlertasListaEstado: 'api/Monitoreo/AlertasConfig/ListaEstado',
        apiBackboneObtenerPdfConsolaAlertas: 'api/Monitoreo/AlertasConfig/ObtenerInfoPDF',
        apiBackboneConsolaAlertasImprimirPDF: 'PDF/ConsolaAlertaConfigPDF',
        apiBackboneConsolaAlertasListaColumnas: 'api/Monitoreo/MapColumnas',
        apiBackboneConsolaCrearActualizarAlertaConfig: 'api/Monitoreo/AlertasConfig/CrearActualizar',
        apiBackboneObtenerExcelConsolaAlertaConfig: 'api/Monitoreo/AlertasConfig/ObtenerExcel',
        apiBackboneObtenerAlertasGeneradas: 'api/Monitoreo/AlertasGeneradas',
        apiBackboneObtenerSituacaoAlertasProyectos: 'api/Monitoreo/ObtenerSituacaoAlertasProyectos',
        apiBackboneConsolaMonitoreoListaFileFormat: 'api/Monitoreo/ObtenerListaFileFormat',
        apiBackboneObtenerEntidadesNegocio: 'api/Entidad/Obtener',
        apiBackboneObtenerEntidadPorTipoEntidad: 'api/Entidad/ObtenerEntidadesPorTipoEntidad?tipoEntidad=',
        apiBackboneObtenerEntidadesPorUnidadesResponsables: 'api/Entidad/ObtenerEntidadesPorUnidadesResponsables',
        apiBackboneObtenerMatrizEntidadDestino: 'api/Proyecto/ObtenerMatrizEntidadDestino',
        apiBackboneActualizarMatrizEntidadDestino: 'api/Proyecto/ActualizarMatrizEntidadDestino',
        apiBackboneObtenerSectoresParaEntidades: 'api/Entidad/ObtenerSectoresParaEntidades',
        apiBackboneObtenerEntidadPorEntidadId: 'api/Entidad/ObtenerEntidadPorEntidadId',
        apiBackboneObtenerSubEntidadesPorEntidadId: 'api/Entidad/ObtenerSubEntidadesPorEntidadId?idEntidad=',
        apiBackboneObtenerCargaDatos: 'api/CargaDatos/ObtenerCargaDatosPorTipoYTipoEntidad?tipoEntidad=',
        apiBackboneObtenerDatosMongoDb: 'api/CargaDatos/ObtenerDatosMongoDb?id=',
        apiBackboneEliminarEntidad: 'api/Entidad/EliminarEntidad/',
        apiBackboneObtenerSectores: 'api/Entidad/ObtenerSectores',
        apiBackboneObtenerDepartamentos: 'api/Entidad/ObtenerDepartamentos',
        apiBackboneObtenerCRType: 'api/Entidad/ObtenerCRType',
        apiBackboneObtenerFase: 'api/Entidad/ObtenerFase',
        apiBackboneObtenerMatrizFlujo: 'api/Entidad/ObtenerMatrizFlujo',
        apiBackboneObtenerExcelEntidades: 'api/Entidad/ObtenerExcelEntidades',
        apiBackboneObtenerPDFEntidades: 'PDF/EntidadesPDF',
        apiBackboneGuardarEntidad: 'api/Entidad/GuardarEntidad',
        apiBackboneActualizarUnidadResponsable: 'api/Entidad/ActualizarUnidadResponsable',
        apiBackboneGuardarFlujo: 'api/Entidad/MantenimientoMatrizFlujo',
        apiBackboneObtenerListaMensajes: 'api/MensajeMantenimiento/ObtenerListaMensajes',
        apiBackboneCrearActualizarMensajeMantenimiento: 'api/MensajeMantenimiento/CrearActualizar',
        apiBackboneEliminarMensajeMantenimiento: 'api/MensajeMantenimiento/Eliminar',
        apiBackboneObtenerConsolaTramite: 'api/ConsolaTramite/ObtenerConsolaTramites',
        apiBackboneConsolaTramitesImprimirPDF: 'PDF/ConsolaTramitesPDF',
        apiBackboneConsolaTramitesObtenerPdf: 'api/ConsolaTramite/ObtenerInfoPDF',
        apiBackboneObtenerExcelConsolaTramites: 'api/ConsolaTramite/ObtenerConsolaTramitesExcel',
        apiBackboneObtenerProyectosPorTramiteConsola: 'api/ConsolaTramite/ObtenerProyectos',
        apiBackboneObtenerExcelProyectosTramitesConsola: 'api/ConsolaTramite/ObtenerProyectosExcel',
        apiBackboneProyectosTramitesPdfConsola: 'api/ConsolaTramite/ObtenerProyectos',
        apiBackboneProyectosTramitesImprimirPDFConsola: 'PDF/ConsolaTramitesProyectosPDF',
        apiBackboneConsolaProyectos: 'api/ConsolaProyecto/ObtenerProyectos',
        apiBackboneConsolaProyectosListaSectores: 'api/ConsolaProyecto/ObtenerListaSectores',
        apiBackboneConsolaProyectosListaEntidades: 'api/ConsolaProyecto/ObtenerListaEntidades',
        apiBackboneConsolaProyectosListaEstadosProyecto: 'api/ConsolaProyecto/ObtenerListaEstadoProyecto',
        apiBackboneConsolaProyectosListaVigenciasProyectos: 'api/ConsolaProyecto/ObtenerVigenciasProyectos',
        apiBackboneObtenerDocumentosAdjuntos: 'api/ConsolaProyecto/ObtenerDocumentosAdjuntos',
        apiBackboneObtenerDocumentoAdjunto: 'api/ConsolaProyecto/ObtenerDocumentoAdjunto',
        apiBackboneObtenerInflexibilidadPorEntidadId: 'api/Inflexibilidad/ObtenerInflexibilidadPorEntidadId',
        apiBackboneGuardarInflexibilidad: 'api/Inflexibilidad/GuardarInflexibilidad',
        apiBackboneGuardarInflexibilidadPagos: 'api/Inflexibilidad/GuardarInflexibilidadPagos',
        apiBackboneEliminarInflexibilidad: 'api/Inflexibilidad/EliminarInflexibilidad/',
        apiBackboneObtenerExcel: 'api/Inflexibilidad/ObtenerExcel/',
        apiBackboneObtenerInflexibilidadPagos: 'api/Inflexibilidad/ObtenerInflexibilidadPagos/',
        apiBackboneAdherenciaObtenerPorEntidadId: 'api/Adherencia/ObtenerAdherenciasPorEntidadId?idEntidad=',
        apiBackboneAdherenciaGuardar: 'api/Adherencia/Guardar',
        apiBackboneAdherenciaEliminar: 'api/Adherencia/Eliminar?idAdherencia=',
        apiBackboneDelegadoObtenerPorEntidadId: 'api/Delegado/ObtenerPorEntidadId?idEntidad=',
        apiBackboneDelegadoGuardar: 'api/Delegado/Guardar',
        apiBackboneDelegadoEliminar: 'api/Delegado/Eliminar?idDelegado=',
        apiPiipCoreObtenerServicioCustomPorIdUri: 'api/Formulario/ObtenerServiciosBotonCustomPorId?id=',
        apiPiipCoreEjecutarProcedimientoUri: 'api/Formulario/EjecutarProcedimiento',
        apiBackboneConsolaProyectosInstancias: 'api/ConsolaProyecto/ObtenerInstanciasProyectos',
        apiBackboneNivelObtener: 'api/Nivel/ObtenerPorIdPadreIdNivelTipo',
        apiBackboneGuardarDatos: 'api/CargarDatos/GuardarDatos',
        apiBackboneEliminarCargaDatos: 'api/CargarDatos/EliminarCargaDatos',
        apiBackboneCambiarClaveUsuario: 'api/Usuario/cambiarClaveUsuario',
        apiBackboneObtenerUsuariosPorEntidadPdf: 'api/Usuario/ObtenerUsuariosPorEntidadPdf?tipoEntidad=',
        apiBackboneUsuariosImprimirPDF: 'PDF/UsuariosPDF',
        apiBackboneObtenerExcelUsuarios: 'api/Usuario/ObtenerUsuariosExcel?tipoEntidad=',

        apiBackboneFlujoTramitePorNivel: 'api/programacion/ObtenerFlujoTramitesPorNivel',
        apiBackboneProgramacionObtenerPorTipoEntidad: 'api/programacion/ObtenerProgramacionesPorTipoEntidad',
        apiBackboneProgramacionObtenerEstadoProcesos: 'api/programacion/ObtenerEstados',
        apiBackboneProgramacionGuardar: 'api/Programacion/GuardarProgramacion',
        apiBackboneProgramacionEliminar: 'api/Programacion/EliminarProgramacion',
        apiBackboneProgramacionExcepcionObtener: 'api/programacion/ObtenerProgramacionExcepciones',
        apiBackboneProgramacionExcepcionGuardar: 'api/Programacion/GuardarExcepcion',
        apiBackboneProgramacionExcepcionEditar: 'api/Programacion/EditarExcepcion',
        apiBackboneProgramacionExcepcionEliminar: 'api/Programacion/EliminarExcepcion',
        apiBackboneProgramacionCrearPeriodo: 'api/Programacion/CrearPeriodo',
        apiBackboneProgramacionIniciarProceso: 'api/Programacion/IniciarProceso',
        apiBackboneObtenerCargaMasivaCreditos: 'api/Programacion/ObtenerCargaMasivaCreditos',
        apiBackboneValidarCargaMasivaCreditos: 'api/Programacion/ValidarCargaMasivaCreditos',
        apiBackboneRegistrarCargaMasivaCreditos: 'api/Programacion/RegistrarCargaMasivaCreditos',

        apiBackboneObtenerCargaMasivaCuotas: 'api/Programacion/ObtenerCargaMasivaCuotas',
        apiBackboneValidarCargaMasivaCuotas: 'api/Programacion/ValidarCargaMasivaCuotas',
        apiBackboneRegistrarCargaMasivaCuotas: 'api/Programacion/RegistrarCargaMasivaCuotas',

        apiBackboneProgramacionConsultarProyectoGenerarPresupuestal: 'api/Programacion/ObtenerProgramacionProyectosSinPresupuestal',
        apiBackboneProgramacionSectores: 'api/Programacion/ObtenerProgramacionSectores',
        apiBackboneProgramacionEntidadesSector: 'api/Programacion/ObtenerProgramacionEntidadesSector',
        apiBackboneProgramacionObtenerCalendarioProgramacion: 'api/Programacion/ObtenerCalendarioProgramacion',
        apiBackboneProgramacionRegistrarProyectosSinPresupuestal: 'api/Programacion/RegistrarProyectosSinPresupuestal',
        apiBackboneProgramacionValidarConsecutivoPresupuestal: 'api/Programacion/ValidarConsecutivoPresupuestal',
        apiBackboneProgramacionRegistrarCalendarioProgramacion: 'api/Programacion/RegistrarCalendarioProgramacion',

        //  apiBackboneGuardarConfiguracionMensaje: 'api/Programacion/GuardarConfiguracionMensaje',

        apiBackboneObtenerProyectoListaEstadoInstancia: 'api/Proyecto/ObtenerListaEstadoInstancia',
        apiBackboneActivarInstancia: 'api/Proyecto/ActivarInstancia',
        apiBackbonePausarInstancia: 'api/Proyecto/PausarInstancia',
        apiBackboneDetenerInstancia: 'api/Proyecto/DetenerInstancia',
        apiBackboneCancelarInstanciaMisProcesos: 'api/Proyecto/CancelarInstanciaMisProcesos',
        apiBackboneGenerarInstancias: 'api/Flujos/GenerarInstancias',
        apiBackboneEliminarProyectoTramite: 'api/Tramite/EliminarProyectoTramite',
        apiBackboneObtenerContraCreditos: 'api/Proyecto/ObtenerContracredito',
        apiBackboneObtenerCredito: 'api/Proyecto/ObtenerCredito',
        apiBackboneGuardarProyectos: 'api/Proyecto/GuardarProyectos',
        apiBackboneGenerarInstanciasMasiva: 'api/Flujos/GenerarInstanciasMasivo',


        apiBackboneObtenerListaTemas: 'api/CentroAyuda/ObtenerListaTemas',
        apiBackboneCrearActualizarAyudaTema: 'api/CentroAyuda/CrearActualizarTema',
        apiBackboneEliminarAyudaTema: 'api/CentroAyuda/EliminarTema/',
        apiBackboneObtenerPdfTemarioAyuda: 'PDF/TemarioCentroAyuda',
        apiBackboneObtenerPdfVideosAyuda: 'PDF/VideosCentroAyuda',

        apiBackboneObtenerExcelLogInstancia: 'api/Flujos/ObtenerExcelLogInstancia',
        apiBackbonePDFInstanciasLog: 'PDF/InstanciasLogPDF',
        apiBackboneCrearLogFlujo: 'api/Flujos/CrearLogFlujo',
        apiBackboneObtenerFlujosLogInstancia: 'api/Flujos/ObtenerFlujosLogInstancia',
        apiBackboneObtenerHistoricoObservaciones: 'api/Flujos/ObtenerHistoricoObservaciones',
        apiBackboneObtenerListaNotificaciones: 'api/UsuarioNotificacion/ObtenerListaConfig',
        apiBackboneObtenerPdfMensajeMantenimiento: 'PDF/NotificacionesMantenimiento',
        apiBackboneObtenerExcelListaNotificacion: 'api/mensajesnotificacion/obtenerexcel',
        apiBackboneObtenerInstanciasPermiso: 'api/Flujos/ObtenerInstanciasPermiso',
        apiBackboneValidarFlujoConInstanciaActiva: 'api/Flujos/ValidarFlujoConInstanciaActiva',
        apiBackboneObtenerInstanciasActivasProyectos: 'api/Flujos/ObtenerInstanciasActivasProyectos',
        apiBackboneConsultarAccionPorInstancia: 'api/Flujos/ConsultarAccionPorInstancia',
        apiBackboneObtenerAmpliarDevolucionTramite: 'api/Tramites/ObtenerAmpliarDevolucionTramite',
        apiBackboneObtenerMensajeNotificacion: 'api/mensajesnotificacion/obtener',
        apiBackboneObtenerProcedimentosAlmacenados: 'api/UsuarioNotificacion/ObtenerProcedimentosAlmacenados',
        apiBackboneObtenerUsuariosPorProcedimentosId: 'api/UsuarioNotificacion/ObtenerUsuariosPorProcedimentoAlmacenado',
        apiBackboneGuardarConfigNotificaciones: 'api/UsuarioNotificacion/CrearActualizar',
        apiBackboneObtenerExcelNotificaciones: 'api/UsuarioNotificacion/ObtenerExcelNotificaciones',
        apiBackboneEliminarNotificacion: 'api/UsuarioNotificacion/Eliminar',
        apiBackboneMarcarNotificacionComoLeida: 'api/UsuarioNotificacion/MarcarNotificacionComoLeida',
        apiBackbonePDFNotificacionesMensajes: 'PDF/NotificacionesMensajesPDF',
        apiBackboneActualizarIdArchivoInflexibilidadPago: 'api/Inflexibilidad/ActualizarIdArchivoInflexibilidadPagos',
        apiBackboneObtenerConsolaTramiteDocumentos: 'api/ConsolaTramite/ObtenerDocumentos',
        apiBackboneObtenerConsolaTramiteDocumento: 'api/ConsolaTramite/ObtenerDocumento',
        apiBackboneObtenerTiposMotivoAnulacion: 'api/Trasversal/ObtenerTiposMotivoAnulacion',
        apiBackboneCrearAlcance: 'api/Trasversal/CrearAlcanceTramite',
        apiManejadorArchivosObtenerArchivo: 'ArchivoInfo/',
        apiManejadorArchivosGuardarArchivo: 'ArchivoInfo',
        apiBackboneCambiarEstadoDataArchivo: 'api/manejadorArchivos/CambiarEstadoDataArchivo/',
        apiBackboneCargarArchivo: 'api/manejadorArchivos/CargarArchivos/',
        apiBackboneObtenerArchivoInfo: 'api/manejadorArchivos/ObtenerArchivoInfo/',
        apiBackboneObtenerListadoArchivos: 'api/manejadorArchivos/ObtenerListadoArchivos/',
        apiBackboneGuardarArchivoRepositorio: 'api/manejadorArchivos/GuardarArchivoRepositorio',
        apiBackboneObtenerArchivoBytes: 'api/manejadorArchivos/ObtenerArchivoBytes/',
        apiBackboneEliminarArchivo: 'api/manejadorArchivos/EliminarArchivo/',
        apiBackboneActualizarArchivo: 'api/manejadorArchivos/ActualizarArchivo/',
        apiBackboneGetAuthorizationApiArchivos: 'api/manejadorArchivos/GetAuthorizationApiArchivos',
        apiBackboneValidarArchivosSgr: 'api/manejadorArchivos/ValidarArchivosSgr/',

        apiBackboneObtenerProyectoConsolaProcesos: 'api/Proyecto/ObtenerProyectosConsolaProcesos',
        apiBackboneDesagregarRegionalizacion: 'api/Proyecto/ObtenerDesagregarRegionalizacion',
        apiBackboneDesagregarRegionalizacionActualizar: 'api/Proyecto/ActualizarDesagregarRegionalizacion',
        apiBackboneAjustesJustificaionRegionalizacion: 'api/Proyecto/ObtenerDetalleAjustesJustificaionRegionalizacion',
        apiBackboneObtenerInstanciaProyectoTramite: 'api/ObtenerInstanciaProyectoTramite',
        apiFlujosObtenerPermisosAccionPaso: 'api/Seguridad/PermisosAccionPaso',

        idEtapaFormulacion: '65A5AA6A-9592-4FED-B59E-04540A345604',
        idEtapaProgramacion: '4053A9F4-6ABE-4526-B674-3564DFBD6FE1',
        idEtapaGestionRecursos: '050B63FB-83DB-4160-B358-4A4061B79B15',
        //Inicio hijos Recursos Fuente
        idEtapaSolicitudRecursos: '88EA329D-F240-4868-9DF7-86C74FB2ECFA',
        idEtapaRevisionRequisitos: '2F929A45-23D6-4A64-8F93-70111D1AC65B',
        idEtapaAprobacion: '28B7E007-5E01-4DAC-849F-1E2E405D646B',
        idEtapaAjustesGR: '4AB13351-E33C-4461-888B-6B47D2E4DC8D',
        //Fin hijos Recursos Fuente
        idEtapaPlaneacion: 'F73990EF-04B5-4123-B87F-38DA445B6888',
        //Inicio hijos Planeacion
        idEtapaViabilidadRegistro: 'D8C0C353-3EA7-4BC5-9CA6-CC8AA0F7BB8B',
        idEtapaAjustes: 'F0CB8742-E7FC-4076-857C-8B5690DB1B33',
        idEtapaPriorizacion: '5FF73F67-ACBA-4859-9C3F-C2643DDF700F',
        //Fin hijos Planeacion
        idEtapaEjecucion: '02519F26-CDBE-4E02-96D8-8F88B2C3CE6E',
        idEtapaNuevaEjecucion: 'B1FCF5EA-8884-476F-8F32-8F32E18DE329',
        //Inicio hijos Ejecución
        idEtapaProgramacionEjecucion: '588781D2-E70A-492B-8D25-6F027FDE2E79',
        idEtapaAjustesEjecucion: '87BE6962-55B8-4F66-BF7B-3E78EA7E4E56',
        idEtapaTramitesEjecucion: '74A0F290-6760-4155-B06B-59A3D0E92DE5',
        idEtapaSeguimientoControl: '7A8DFF82-9EEA-4181-B1A2-549AD69645C5',

        //Fin hijos Ejecución
        idEtapaViabilidad: 'F92A4087-7A92-45F5-A8BA-28F1C23BD849',
        idEtapaEvaluacion: 'AB45E9AD-D8B7-4045-949C-C415272D03D2',
        //Inicio hijos Evaluacion
        idEtapaCortoPlazo: '5459A89D-BC80-4392-BC54-5F374DD61CE5',
        idEtapaMedianoPlazo: 'A76A52D1-8A84-4912-A440-1F00A6B6E982',
        idEtapaLargoPlazo: '502D7EB5-50B4-48D7-9C4B-B7A50F7A3FDA',
        //Fin hijos Evaluacion
        //RolesPreguntas
        idRControlFormulacionTecnico: '48807AF9-57ED-4951-B009-094AC56F7FBA',
        idRControlFormulacion: '54164BAA-0BC5-4BF6-B7AC-B85262732243',
        idRControlViabilidadTecnico: 'DFC851A6-ECC0-4E84-8246-25839E271A37',
        idRControlViabilidad: '96668EFE-FD90-4804-9FF3-C5FFB673A3D7',
        idRControlPosteriorViabilidadTecnico: 'D5EB24B7-7138-4ED0-A786-8DF1B137A53E',
        idRControlPosteriorViabilidad: '0EB96A9D-BF38-4688-A2A8-5541EC54CE3C',
        nombreFichaPreguntas: 'rpt-ficha-CuestionariosPreguntas',
        idRControlPosteriorDireccionesTecnicas: '35063490-3D6B-4C68-8498-7FF8A9C25096',
        idPrimerNivelFlujoPreguntas: '67c107aa-5f59-407a-b430-407959e38b52',
        nameRControlPosteriorViabilidad: 'R_Concepto Técnico',//'R_Control Posterior de Viabilidad',
        idRSubdirectorEntidad: '921306BB-65A0-481A-8EF2-F178F21D957A',
        idRControlValidadorPoliticaTransversal: 'FDC96CBC-DA2E-4FEE-AD88-B7B24B7A6308',
        // rol presupuesto
        idRPresupuesto: 'DA595AA3-CF59-46D3-A22A-0D96DA5C7371',
        // rol presupuesto Paso2
        idRolPresupuesto: '4FF68A0A-DC57-4252-92DB-C41AE7059E3B',
        // rol priorización
        idRPriorizacion: '356ABCFD-C69E-44F9-AF8F-441DFCD07D0D',
        //Rol Cabeza de sector
        idRCabezaSector: 'C095FDA7-2781-4274-BEC1-FCC4E941C3D8',
        //Rol Formulador
        idRFormulador: 'B9B7E381-CE0D-4B67-A81E-D78515415FC2',
        //Rol R_Gerente de proyecto
        idRGerenteProyectos: '90f33b44-d442-4b0d-86ad-21f055fe561f',

        //Inicio acciones tramite
        idAccionSeleccionProyectosTamites: '2eff3a46-e785-d93c-93f4-7737d8462bac',

        //Fin accciones tramite
        apiBackboneObtenerExcelProyectosConsolaProcesos: 'api/Proyecto/ObtenerExcelConsolaProcesos',
        apiBackboneObtenerProyectosPdfProyectoConsolaProcesos: 'api/Proyecto/ObtenerInfoPDFConsolaProcesos',

        apiBackboneObtenerTramiteConsolaProcesos: 'api/Tramite/ObtenerTramitesConsolaProcesos',
        apiBackboneObtenerTiposTramite: 'api/Tramite/ObtenerTiposTramite',
        apiBackboneObtenerExcelTramitesConsolaProcesos: 'api/Tramite/ObtenerTramitesExcelConsolaProcesos',
        apiBackboneTramitesObtenerPdfInboxConsolaProcesos: 'api/Tramite/ObtenerInfoPDFConsolaProcesos',

        apiBackboneObtenerIdAplicacionPorBpin: 'api/ConsolaProyecto/ObtenerIdAplicacionPorBpin',
        apiBackboneObtenerIdAplicacionPorInstancia: 'api/ConsolaProyecto/ObtenerIdAplicacionPorInstancia',
        apiBackboneObtenerObservacionesPasoPadre: 'api/Flujos/ObtenerObservacionesPasoPadre',
        apiFichaProyectoFichaFisico: 'api/FichaFisico',
        apiFichaProyectoFichaFisicoSGR: 'api/FichaFisicoSGR',
        apiFichaProyectoObtenerPlantillaPorNombre: 'api/Reporte/ObtenerPlantilla/',

        apiObtenerTokenMGA: 'api/Proyecto/ObtenerTokenMGA',
        apiBackboneObtenerProyectosTramiteNegocio: 'api/Tramites/ObtenerProyectosTramiteNegocio?TramiteId=',
        apiBackboneObtenerTipoDocumentoTramite: 'api/Tramites/ObtenerTipoDocumentoTramite',
        apiBackboneGuardarProyectosTramiteNegocio: 'api/Tramites/GuardarProyectosTramiteNegocio',
        apiBackboneEliminarProyectoTramiteNegocio: 'api/Tramites/EliminarProyectoTramiteNegocio',
        apiBackboneObtenerFuentesInformacionPresupuestal: 'api/Tramites/ObtenerFuentesInformacionPresupuestal',
        apiBackboneObtenerProyectoFuentePresupuestalPorTramite: 'api/Tramites/ObtenerProyectoFuentePresupuestalPorTramite',
        apiBackboneObtenerProyectoRequisitosPorTramite: 'api/Tramites/ObtenerProyectoRequisitosPorTramite',
        apiBackboneObtenerCodigoPresupuestal: 'api/Tramites/ObtenerCodigoPresupuestal',
        apiBackboneActualizarCodigoPresupuestal: 'api/Tramites/ActualizarCodigoPresupuestal',
        apiBackboneObtenerTipoDocumentoTramiteNivel: 'api/Tramites/ObtenerTipoDocumentoTramitePorNivel',
        apiBackboneConsultarSystemConfiguracion: 'api/Tramites/ConsultarSystemConfiguracion',

        apiBackboneObtenerPreguntasJustificacion: 'api/Tramites/ObtenerPreguntasJustificacion',
        apiBackboneGuardarRespuestasJustificacion: 'api/Tramite/GuardarRespuestasJustificacion',
        apiBackboneActualizarInstanciaProyecto: 'api/Tramite/ActualizarInstanciaProyecto',
        apiBackboneActualizarValoresProyecto: 'api/Tramite/ActualizarValoresProyecto',
        apiBackboneValidarEnviarDatosTramiteNegocio: 'api/Tramites/ValidarEnviarDatosTramiteNegocio?TramiteId=',
        apiBackboneObtenerPreguntasProyectoActualizacion: 'api/Tramites/ObtenerPreguntasProyectoActualizacion',
        apiBackboneObtenerProyectosTramiteNegocioAprobacion: 'api/Tramites/ObtenerProyectosTramiteNegocioAprobacion',
        apiBackboneActualizarTramitesFuentesPresupuestales: 'api/Tramites/GuardarTramiteInformacionPresupuestal',
        apiBackboneActualizarTramitesRequisitos: 'api/Tramites/GuardarTramiteTipoRequisito',
        apiBackboneObtenerTiposRequisito: 'api/Tramite/ObtenerTiposRequisito',
        apiBackboneObtenerFuentesTramiteProyectoAprobacion: 'api/Tramites/ObtenerFuentesTramiteProyectoAprobacion',
        apiBackboneGuardarFuentesTramiteProyectoAprobacion: 'api/Tramite/GuardarFuentesTramiteProyectoAprobacion',

        apiBackboneObtenerPreguntasPersonalizadas: 'api/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadas',
        apiBackboneObtenerPreguntasPersonalizadasComponente: 'api/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadasComponente',
        apiBackboneObtenerPreguntasPersonalizadasComponenteSGR: 'api/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadasComponenteSGR',
        apiBackboneObtenerDatosGeneralesProyecto: 'api/PreguntasPersonalizadas/ObtenerDatosGeneralesProyecto',
        apiBackboneObtenerConfiguracionEntidades: 'api/PreguntasPersonalizadas/ObtenerConfiguracionEntidades',
        apiBackboneObtenerDireccionTecnica: 'api/Proyecto/ObtenerListaDireccionTecnica',
        apiBackboneObtenerSubDireccionTecnica: 'api/Proyecto/ObtenerListaSubDireccionTecnica',
        apiBackboneObtenerAnalistasSubDireccionTecnica: 'api/Proyecto/ObtenerListaAnalistasSubDireccionTecnica',
        apiBackboneSolicitarConcepto: 'api/Proyecto/SolicitarConcepto',
        apiBackboneObtenerSolicitarConcepto: 'api/Proyecto/ObtenerSolicitarConcepto',
        apiBackboneGuardarPreguntasPersonalizadas: 'api/PreguntasPersonalizadas/GuardarPreguntasPersonalizadas',
        apiBackboneGuardarPreguntasPersonalizadasCustomSGR: 'api/PreguntasPersonalizadas/GuardarPreguntasPersonalizadasCustomSGR',
        apiBackboneObtenerValoresProyectos: 'api/Tramites/ObtenerValoresProyectos',
        apiBackboneEliminarInstanciaProyectoTramite: 'api/Flujos/EliminarInstanciaProyectoTramite',
        apiBackboneEliminarInstanciaCerrada_AbiertaProyectoTramite: 'api/Flujos/EliminarInstanciaCerrada_AbiertaProyectoTramite',
        apiBackboneNotificarUsuariosPorInstanciaPadre: 'api/Flujos/NotificarUsuariosPorInstanciaPadre',
        apiBackboneObtenerTarmitesInstanciaEstadoCerrado: 'api/Flujos/ObtenerTramitesInstanciasEstadoCerrado',
        apiBackboneDevolverProyecto: 'api/proyecto/DevolverProyecto',
        apiBackboneObtenerConceptoDireccionTecnicaTramite: 'api/Tramites/ObtenerConceptoDireccionTecnicaTramite',
        apiBackboneGuardarConceptoDireccionTecnicaTramite: 'api/Tramites/GuardarConceptoDireccionTecnicaTramite',
        idfaseControlPosteriorTramites: 'E8FC3694-C566-4944-A487-DAA494EB3581',
        apiBackBoneFlujoRegistrarPermisosAccionPorUsuario: 'api/Flujos/RegistrarPermisosAccionPorUsuario',
        apiBackboneDevolverCuestionarioProyecto: 'api/PreguntasPersonalizadas/DevolverCuestionarioProyecto',
        apiBackboneValidarEnviarDatosTramiteNegocioAprobacion: 'api/Tramites/ValidarEnviarDatosTramiteNegocioAprobacion?TramiteId=',
        apiBackboneObtenerListaDirecciones: 'api/Tramites/ObtenerListaDirecciones',
        apiBackboneObtenerListaSubdirecciones: 'api/Tramites/ObtenerListaSubdirecciones',
        apiBackboneObtenerDatosProyectoConceptoPorInstancia: 'api/Tramites/ObtenerDatosProyectoConceptoPorInstancia',
        apiBackboneObtenerConceptosPreviosEmitidos: 'api/PreguntasPersonalizadas/ObtenerConceptosPreviosEmitidos',
        //fuentes Financiacion
        apiBackboneFuenteFinanciacionConsultar: 'api/FuenteFinanciacionObtener',
        apiBackboneFuenteFinanciacionVigenciaConsultar: 'api/ObtenerFuenteFinanciacionVigencia',
        apiBackboneFuenteFinanciacionAgregar: 'api/FuenteFinanciacionAgregar',
        apiBackboneFuenteFinanciacionEliminar: 'api/FuenteFinanciacionEliminar',
        apiBackboneDatosAdicionalesConsultar: 'api/DatosAdicionalesObtener',
        apiBackboneDatosAdicionalesAgregar: 'api/DatosAdicionalesAgregar',
        apiBackboneDatosAdicionalesEliminar: 'api/DatosAdicionalesEliminar',
        apiBackboneResumenCostosVsSolicitado: 'api/CostosVsSolicitado/Consultar',
        apiBackboneResumenFuenteFinanciacion: 'api/ResumenFuenteFinanciacion',
        apiBackboneCostosPIIPvsFuentesPIIP: 'api/ConsultarCostosPIIPvsFuentesPIIP',
        apiBackboneFuentesProgramarSolicitado: 'api/ConsultarFuentesProgramarSolicitado',
        apiBackboneGuardarFuentesProgramarSolicitado: 'api/GuardarFuentesProgramarSolicitado',
        apiBackBoneCapitulosModificadosCapitoSeccion: 'api/SeccionesCapitulos/ObtenerCapitulosModificadosCapitoSeccion',
        apiBackboneguardarFuentesFinanciacionRecursosAjustes: 'api/guardarFuentesFinanciacionRecursosAjustes',
        apiBackBoneobtenerDetalleAjustesFuenteFinanciacion: 'api/SeccionesCapitulos/ObtenerDetalleAjustesFuenteFinanciacion',
        apiBackBoneObtenerSeccionCapitulo: 'api/SeccionesCapitulos/ObtenerSeccionCapitulo',
        apiBackBoneObtenerPreguntasAprobacionRol: 'api/FuenteObtenerPreguntasAprobacionRol',
        apiBackBoneGuardarPreguntasAprobacionRol: 'api/FuenteGuardarPreguntasAprobacionRol',

        apiBackBoneObtenerPreguntasAprobacionJefe: 'api/FuenteObtenerPreguntasAprobacionJefe',
        apiBackBoneGuardarPreguntasAprobacionJefe: 'api/FuenteGuardarPreguntasAprobacionJefe',

        //focalizacion
        apiBackbonePoliticasTransversalesAConsultar: 'api/ObtenerPoliticasTransversalesAjustes',
        apiBackbonePoliticasTransversalesAgregar: 'api/AgregarPoliticasTransversalesAjustes',
        apiBackbonePoliticasTransversalesCategorias: 'api/ObtenerPoliticasTransversalesCategorias',
        apiBackbonePoliticasCategoriaPorPadre: 'api/PoliticasCategoriaPorPadre',
        apiBackboneObtenerCategoriasSubcategorias: 'api/ObtenerCategoriasSubcategorias',
        apiBackboneguardarFocalizacionCategoriasPolitica: 'api/GuardarFocalizacionCategoriasPolitica',
        apiBackboneObtenerPoliticasTransversalesResumen: 'api/ObtenerPoliticasTransversalesResumen',
        apiBackbonePoliticasTransversalesResumen: 'api/ObtenerPoliticasTransversalesResumen',
        apiBackboneObtenerPoliticasCategoriasIndicadores: 'api/Focalizacion/ConsultarPoliticasCategoriasIndicadores',
        apiBackboneModificarPoliticasCategoriasIndicadores: 'api/Focalizacion/ModificarCategoriasIndicadores',
        apiBackboneObtenerCrucePoliticasAjustes: 'api/ObtenerCrucePoliticasAjustes',
        apiBackboneGuardarCrucePoliticasAjustes: 'api/GuardarCrucePoliticasAjustes',
        apiBackboneObtenerPoliticasSolicitudConcepto: 'api/ObtenerPoliticasSolicitudConcepto',
        apiBackboneFocalizacionSolicitarConceptoDT: 'api/FocalizacionSolicitarConceptoDT',
        apiBackboneObtenerUsuariosRValidadorPoliticaTransversal: 'api/Proyecto/ObtenerUsuariosRValidadorPoliticaTransversal',
        apiBackboneObtenerDireccionesTecnicasPoliticasFocalizacion: 'api/ObtenerDireccionesTecnicasPoliticasFocalizacion',
        apiBackboneNotificarUsuariosRValidadorPoliticaTransversal: 'api/Notificaciones/NotificarUsuarios',
        apiBackboneObtenerResumenSolicitudConcepto: 'api/ObtenerResumenSolicitudConcepto',
        apiBackboneObtenerPreguntasEnvioPoliticaSubDireccion: 'api/ObtenerPreguntasEnvioPoliticaSubDireccion',
        apiBackboneGuardarPreguntasEnvioPoliticaSubDireccionAjustes: 'api/GuardarPreguntasEnvioPoliticaSubDireccionAjustes',
        apiBackboneGuardarRespuestaEnvioPoliticaSubDireccionAjustes: 'api/GuardarRespuestaEnvioPoliticaSubDireccionAjustes',

        //pasos tramite
        idNivelSeleccionProyectos: '38D70687-ACCE-4329-9D42-366F267DCE42',
        idNivelAprobacionEntidad: '23E787B6-5F9A-4B0B-9CE7-8AC08EE9E7C9',
        idNivelElaboracionConcepto: '4212CE81-4752-4BFD-8EEB-0110EA97348F',
        idNivelRevisionConcepto: '748A4364-6C33-45F4-96D1-D3CDBFBB4CC3',
        idNivelAprobacionTramite: '99688282-BAD0-433E-861D-B8B7473D16F4',
        //nivel de viabilidad
        idNivelViabilidadDefinitiva: '8546906b-66a0-4578-a17c-686baaf00caa',
        idNivelViabilidadSectorialPreliminar: '6079312F-AAB5-48A8-B781-27DD538D046D',
        idNivelJustificaciónAJustesTramite: '88CC8978-EC97-47AA-8F6F-C16D1A62C36E',
        idNivelJustificaciónAJustesProyecto: '87BE6962-55B8-4F66-BF7B-3E78EA7E4E56',
        //nivel de programacion
        idNivelAprobacionProgramacion: 'B7F61818-54BF-4064-89DE-6EFC292BCCBA',
        idNivelAprobacionSupervisorProgramacion: 'DCB5D8EB-8178-4276-97CF-65A9884AC5FB',

        //Nivel ejecucuion -Segumiento
        idNivelPlanearlaEjecucion: '27A5BCF7-A896-4168-86EA-AACA288BCDFA',
        //nivel de Modificación de ley
        idNivelAprobacionEntidadAdicion: 'B7F61818-54BF-4064-89DE-6EFC292BCCBA',
        idNivelReporteAvance: 'AFB17793-0210-4331-A93D-6E1F5FDABAEB',
        idNivelCerrarSeguimiento: 'DB3C22B4-DB06-402B-A03F-4C92EA4A71B2',
        apiBackboneTramiteObtenerProyectoConpes: "api/Tramites/ObtenerProyectoConpes",
        apiBackboneTramiteAdicionarProyectoConpes: "api/Tramites/AdicionarProyectoConpes",
        idRAnalistaDIFP: "0C0CCA1B-8FBA-4371-8BF6-4EE2FE6AFBAF",
        apiBackboneTramiteCargarProyectoConpes: "api/Tramites/CargarProyectoConpes",
        apiBackboneTramiteEliminarProyectoConpes: "api/Tramites/EliminarProyectoConpes",
        idRValidadorPoliticaTransversal: "FDC96CBC-DA2E-4FEE-AD88-B7B24B7A6308",

        // carta tramite
        apiBackBoneObtenerPlantillaCarta: 'api/Tramites/ObtenerPlantillaCarta',
        apiBackBoneObtenerDatosCartaPorSeccion: 'api/Tramites/ObtenerDatosCartaPorSeccion',
        apiBackBoneVerificaUsuarioDestinatario: 'api/Tramites/VerificaUsuarioDestinatario',
        apiBackBoneActualizarCartaDatosIniciales: 'api/Tramites/ActualizarCartaDatosIniciales',
        apiBackBoneObtenerUsuariosRegistrados: 'api/Tramites/ObtenerUsuariosRegistrados',
        apiBackBoneCargarFirma: 'api/Tramites/CargarFirma',
        apiBackBoneValidarSiExisteFirmaUsuario: 'api/Tramites/validarSiExisteFirmaUsuario',
        apiBackBoneBorrarFirma: 'api/Tramites/BorrarFirma',
        apiBackBoneFirmar: 'api/Tramites/Firmar',
        apiBackBoneTramitesFirmar: 'api/Flujos/Firmar',
        apiBackBoneNombrePDFCarta: '26426-iniciales',
        apiBackBoneNombrePDFCartaVf: '28356-tramite-preliminar',
        apiBackBoneNombrePDFCartaAL: '31540_Aclaracion_Leyenda',
        apiBackBoneNombrePDFCartaVFExcep: '28356-tramite-preliminar - VFExcep',
        apiBackBoneNombrePDFCartaIncorporacion: '12232022-incorporacion',
        apiBackBoneNombrePDFCartaAdicionDonacion: '732023-adicion-donacion',
        apiBackBoneObtenerCuerpoConceptoCDP: 'api/Tramites/ObtenerCuerpoConceptoCDP',
        apiBackBoneObtenerCuerpoConceptoAutorizacion: 'api/Tramites/ObtenerCuerpoConceptoAutorizacion',
        apiBackBoneObtenerCartaConceptoDatosDespedida: 'api/Tramites/ObtenerCartaConceptoDatosDespedida',
        apiBackBoneActualizarCartaConceptoDatosDespedida: 'api/Tramites/ActualizarCartaConceptoDatosDespedida',
        apiBackBoneObtenerProyectosCartaTramite: 'api/Tramites/ObtenerProyectosCartaTramite',
        apiBackBoneObtenerDetalleCartaAL: 'api/Tramites/ObtenerDetalleCartaAL',
        apiBackBoneNombrePDFCartaReprogramacionVF: '28323-reprogVF',
        apiBackboneActualizarEstadoAjusteProyecto: 'api/Tramites/ActualizarEstadoAjusteProyecto',

        apiBackBoneConsultarCarta: 'api/Tramites/ConsultarCarta',
        apiBackBoneConsultarCartaConcepto: 'api/TramitesProyectos/ConsultarCartaConcepto',
        // Seguimiento y control
        uriObtenerListadoObjProdNiveles: 'api/seguimientoControl/DesagregarEdt/ObtenerListadoObjProdNiveles',
        uriObtenerListadoObjProdNivelesReporte: 'api/seguimientoControl/ProgramarActividades/ObtenerListadoObjProdNivelesXReporte',
        uriObtenerIndicadores: 'api/SeguimientoControl/FocalizacionIndicadores/ObtenerIndicadoresPoliticas',
        uriActividadProgramacionSeguimientoPeriodosValores: 'api/seguimientoControl/ProgramarActividades/ActividadProgramacionSeguimientoPeriodosValores',
        uriActividadReporteSeguimientoPeriodosValores: 'api/seguimientoControl/ProgramarActividades/ActividadReporteSeguimientoPeriodosValores',
        uriIndicadorPoliticaSeguimientoPeriodosValores: 'api/seguimientoControl/ProgramarIndicadorPolitica/IndicadorPoliticaSeguimientoPeriodosValores',
        uriObtenerListadoObjProdNivelesProgramar: 'api/seguimientoControl/ProgramarActividades/ObtenerListadoObjProdNiveles',
        uriObtenerCalendarioPeriodo: 'api/SeguimientoControl/ProgramarActividades/ObtenerCalendarioPeriodo',
        uriObtenerListadoObjProdNivelesProgramarProducto: 'api/seguimientoControl/ProgramarProductos/ObtenerListadoObjProdNiveles',
        uriObtenerUnidadesMedida: 'api/gestionSeguimiento/UnidadesMedida',
        uriRegistrarNivelesNuevos: 'api/seguimientoControl/DesagregarEdt/RegistrarNivel',
        uriEliminarNivel: 'api/seguimientoControl/DesagregarEdt/EliminarNivel',
        uriObtenerErroresProyectoSeguimiento: 'api/gestionSeguimiento/ObtenerErroresSeguimiento',
        uriObtenerErroresSeguimiento: 'api/SeccionCapitulo/ObtenerErroresSeguimiento',
        uriEditarProgramarActividad: 'api/seguimientoControl/ProgramarActividades/EditarProgramarActividad',
        apiBackboneGuardarProgramarProducto: 'api/seguimientoControl/ProgramarProductos/GuardarProgramarProducto',

        apiBackboneObtenerPreguntasAvanceFinanciero: 'api/seguimientoControl/ObtenerPreguntasAvanceFinanciero',
        apiBackboneGuardarPreguntasAvanceFinanciero: 'api/seguimientoControl/GuardarPreguntasAvanceFinanciero',
        apiBackboneObtenerAvanceFinanciero: 'api/seguimientoControl/ObtenerAvanceFinanciero',
        apiBackboneGuardarAvanceFinanciero: 'api/seguimientoControl/GuardarAvanceFinanciero',

        uriapiBackboneObtenerFocalizacionProgramacionSeguimiento: 'api/SeguimientoControl/FocalizacionIndicadores/ObtenerFocalizacionProgramacionSeguimiento',
        uriapiBackboneGuardarFocalizacionProgramacionSeguimiento: 'api/SeguimientoControl/FocalizacionIndicadores/GuardarFocalizacionProgramacionSeguimiento',
        uriapiBackboneObtenerCruceProgramacionSeguimiento: 'api/SeguimientoControl/FocalizacionIndicadores/ObtenerCruceProgramacionSeguimiento',
        uriapiBackboneGuardarCrucePoliticasSeguimiento: 'api/SeguimientoControl/FocalizacionIndicadores/GuardarCrucePoliticasSeguimiento',
        uriapiBackboneObtenerFocalizacionProgramacionSeguimientoDetalle: 'api/SeguimientoControl/FocalizacionIndicadores/ObtenerFocalizacionProgramacionSeguimientoDetalle',
        // Transversales
        apiBackBoneCapitulosModificados: 'api/SeccionesCapitulos/ObtenerCapitulosModificados',
        apiBackBoneCapitulosModificadosLocalizacion: 'api/SeccionesCapitulos/ObtenerCapitulosModificadosLocalizacion',
        apiBackBoneCapitulosByMacroproceso: 'api/SeccionesCapitulos/ObtenerCapitulosByMacroproceso',
        apiBackBoneValidarCapitulos: 'api/SeccionesCapitulos/ValidarCapitulos',
        apiBackBoneObtenerErroresProyecto: 'api/SeccionesCapitulos/ObtenerErroresProyecto',
        apiBackboneCambiosFirmeRelacionPlanificacion: 'api/CambiosFirme/ObtenerRelacionPlanificacion',
        apiBackboneGuardarCambiosFirmeRelacionPlanificacion: 'api/CambiosFirme/guardarCambiosFirmeRelacionPlanificacion',
        apiCambiosFirmeObtenerJustificacionHorizonte: 'api/CambiosFirme/ObtenerJustificacionHorizonte',
        apiBackboneGuardarCambiosFirmeJustificacionHorizonte: 'api/CambiosFirme/guardarCambiosFirmeJustificacionHorizonte',
        uriObtenerJustificacionHorizonte: 'api/TramitesProyectos/ObtenerJustificacionHorizonte',
        uriGuardarCambiosJustificacionHorizonte: 'api/TramitesProyectos/guardarCambiosFirmeJustificacionHorizonte',
        apiBackBoneNombrePDFCartaFirma: '26426-iniciales_Despedida',

        apiBackBoneObtenerErroresTramite: 'api/SeccionesCapitulos/ObtenerErroresTramite',
        apiBackBoneObtenerSeccionesTramite: 'api/SeccionesCapitulos/ObtenerSeccionesTramite',
        apiBackbonEliminarCambiosFirme: 'api/CambiosFirme/eliminarCapituloModificado',

        apiBackBoneObtenerErroresViabilidad: 'api/SeccionesCapitulos/ObtenerErroresViabilidad',
        apiBackboneFocalizacionActualizaPoliticasModificadas: 'api/CambiosFirme/FocalizacionActualizaPoliticasModificadas',
        //encabezadp
        apiBackboneObtenerEncabezadoGeneral: 'api/proyecto/ObtenerEncabezadoGeneral',
        apiBackboneObtenerEncabezadoSGR: 'api/proyecto/ObtenerEncabezadoSGR',
        apiBackboneObtenerEncabezadoSGP: 'api/proyecto/ObtenerEncabezadoSGP',
        apiBackboneActualizarHorizonte: 'api/Proyecto/actualizarHorizonte',

        //Indicadores
        apiBackboneObtenerIndicadorProducto: 'api/proyecto/ObtenerIndicadoresProducto',
        apiBackboneGuardarIndicadorSecundario: 'api/proyecto/GuardarIndicadoresSecundarios',
        apiBackboneEliminarIndicadorProducto: 'api/proyecto/EliminarIndicadorProducto',
        apiBackboneActualizarMetaAjusteIndicador: 'api/proyecto/ActualizarMetaAjusteIndicador',
        apiBackboneIndicadoresValidarCapituloModificado: 'api/proyecto/IndicadoresValidarCapituloModificado',
        apiBackboneRegionalizacionGeneral: 'api/proyecto/RegionalizacionGeneral',
        apiBackboneRegionalizacionGeneralSgp: 'api/proyecto/RegionalizacionGeneralSgp',
        apiBackboneguardarRegionalizacionFuentesFinanciacionAjustes: 'api/proyecto/GuardarRegionalizacionFuentesFinanciacionAjustes',
        apiBackboneguardarFocalizacionCategoriasAjustes: 'api/proyecto/GuardarFocalizacionCategoriasAjustes',
        apiBackboneRegionalizacionDetalle: 'api/proyecto/RegionalizacionDetalle',
        //Radicado ORFEO
        apiBackboneReasignarRadicado: 'api/Tramites/ReasignarRadicadoORFEO',

        //Costo Actividades
        apiBackboneObtenerResumenObjetivosProductosActividades: 'api/proyecto/ObtenerResumenObjetivosProductosActividades',
        apiBackboneObtenerResumenObjetivosProductosActividadesJustificacion: 'api/proyecto/ObtenerResumenObjetivosProductosActividadesJustificacion',
        apiBackboneGuardarCostoActividades: 'api/proyecto/GuardarCostoActividades',
        apiBackboneAgregarEntregable: 'api/proyecto/AgregarEntregable',
        apiBackboneEliminarEntregable: 'api/proyecto/EliminarEntregable',

        //Vigencias Futuras
        apiBackBoneTramiteEnPasoUno: 'api/Tramites/TramiteEnPasoUno',
        apiBackBoneObtenerDetallesTramite: 'api/Flujos/ObtenerDetalleTramite',
        apiBackBoneDevolverInstanciasHijas: 'api/Proyecto/DevolverInstanciasHijas',
        apiBackBoneObtenrTramiteConpes: 'api/Tramites/ObtenerConpesAsociados',
        apiBackboneObtenerPreguntasProyectoActualizacionPaso: "api/Tramites/ObtenerPreguntasProyectoActualizacionPaso",

        apiBackBoneAsociarTramiteConpes: 'api/Tramites/AsociarConpesTramite',
        apiBackBoneObtenerProyectosPorTramite: 'api/Flujos/ObtenerProyectosPorTramite',
        apiBackBoneRemoverAsociacionTramiteConpes: 'api/Tramites/RemoverAsociacionConpesTramite',
        apiBackBoneObtenerDetalleTramitePorInstancia: 'api/Tramites/ObtenerTramitePorInstancia',
        apiBackBoneValidarConpesTramite: 'api/Tramites/ValidarConpesTramiteVigenciaFutura',
        apiBackboneEliminarAsociacionVFOPLN: 'api/Tramites/EliminarAsociacionVFOPLN',
        apiBackboneObtenerProyectoAsociacionVFO: 'api/Tramites/ObtenerProyectoAsociacionVFO',
        apiBackboneAsociarProyectoVFOPLN: 'api/Tramites/AsociarProyectoVFO',
        apiBackboneObtenerDatosProyectoTramite: 'api/Tramites/ObtenerDatosProyectoTramite',
        apiBackboneGuardarInformacionPresupuestalValores: 'api/Tramites/GuardarInformacionPresupuestalValores',
        apiBackboneObtenerValores: 'api/Tramites/ObtenerInformacionPresupuestalValores',
        apiBackboneCargarSolicitudesConcepto: 'api/Tramites/ObtenerSolicitarConceptoPorTramite',
        apiBackboneObtenerDatosCronograma: 'api/Tramites/ObtenerDatosCronograma',
        apiBackBoneValidacionPeriodoPresidencial: 'api/TramitesProyectos/ValidacionPeriodoPresidencial',

        apiBackBoneTramitesGenerarRadicado: 'api/Tramites/GenerarRadicadoSalida',
        apiBackBoneTramitesCerrar_CargarDocumentoElectronicoOrfeo: 'api/Tramites/Cerrar_CargarDocumentoElectronicoOrfeo',


        apiBackBoneObtenerDeflactores: 'api/Tramites/ObtenerDeflactores',
        apiBackBoneObtenerProyectoTramite: 'api/Tramites/ObtenerProyectoTramite',
        apiBackBoneActualizaVigenciaFuturaProyectoTramite: 'api/Tramites/ActualizaVigenciaFuturaProyectoTramite',
        apiBackBoneObtenerFuentesFinanciacionVigenciaFuturaCorriente: 'api/Tramites/ObtenerFuentesFinanciacionVigenciaFuturaCorriente',
        apiBackBoneEliminarPermisosAccionesUsuarios: 'api/Tramites/EliminarPermisosAccionesUsuarios',
        apiBackBoneObtenerAccionActualyFinal: 'api/Tramites/ObtenerAccionActualyFinal',
        apiBackboneActualizarVigenciaFuturaFuente: 'api/Tramites/ActualizarVigenciaFuturaFuente',
        apiBackBoneObtenerFuentesFinanciacionVigenciaFuturaConstante: 'api/Tramites/ObtenerFuentesFinanciacionVigenciaFuturaConstante',
        apiBackBoneEnviarConceptoDireccionTecnicaTramite: 'api/Tramites/EnviarConceptoDireccionTecnicaTramite',
        apiBackBoneObtenerProductosVigenciaFuturaConstante: 'api/Tramites/ObtenerProductosVigenciaFuturaConstante',
        apiBackBoneObtenerProductosVigenciaFuturaCorriente: 'api/Tramites/ObtenerProductosVigenciaFuturaCorriente',
        apiBackboneActualizarVigenciaFuturaProducto: 'api/Tramites/ActualizarVigenciaFuturaProducto',
        apiBackboneObtenerDatosUsuarioTramite: 'api/Tramites/ObtenerDatosUsuario',
        apiBackboneObtenerDatosProyectosPorTramite: 'api/Tramites/ObtenerDatosProyectosPorTramite',
        //Focalizacion
        apiBackboneObtenerFocalizacionPoliticasTransversalesFuentes: 'api/Focalizacion/ObtenerFocalizacionPoliticasTransversalesFuentes',
        apiBackboneEliminarPoliticaProyecto: "api/Focalizacion/EliminarPoliticaProyecto",
        apiBackboneEliminarCategoriaPoliticaProyecto: "api/Focalizacion/EliminarCategoriaPoliticaProyecto",

        //Focalizacion - PoliticaCrucePoliticas
        apiBackBoneObtenerPoliticasTransversalesCrucePoliticas: 'api/Focalizacion/ObtenerPoliticasTransversalesCrucePoliticas',
        apiBackBoneActualizarPoliticasTransversalesCrucePoliticas: 'api/Focalizacion/ActualizarPoliticasTransversalesCrucePoliticas',

        // Localizaciones
        apiBackboneObtenerListaAgrupaciones: 'api/Proyecto/ObtenerListaAgrupaciones',
        apiBackboneObtenerListaTipoAgrupaciones: 'api/Proyecto/ObtenerListaTipoAgrupaciones',
        apiBackboneGuardarTempLocalizaciones: 'api/Localizacion/Temporal',
        apiBackboneGuardarDefLocalizaciones: 'api/Localizacion/GuardarLocalizacion',
        apiBackboneObtenerDepartamentosLocalizacion: 'api/Catalogo/Departamentos',
        apiBackboneObtenerMunicipiosLocalizacion: 'api/Catalogo/Municipios',
        apiBackboneObtenerListaAgrupacionesCompleta: 'api/Catalogo/Agrupaciones',
        apiBackboneObtenerJustificacionLocalizacionProyecto: 'api/Proyecto/ObtenerJustificacionLocalizacionProyecto',


        //Flujos tramite
        pasoControlPosteriorDNPAplicado: "Control Posterior DNP Aplicado",
        apiBackboneRolConceptoTecnico: "35063490-3D6B-4C68-8498-7FF8A9C25096",


        apiBackBoneObtenerModalidadesContratacion: 'api/Tramites/ObtenerModalidadesContratacion',
        apiBackBoneActualizarActividadesCronograma: 'api/Tramites/ActualizarActividadesCronograma',
        apiBackBoneObtenerActividadesPrecontractualesProyectoTramite: 'api/Tramites/ObtenerActividadesPrecontractualesProyectoTramite',

        apiBackBoneobtenerDetalleAjustesJustificaionFacalizacionPT: 'api/SeccionesCapitulos/ObtenerDetalleAjustesJustificaionFacalizacionPT',
        apiBackboneobtenerSeccionOtrasPoliticasFacalizacionPT: 'api/Proyecto/ObtenerSeccionOtrasPoliticasFacalizacionPT',
        apiBackboneObtenerSeccionPoliticasDT: 'api/Proyecto/ObtenerSeccionPoliticaFocalizacionDT',
        apiBackBoneTramiteAjusteEnPasoUno: 'api/Tramites/TramiteAjusteEnPasoUno',

        //Beneficiarios
        apiBackboneObtenerProyectosBeneficiarios: 'api/Proyecto/ObtenerProyectosBeneficiarios',
        apiBackboneObtenerProyectosBeneficiariosDetalle: 'api/Proyecto/ObtenerProyectosBeneficiariosDetalle',
        apiBackboneObtenerJustificacionProyectosBeneficiarios: 'api/Proyecto/ObtenerJustificacionProyectosBeneficiarios',
        apiBackboneGuardarBeneficiarioTotales: 'api/Proyecto/GuardarBeneficiarioTotales',
        apiBackboneGuardarBeneficiarioProducto: 'api/Proyecto/GuardarBeneficiarioProducto',
        apiBackboneGuardarBeneficiarioProductoLocalizacion: 'api/Proyecto/GuardarBeneficiarioProductoLocalizacion',
        apiBackboneGuardarBeneficiarioProductoLocalizacionCaracterizacion: 'api/Proyecto/GuardarBeneficiarioProductoLocalizacionCaracterizacion',



        apiBackBoneObtenerModificacionLeyenda: 'api/Tramites/ObtenerModificacionLeyenda',
        apiBackBoneActualizaModificacionLeyenda: 'api/Tramites/ActualizarModificacionLeyenda',
        //AprobacionEntidad
        apiBackBoneObtenerPreguntasAprobacionEntidad: 'api/Tramites/ObtenerPreguntasJustificacion',
        apiBackBoneGuardarPreguntasAprobacionEntidadPresupuesto: 'api/Tramite/GuardarRespuestasJustificacion',
        //Priorizacion
        apiBackBoneConsultarPriorizacionPorBPIN: 'api/priorizacion/ConsultarPriorizacionPorBPINs',
        apiBackBoneConsultarFuentesSGR: 'api/priorizacion/ConsultarFuentesSGR',
        apiBackBoneRegistrarFuentesSGR: 'api/priorizacion/RegistrarFuentesSGR',
        apiBackBoneConsultarFuentesNoSGR: 'api/priorizacion/ConsultarFuentesNoSGR',
        apiBackBoneRegistrarFuentesNoSGR: 'api/priorizacion/RegistrarFuentesNoSGR',
        apiBackBoneRegistrarDatosAdicionalesCofinanciadorFuentesNoSGR: 'api/priorizacion/RegistrarDatosCofinanciadorFuentesNoSGR',
        apiBackBoneConsultarDatosAdicionalesCofinanciadorFuentesNoSGR: 'api/priorizacion/ConsultarDatosCofinanciadorFuentesNoSGR',
        apiBackBoneConsultarResumenFuentesCostos: 'api/priorizacion/ConsultarResumenFuentesCostos',
        apiBackBoneConsultarTiposCofinanciaciones: 'api/priorizacion/TiposCofinanciaciones',
        apiBackboneObtenerPriorizacionProyecto: 'api/Priorizacion/ObtenerPriorizacionProyecto',
        apiBackboneObtenerAprobacionProyecto: 'api/Priorizacion/ObtenerAprobacionProyecto',
        apiBackboneSGR_ObtenerPriorizionProyectoDetalleSGR: 'api/Priorizacion/ObtenerPriorizionProyectoDetalle',
        apiBackboneSGR_GuardarPriorizionProyectoDetalleSGR: 'api/Priorizacion/GuardarPriorizionProyectoDetalleSGR',
        apiBackboneSGR_GuardarPermisosPriorizionProyectoDetalleSGR: 'api/Priorizacion/GuardarPermisosPriorizionProyectoDetalleSGR',
        apiBackboneSGR_ObtenerAprobacionProyectoCredito: 'api/Aprobacion/ObtenerAprobacionProyectoCredito',
        apiBackboneSGR_GuardarAprobacionProyectoCredito: 'api/Aprobacion/GuardarAprobacionProyectoCredito',
        //Aprobacion
        apiBackboneObtenerProyectoAprobacionInstanciasSGR: 'api/Aprobacion/ObtenerProyectoAprobacionInstanciasSGR',
        apiBackboneGuardarProyectoAprobacionInstanciasSGR: 'api/Aprobacion/GuardarProyectoAprobacionInstanciasSGR',
        apiBackboneObtenerProyectoResumenAprobacionSGR: 'api/Aprobacion/ObtenerProyectoResumenAprobacionSGR',
        apiBackboneObtenerProyectoResumenAprobacionCreditoParcialSGR: 'api/Aprobacion/ObtenerProyectoResumenAprobacionCreditoParcialSGR',
        apiBackboneObtenerProyectoResumenEstadoAprobacionCreditoSGR: 'api/Aprobacion/ObtenerProyectoResumenEstadoAprobacionCreditoSGR',

        //Entidad
        apiBackBoneEntidadDNP: 'fbb8bab4-868b-4422-84f7-58b16f556ad6',

        //Liberación de Vigencias Futuras.
        apiBackboneObtenerTramitesVFparaLiberar: 'api/Tramites/ObtenerTramitesVFparaLiberar',
        apiBackboneGuardarLiberacionVigenciaFutura: 'api/Tramites/GuardarLiberacionVigenciaFutura',
        apiBackboneObtenerLiberacionVigenciaFutura: 'api/Tramites/ObtenerLiberacionVigenciasFuturas',
        apiBackboneInsertaAutorizacionVigenciasFuturas: 'api/Tramites/InsertaAutorizacionVigenciasFuturas',
        apiBackboneInsertaValoresUtilizadosLiberacionVF: 'api/Tramites/InsertaValoresUtilizadosLiberacionVF',
        apiBackboneObtenerResumenLiberacionVigenciaFutura: 'api/Tramites/ObtenerResumenLiberacionVigenciasFuturas',
        apiBackboneObtenerValUtilizadosLiberacionVigenciasFuturas: 'api/Tramites/ObtenerValUtilizadosLiberacionVigenciasFuturas',
        apiBackboneInsertaValoresproductosLiberacionVFCorrientes: 'api/Tramites/InsertaValoresproductosLiberacionVFCorrientes',
        apiBackboneInsertaValoresproductosLiberacionVFConstantes: 'api/Tramites/InsertaValoresproductosLiberacionVFConstantes',
        uriobtenerTarmitesPorProyectoEntidad: 'api/Tramites/ObtenerTarmitesPorProyectoEntidad',
        apiBackboneEliminarLiberacionVigenciaFutura: 'api/Tramites/EliminarLiberacionVigenciaFutura',

        //Log Instancias
        apiBackBoneObtenerLogInstancia: 'api/Flujo/ObtenerLog',
        apiBackBoneObtenerLogInstanciaSubpasos: 'api/Flujo/ObtenerLogSubpasos',
        //comunes asociacion.
        apiBackboneobtenerEntidadAsociarProyecto: 'api/Tramites/obtenerEntidadAsociarProyecto',

        //Documento Soporte
        apiBackbone_ObtenerListaTipoDocumentoSoporteTrv: 'api/Transversal/DocumentoSoporte/ObtenerListaTipoDocumentosSoportePorRolTrv',
        apiBackbone_ObtenerListadoArchivosPIIP: 'api/Transversal/ObtenerListadoArchivosPIIP/',
        apiBackbone_ObtenerListadoArchivosMGA: 'api/Transversal/ObtenerListadoArchivosMGA/',
        apiBackbone_ObtenerListadoArchivosSUIFP: 'api/Transversal/ObtenerListadoArchivosSUIFP/',

        //SGR
        idRolViabilidadDefinitiva: '0eb96a9d-bf38-4688-a2a8-5541ec54ce3c',
        codigoTipoDocumentoViabilidad: 'DV-SGR',
        codigoTipoDocumentoInsumoOtroSector: 'IOS-SGR',
        apiBackBoneObtenerOperacionCreditoDatosGenerales: 'api/SGR/ObtenerOperacionCreditoDatosGenerales',
        apiBackboneGuardarOperacionCreditoDatosGenerales: 'api/SGR/GuardarOperacionCreditoDatosGenerales',
        apiBackboneEliminarOperacionCredito: 'api/SGR/EliminarOperacionCredito',
        apiBackBoneObtenerOperacionCreditoDetalles: 'api/SGR/ObtenerOperacionCreditoDetalles',
        apiBackboneGuardarOperacionCreditoDetalles: 'api/SGR/GuardarOperacionCreditoDetalles',
        apiBackboneObtenerTiposRecursosEntidadPorGrupoRecursos: "api/SGR/TiposRecursosEntidadPorGrupoRecursos",
        apiBackboneGuardarMontosTramite: 'api/Tramites/GuardarMontosTramite',
        apiBackboneConsultarEjecutor: 'api/administracion/ConsultarEjecutor',
        apiBackboneGuardarEjecutor: 'api/administracion/GuardarEjecutor',
        apiBackboneSGR_Proyectos_GuardarProyectoPermisosProcesoSGR: 'api/SGR/Proyectos/GuardarProyectoPermisosProcesoSGR',
        //Rutas para la administracion de documentos
        apiBackboneDocumentoConsultar: 'api/administracion/ConsultarDocumento',
        apiBackboneDocumentoCrear: 'api/administracion/CrearDocumento',
        apiBackboneDocumentoActualizar: 'api/administracion/ActulizarDocumento',
        apiBackboneDocumentoEliminar: 'api/administracion/EliminarDocumento',
        apiBackboneDocumentoEstado: 'api/administracion/EstadoDocumento',
        apiBackboneDocumentoReferencias: 'api/administracion/ReferenciasDocumento',
        //Rutas para la administracion de usos de documentos
        apiBackboneDocumentoConsultarUso: 'api/administracion/ConsultarUsoDocumento',
        apiBackboneDocumentoCrearUso: 'api/administracion/CrearUsoDocumento',
        apiBackboneDocumentoActualizarUso: 'api/administracion/ActualizarUsoDocumento',
        apiBackboneDocumentoUsoEliminar: 'api/administracion/EliminarUsoDocumento',


        apiBackboneObtenerEjecutorByTipoEntidad: 'api/SGR/ObtenerEjecutorByTipoEntidad',
        apiBackboneObtenerEjecutores: 'api/SGR/ObtenerEjecutores',
        apiBackboneSGR_Acuerdo_LeerProyecto: 'SGR/Acuerdo/LeerProyecto',
        apiBackboneSGR_Acuerdo_GuardarProyecto: 'SGR/Acuerdo/GuardarProyecto',
        apiBackboneSGR_Proyectos_LeerListas: 'SGR/Proyectos/LeerListas',
        apiBackBoneConsultarDelegarViabilidadSgr: 'api/SGR/DelegarViabilidad/ObtenerProyecto',
        apiBackBoneConsultarEntidadesDelegarViabilidadSgr: 'api/SGR/DelegarViabilidad/ObtenerEntidadesDelegar',
        apiBackBoneRegistrarDelegarViabilidad: 'api/SGR/DelegarViabilidad/RegistrarDelegarViabilidad',
        apiBackboneObtenerEjecutoresAsociados: 'api/SGR/ObtenerEjecutoresAsociados',
        apiBackboneCrearEjecutorAsociado: 'api/SGR/CrearEjecutorAsociado',
        apiBackboneEliminarEjecutorAsociado: 'api/SGR/EliminarEjecutorAsociado',
        apiBackboneSGR_Viabilidad_LeerInformacionGeneral: 'api/SGR/Viabilidad/LeerInformacionGeneral',
        apiBackboneSGR_Viabilidad_LeerParametricas: 'api/SGR/Viabilidad/LeerParametricas',
        apiBackboneSGR_Viabilidad_GuardarInformacionBasica: 'api/SGR/Viabilidad/GuardarInformacionBasica',
        apiBackboneSGR_ObtenerTipoDocumentoSoporte: 'api/SGR/Transversal/ObtenerTipoDocumentoSoporte',
        apiBackboneSGR_ObtenerListaTipoDocumentoSoporte: 'api/SGR/Transversal/ObtenerListaTipoDocumentoSoporte',
        apiBackBoneSGRLeerProyectoViabilidadInvolucrados: 'api/SGR/Proyectos/LeerProyectoViabilidadInvolucrados',
        apiBackBoneProyectoViabilidadInvolucradosAgregar: 'api/SGR/Proyectos/ProyectoViabilidadInvolucrados/Agregar',
        apiBackBoneProyectoViabilidadInvolucradosEliminar: 'api/SGR/Proyectos/ProyectoViabilidadInvolucrados/Eliminar',
        apiBackBoneObtenerUsuariosInvolucrados: 'api/Proyecto/ObtenerUsuariosBasicosPorRolEntidad',
        apiBackBoneSGRLeerProyectoViabilidadInvolucradosFirma: 'api/SGR/Proyectos/LeerProyectoViabilidadInvolucradosFirma',
        apiBackBoneSGR_Transversal_LeerParametro: 'SGR/Transversal/LeerParametro',
        apiBackBone_LeerListaParametros: 'SGR/Transversal/LeerListaParametros',
        apiBackBoneObtenerUsuariosPorRolEntidad: 'api/Proyecto/ObtenerUsuariosBasicosPorRolEntidad',
        apiBackBoneSGR_Transversal_ObtenerConfiguracionReportes: 'api/SGR/Transversal/LeerConfiguracionReportes',
        apiBackBoneSGR_ProyectosPriorizar: 'api/Flujos/ProyectosPriorizarSGR',
        //Regionalizacion SGR
        apiBackboneObtenerDesagregarRegionalizacionSgr: 'SGR/Transversales/ObtenerDesagregarRegionalizacionSgr',
        apiBackboneObtenerDatosGeneralesProyectoSgr: 'SGR/Transversales/ObtenerDatosGeneralesProyectoSgr',
        //Focalizacion SGR 
        apiBackBoneObtenerFocalizacionPoliticasTransversalesFuentesSgr: 'SGR/Transversales/ObtenerFocalizacionPoliticasTransversalesFuentesSgr',
        apiBackBoneObtenerPoliticasTransversalesCrucePoliticasSgr: 'SGR/Transversales/ObtenerPoliticasTransversalesCrucePoliticasSgr',
        apiBackBoneObtenerDatosIndicadoresPoliticaSgr: 'SGR/Transversales/ObtenerDatosIndicadoresPoliticaSgr',
        apiBackBoneObtenerDatosCategoriaProductosPoliticaSgr: 'SGR/Transversales/ObtenerDatosCategoriaProductosPoliticaSgr',
        apiBackBoneGuardarFocalizacionCategoriasAjustesSgr: 'SGR/Transversales/GuardarFocalizacionCategoriasAjustesSgr',
        //Focalizacion Registro SGR         
        apiBackBoneObtenerPoliticasTransversalesProyectoSgr: 'SGR/Transversales/ObtenerPoliticasTransversalesProyectoSgr',
        apiBackBoneEliminarPoliticasProyectoSgr: 'SGR/Transversales/EliminarPoliticasProyectoSgr',
        apiBackBoneAgregarPoliticasTransversalesAjustesSgr: 'SGR/Transversales/AgregarPoliticasTransversalesAjustesSgr',
        apiBackBoneConsultarPoliticasCategoriasIndicadoresSgr: 'SGR/Transversales/ConsultarPoliticasCategoriasIndicadoresSgr',
        apiBackBoneObtenerPoliticasTransversalesCategoriasSgr: 'SGR/Transversales/ObtenerPoliticasTransversalesCategoriasSgr',
        apiBackBoneEliminarCategoriasPoliticasProyectoSgr: 'SGR/Transversales/EliminarCategoriasPoliticasProyectoSgr',
        apiBackBoneModificarPoliticasCategoriasIndicadoresSgr: 'SGR/Transversales/ModificarPoliticasCategoriasIndicadoresSgr',
        apiBackBoneObtenerCrucePoliticasAjustesSgr: 'SGR/Transversales/ObtenerCrucePoliticasAjustesSgr',
        apiBackBoneGuardarCrucePoliticasAjustesSgr: 'SGR/Transversales/GuardarCrucePoliticasAjustesSgr',
        apiBackBoneObtenerPoliticasTransversalesResumenSgr: 'SGR/Transversales/ObtenerPoliticasTransversalesResumenSgr',
        //Firmas SGR
        apiBackBoneCargarFirmaSgr: 'api/SGR/CargarFirma',
        apiBackBoneValidarSiExisteFirmaUsuarioSgr: 'api/SGR/validarSiExisteFirmaUsuario',
        apiBackBoneBorrarFirmaSgr: 'api/SGR/BorrarFirma',
        apiBackBoneFirmarSgr: 'api/SGR/Firmar',
        //OCAD Paz SGR
        apiBackboneSGR_Proyectos_LeerProyectoCtus: 'api/SGR/Proyectos/LeerProyectoCtus',
        apiBackboneSGR_Proyectos_LeerEntidadesSolicitarCtus: 'api/SGR/Proyectos/LeerEntidadesSolicitarCtus',
        apiBackboneSGR_Proyectos_GuardarProyectoSolicitarCtus: 'api/SGR/Proyectos/GuardarProyectoCtus',
        apiBackboneSGR_Transversal_ValidacionOCADPaz: 'api/SGR/Transversal/ValidacionOCADPaz',
        apiBackboneObtenerProyectoVerificacionOcadPazSgr: 'api/Proyecto/ObtenerProyectosVerificacionOcadPazSgr',
        apiBackBoneObtenerUsuariosVerificacionOcadPaz: 'api/SGR/Proyectos/ObtenerUsuariosVerificacionOcadPaz',
        apiBackboneSGR_OCADPaz_GuardarAsignacionUsuarioEncargado: 'api/SGR/OCADPaz/GuardarAsignacionUsuarioEncargado',
        apiBackboneSGR_Proyectos_ValidarTecnicoOcadPaz: 'SGR/Proyectos/validarTecnicoOcadpaz',
        apiFlujosSubPasoEjecutar: 'api/Flujos/SubPasoEjecutar',
        apiFlujosSubPasosValidar: 'api/Flujos/SubPasosValidar',
        idSubPasoAsignacionOcadPazSgr: '69C8A7AA-3141-4798-AD02-C6DFE07E64DB',
        idSubPasoTecnicoOcadPazSgr: 'D618A017-A347-4B6F-B7B2-C7DE1AD5913D',
        idSubPasoSeguimientoControlOcadPazSgr: '725135C6-252B-45B9-9752-EA6763BEAAB0',
        idSubPasoRevisionCoordinadorOcadPazSgr: 'A36F7894-86AD-4AF0-9349-C0DCBEBE6206',
        idSubPasoSubdirectorOcadPazSgr: '34BFCFE1-B4F9-4EB9-98C4-DA5EEB70FB54',
        apiBackboneSGR_OCADPaz_GenerarFichaVerificacion: 'api/GenerarFichaManualSubFlujoSGR',
        apiBackBoneValidarInstanciaCTUSNoFinalizada: 'api/SGR/Proyectos/ValidarInstanciaCTUSNoFinalizada',
        apiBackBoneValidarViavilidadCumplimentoFlujoSGR: 'api/SGR/Proyectos/CumplimentoFlujoSGR',
        apiBackBoneTieneInstanciaActiva: 'api/SGR/Proyectos/TieneInstanciaActiva',
        apiBackBoneObtenerPuntajeProyecto: 'api/SGR/Viabilidad/ObtenerPuntajeProyecto',
        apiBackBoneGuardarPuntajeProyecto: 'api/SGR/Viabilidad/GuardarPuntajeProyecto',

        //Entidad Nacional SGR
        apiBackboneSGR_Proyectos_LeerEntidadesAdscritas: 'api/SGR/Proyectos/LeerEntidadesAdscritas',
        apiBackboneSGR_Proyectos_ActualizarEntidadAdscrita: 'api/SGR/Proyectos/ActualizarEntidadAdscrita',
        apiBackboneSGR_Proyectos_GuardarAsignacionUsuarioEncargado: 'api/SGR/Proyectos/GuardarAsignacionUsuarioEncargado',
        apiBackboneSGR_Proyectos_ValidarEntidadDelegada: 'api/SGR/Proyectos/ValidarEntidadDelegada',
        apiBackboneSGR_Proyectos_LeerAsignacionUsuarioEncargado: 'api/SGR/Proyectos/LeerAsignacionUsuarioEncargado',

        //CTUS
        apiBackboneSGR_CTUS_GuardarAsignacionUsuarioEncargado: 'api/SGR/CTUS/GuardarAsignacionUsuarioEncargado',
        apiBackboneSGR_CTUS_LeerProyectoCtusConcepto: 'api/SGR/CTUS/LeerProyectoCtusConcepto',
        apiBackboneSGR_CTUS_GuardarProyectoCtusConcepto: 'api/SGR/CTUS/GuardarProyectoCtusConcepto',
        apiBackboneSGR_CTUS_LeerProyectoCtusUsuarioEncargado: 'api/SGR/CTUS/LeerProyectoCtusUsuarioEncargado',
        apiBackboneSGR_CTUS_GuardarResultadoConceptoCtus: 'api/SGR/CTUS/GuardarResultadoConceptoCtus',
        apiBackboneSGR_CTUS_ActualizarEntidadAdscritaCTUS: 'api/SGR/CTUS/ActualizarEntidadAdscritaCTUS',

        //CTEI
        apiBackboneSGR_CTEI_LeerDatosAdicionalesCTEI: 'api/SGR/Proyectos/LeerDatosAdicionalesCTEI',
        apiBackboneSGR_CTEI_GuardarDatosAdicionalesCTEI: 'api/SGR/Proyectos/GuardarDatosAdicionalesCTEI',

        //AvalUso
        apiBackboneSGR_Proyectos_RegistrarAvalUso: 'api/SGR/Proyectos/RegistrarAvalUsoSgr',
        apiBackboneSGR_Proyectos_LeerAvalUso: 'api/SGR/Proyectos/LeerAvalUsoSgr',

        // Priorizacion SGR
        apiBackboneSGR_Proyectos_MostrarEstadosPriorizacion: 'SGR/Proyectos/MostrarEstadosPriorizacion',

        //Designacion Ejecutor
        apiBackboneSGR_Procesos_ActualizarValorEjecutorSGR: 'api/SGR/Procesos/ActualizarValorEjecutorSGR',
        apiBackboneSGR_Procesos_LeerValoresAprobacionSGR: 'api/SGR/Procesos/LeerValoresAprobacionSGR',
        apiBackboneSGR_Procesos_ObtenerRespuestaEjecutorSGR: 'api/SGR/Procesos/ObtenerRespuestaEjecutorSGR',
        apiBackboneSGR_Procesos_RegistrarRespuestaEjecutorSGR: 'api/SGR/Procesos/RegistrarRespuestaEjecutorSGR',
        apiBackboneSGR_Procesos_ConsultarEjecutorbyTipo: 'api/SGR/Procesos/ConsultarEjecutorbyTipo',
        apiBackboneSGR_Procesos_ObtenerValorCostosEstructuracionViabilidadSGR: 'api/SGR/Procesos/ObtenerValorCostosEstructuracionViabilidadSGR',

        //Traslados
        apiBackboneObtenerPreguntasJustificacionPorProyectos: 'api/Tramites/ObtenerPreguntasJustificacionPorProyectos',
        apiBackboneObtenerListaProyectosFuentesAprobado: 'api/Tramites/ObtenerListaProyectosFuentesAprobado',
        apiBackboneObtenerEntidadTramite: 'api/Tramites/ObtenerEntidadTramite',

        //Catalogos.
        apiBackboneCatalogoTodosTipoEntidades: 'api/Catalogo/TodosTiposEntidades',
        apiBackBoneObtenerTablasBasicas: 'api/Catalogo/ObtenerTablasBasicas',

        //Flujos
        apiFlujosObtenerFlujosPorRoles: 'api/Flujo/ObtenerFlujosPorRoles',
        apiFlujosProyectos: 'api/Flujos/Proyectos',
        apiFlujosObtenerEstadoOcultarObservacionesGenerales: 'api/Flujos/ObtenerEstadoOcultarObservacionesGenerales',

        //Cargue Masivo
        apiBackboneActualizarCargueMasivo: 'api/Tramites/ActualizarCargueMasivo',
        apiBackboneConsultarCargueExcel: 'api/Tramites/ConsultarCargueExcel',

        //ReporteAvanceProducto

        apiBackboneConsultarAvanceMetaProducto: 'api/ReporteAvanceProducto/ConsultarAvanceMetaProducto',
        apiBackboneActualizarAvanceMetaProducto: 'api/ReporteAvanceProducto/ActualizarAvanceMetaProducto',

        //ReporteAvanceProducto
        apiBackboneConsultarAvanceRegionalizacion: 'api/ReporteAvanceRegionalizacion/ConsultarAvanceRegionalizacion',
        apiBackboneGuardarAvanceRegionalizacion: 'api/ReporteAvanceRegionalizacion/GuardarAvanceRegionalizacion',
        apiBackboneResumenAvanceRegionalizacion: 'api/ReporteAvanceRegionalizacion/ConsultarResumenAvanceRegionalizacion',
        apiBackboneObtenerDetalleRegionalizacionProgramacionSeguimiento: 'api/ReporteAvanceRegionalizacion/ObtenerDetalleRegionalizacionProgramacionSeguimiento',

        //Incorporaciones
        apiBackboneObtenerPresupuestalProyectosAsociados: 'api/Tramites/ObtenerPresupuestalProyectosAsociados',

        //Tramite Incorporacion
        apiBackboneObtenerDatosIncorporacion: 'api/TramiteIncorporacion/ObtenerDatosIncorporacion',
        apiBackboneGuardarDatosIncorporacion: 'api/TramiteIncorporacion/GuardarDatosIncorporacion',
        apiBackboneEiliminarDatosIncorporacion: 'api/TramiteIncorporacion/EiliminarDatosIncorporacion',
        apiBackboneObtenerCalendarioPeriodo: 'api/Tramites/ObtenerCalendarioPeriodo',
        apiBackboneGetOrigenRecursosTramite: 'api/Tramites/GetOrigenRecursosTramite',
        apiBackboneSetOrigenRecursosTramite: 'api/Tramites/SetOrigenRecursosTramite',

        //Tramite Distribución
        apiBackboneTramitesDistribucionAnteriores: 'api/TramitesDistribucion/ConsultarTramitesDistribucionAnteriores',

        //Tramite Adición Donación
        apiBackboneObtenerPresupuestalProyectosAsociados_Adicion: 'api/Tramites/ObtenerPresupuestalProyectosAsociados_Adicion',

        //Ajustes con Tramite
        apiBackboneObtenerResumenReprogramacionPorVigencia: 'api/Tramites/ObtenerResumenReprogramacionPorVigencia',
        apiBackboneGuardarDatosReprogramacion: 'api/Tramites/GuardarDatosReprogramacion',

        //Nuevo filtros consola
        apiBackboneObtenerEntidadesPorSector: 'api/Autorizacion/ObtnerEntidadesPorSector',
        apiBackboneObtenerFlujosPorTipoObjeto: 'api/Flujos/ObtenerFlujosPorTipoObjeto',
        apiBackboneObtenerAccionesFlujoPorFlujoId: 'api/Flujos/ObtenerAccionesFlujoPorFlujoId',
        apiBackboneObtenerVigencias: 'api/Flujos/ObtenerVigencias',

        //Tramite Reprogramación
        apiBackboneConsultarResumenReprogramacionPorProductoVigencia: 'api/Tramites/ObtenerResumenReprogramacionPorProductoVigencia',

        apiBackBoneObtenerModalidadContratacionVigenciasFuturas: 'api/Tramites/ObtenerModalidadContratacionVigenciasFuturas',
        apiBackBoneGuardarReprogramacionPorProductoVigencia: 'api/Proyecto/GuardarReprogramacionPorProductoVigencia',
        apiBackboneObtenerAutorizacionesParaReprogramacion: 'api/Tramites/ObtenerAutorizacionesParaReprogramacion',
        apiBackboneAsociarAutorizacionRVF: 'api/Tramites/AsociarAutorizacionRVF',
        apiBackboneObtenerAutorizacionAsociada: 'api/Tramites/ObtenerAutorizacionAsociada',
        apiBackboneEliminaReprogramacionVF: 'api/Tramites/EliminaReprogramacionVF',

        //Soportes del proyecto
        apiBackboneObtenerSoportesProyecto: 'api/Proyecto/ObtenerSoportesProyecto',
        apiBackboneDescargarArchivosProyecto: 'api/manejadorArchivos/DescargarDocumentosProyectos',

        //Soportes del proyecto

        //Programación Distribución
        apiBackboneObtenerDatosProgramacionEncabezado: 'api/ProgramacionDistribucion/ObtenerDatosProgramacionEncabezado',
        apiBackboneObtenerDatosProgramacionDetalle: 'api/ProgramacionDistribucion/ObtenerDatosProgramacionDetalle',
        apiBackBoneGuardarDatosProgramacionDistribucion: 'api/ProgramacionDistribucion/GuardarDatosProgramacionDistribucion',
        apiBackBoneGuardarDatosProgramacionFuentes: 'api/ProgramacionFuentes/GuardarDatosProgramacionFuentes',
        apiBackBoneValidarCalendarioProgramacion: 'api/Programacion/ValidarCalendarioProgramacion',
        apiBackBoneGuardarProgramacionRegionalizacion: 'api/Programacion/GuardarProgramacionRegionalizacion',
        apiBackBoneConsultarPoliticasTransversalesProgramacion: 'api/Programacion/ConsultarPoliticasTransversalesProgramacion',
        apiBackBoneAgregarPoliticasTransversalesProgramacion: 'api/Programacion/AgregarPoliticasTransversalesProgramacion',
        apiBackBoneConsultarPoliticasTransversalesCategoriasProgramacion: 'api/Programacion/ConsultarPoliticasTransversalesCategoriasProgramacion',
        apiBackBoneEliminarPoliticasProyectoProgramacion: 'api/Programacion/EliminarPoliticasProyectoProgramacion',
        apiBackBoneAgregarCategoriasPoliticaTransversalesProgramacion: 'api/Programacion/AgregarCategoriasPoliticaTransversalesProgramacion',
        apiBackBoneGuardarPoliticasTransversalesCategoriasProgramacion: 'api/Programacion/GuardarPoliticasTransversalesCategoriasProgramacion',
        apiBackBoneEliminarCategoriasProyectoProgramacion: 'api/Programacion/EliminarCategoriasProyectoProgramacion',
        apiBackBoneEliminarCategoriaPoliticasProyectoProgramacion: 'api/Programacion/EliminarCategoriaPoliticasProyectoProgramacion',
        apiBackBoneObtenerCrucePoliticasProgramacion: 'api/Programacion/ObtenerCrucePoliticasProgramacion',
        apiBackBonePoliticasSolicitudConceptoProgramacion: 'api/Programacion/PoliticasSolicitudConceptoProgramacion',
        apiBackBoneGuardarCrucePoliticasProgramacion: 'api/Programacion/GuardarCrucePoliticasProgramacion',
        apiBackBoneSolicitarConceptoDTProgramacion: 'api/Programacion/SolicitarConceptoDTProgramacion',
        apiBackBoneObtenerResumenSolicitudConceptoProgramacion: 'api/Programacion/ObtenerResumenSolicitudConceptoProgramacion',
        apiBackBoneObtenerErroresProgramacion: 'api/SeccionesCapitulos/ObtenerErroresProgramacion',

        apiBackBoneObtenerProgramacionBuscarProyecto: 'api/Programacion/ObtenerProgramacionBuscarProyecto',
        apiBackBoneBorrarTramiteProyecto: 'api/Programacion/BorrarTramiteProyecto',
        apiBackBoneGuardarDatosInclusion: 'api/Programacion/GuardarDatosInclusion',
        apiBackBoneGuardarPoliticasTransversalesCategoriasModificaciones: 'api/Programacion/GuardarPoliticasTransversalesCategoriasModificaciones',
        apiBackBoneConsultarPoliticasTransversalesCategoriasModificaciones: 'api/Programacion/ConsultarPoliticasTransversalesCategoriasModificaciones',

        apiBackBoneConsultarPoliticasTransversalesAprobacionesModificaciones: 'api/Programacion/ConsultarPoliticasTransversalesAprobacionesModificaciones',

        apiBackBoneConsultarCatalogoIndicadoresPolitica: 'api/Programacion/ConsultarCatalogoIndicadoresPolitica',
        apiBackBoneGuardarModificacionesAsociarIndicadorPolitica: 'api/Programacion/GuardarModificacionesAsociarIndicadorPolitica',


        //Programación Iniciativa
        apiBackBoneGuardarDatosProgramacionIniciativa: 'api/Programacion/GuardarDatosProgramacionIniciativa',

        //Lanzador Programación
        apiBackBoneExisteFlujoProgramacion: 'api/Flujos/ExisteFlujoProgramacion',

        //Modificación Ley Adición
        apiBackboneObtenerInformacionPresupuestalMLEncabezado: 'api/ModificacionLeyAdicion/ObtenerInformacionPresupuestalMLEncabezado',
        apiBackboneObtenerInformacionPresupuestalMLDetalle: 'api/ModificacionLeyAdicion/ObtenerInformacionPresupuestalMLDetalle',
        apiBackBoneGuardarInformacionPresupuestalML: 'api/ModificacionLeyAdicion/GuardarInformacionPresupuestalML',

        //Programación Producto
        apiBackboneObtenerDatosProgramacionProducto: 'api/Programacion/ObtenerDatosProgramacionProducto',
        apiBackBoneGuardarDatosProgramacionProducto: 'api/Programacion/GuardarDatosProgramacionProducto',
        apiBackboneObtenerProgramacionConsolaProcesos: 'api/Programacion/ObtenerProgramacionConsolaProcesos',

        //Programación Cargue saldos
        apiBackboneRegistrarCargaMasivaSaldos: 'api/Programacion/RegistrarCargaMasivaSaldos',
        apiBackBoneObtenerLogErrorCargaMasivaSaldos: 'api/Programacion/ObtenerLogErrorCargaMasivaSaldos',
        apiBackboneObtenerCargaMasivaSaldos: 'api/Programacion/ObtenerCargaMasivaSaldos',
        apiBackboneObtenerTipoCargaMasiva: 'api/Programacion/ObtenerTipoCargaMasiva',
        apiBackboneValidarCargaMasiva: 'api/Programacion/ValidarCargaMasiva',
        apiBackboneDetalleCargaMasivaSaldos: 'api/Programacion/ObtenerDetalleCargaMasivaSaldos',

        //Programación Distribución
        apiBackboneConsultarDatosProgramacionDistribucion: 'api/ProgramacionDistribucion/ConsultarDatosProgramacionDistribucion',

        //Reportes PIIP
        apiBackboneObtenerAgrupadorReportes: 'api/Autorizacion/ObtenerEncabezadoListadoReportesPIIP',
        apiBackboneObtenerListadoReportes: 'api/Autorizacion/ObtenerListadoReportesPIIP',
        apiBackboneObtenerFiltrosReportesPIIP: 'api/Autorizacion/ObtenerFiltrosReportesPIIP',
        apiBackboneObtenerDatosReportePIIP: 'api/Autorizacion/ObtenerDatosReportePIIP',
        apiBackboneObtenerDatosReportePIIPMga: 'api/ObtenerDatosReportePIIPMga',
        apiBackboneObtenerDatosReportePIIPFlujos: 'api/ObtenerDatosReportePIIPFlujos',
        apiEsquemaMga: 'MgaWeb',
        apiEsquemaAutorizacion: 'autorizacion',
        apiEsquemaFlujos: 'GestorCore',

        //Plan Nacional de desarrollo
        apiBackBoneObtenerPND: 'api/Proyecto/ObtenerPlanNacionalDesarrollo',

        //SGP
        apiBackboneObtenerProyectoListaLocalizacionesSGP: 'api/SGP/ObtenerProyectoListaLocalizacionesSGP',
        apiBackboneDesagregarRegionalizacionSGP: 'api/SGP/ObtenerDesagregarRegionalizacionSGP',
        apiBackBoneObtenerPoliticasTransversalesProyectoSGP: 'api/SGP/ObtenerPoliticasTransversalesProyectoSGP',
        apiBackBoneEliminarPoliticasProyectoSGP: 'api/SGP/EliminarPoliticasProyectoSGP',
        apiBackBoneAgregarPoliticasTransversalesAjustesSGP: 'api/SGP/AgregarPoliticasTransversalesAjustesSGP',
        apiBackboneObtenerProyectoListaTiposRecursosSGP: 'api/SGP/ObtenerListaTiposRecursosSGP',
        apiBackBoneConsultarPoliticasCategoriasIndicadoresSGP: 'api/SGP/ConsultarPoliticasCategoriasIndicadoresSGP',
        apiBackBoneModificarPoliticasCategoriasIndicadoresSGP: 'api/SGP/ModificarPoliticasCategoriasIndicadoresSGP',
        apiBackBoneObtenerPoliticasTransversalesCategoriasSGP: 'api/SGP/ObtenerPoliticasTransversalesCategoriasSGP',
        apiBackBoneEliminarCategoriasPoliticasProyectoSGP: 'api/SGP/EliminarCategoriasPoliticasProyectoSGP',
        apiBackBoneGuardarFocalizacionCategoriasAjustesSGP: 'api/SGP/GuardarFocalizacionCategoriasAjustesSGP',
        apiBackboneObtenerCategoriasSubcategoriasSGP: 'api/SGP/ObtenerCategoriasSubcategoriasSGP',
        apiBackboneguardarFocalizacionCategoriasPoliticaSGP: 'api/SGP/GuardarFocalizacionCategoriasPoliticaSGP',

        apiBackBoneObtenerCrucePoliticasAjustesSGP: 'api/SGP/ObtenerCrucePoliticasAjustesSGP',
        apiBackBoneObtenerPoliticasTransversalesResumenSGP: 'api/SGP/ObtenerPoliticasTransversalesResumenSGP',
        apiBackBoneGuardarCrucePoliticasAjustesSGP: 'api/SGP/GuardarCrucePoliticasAjustesSGP',

        apiBackBoneSGPTransversalLeerParametro: 'SGP/Transversal/LeerParametro',
        apiBackboneSGPAcuerdoLeerProyecto: 'SGP/Acuerdo/LeerProyecto',
        apiBackboneSGPAcuerdoGuardarProyecto: 'SGP/Acuerdo/GuardarProyecto',
        apiBackboneSGPProyectosLeerListas: 'SGP/Proyectos/LeerListas',

        apiBackboneSGPViabilidadLeerInformacionGeneral: 'SGP/Viabilidad/SGPViabilidadLeerInformacionGeneral',
        apiBackboneSGPViabilidadLeerParametricas: 'SGP/Viabilidad/LeerParametricas',
        apiBackboneSGPViabilidadGuardarInformacionBasica: 'SGP/Viabilidad/GuardarInformacionBasica',

        apiBackboneConsultarPreguntasSGP: 'SGP/PreguntasPersonalizadas/ConsultarPreguntasSGP',
        apiBackboneObtenerPreguntasPersonalizadasSGP: 'api/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadas',
        apiBackboneObtenerPreguntasPersonalizadasSGPComponente: 'SGP/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadasComponente',
        apiBackboneObtenerPreguntasPersonalizadasComponenteSGP: 'SGP/PreguntasPersonalizadas/ObtenerPreguntasPersonalizadasComponenteSGP',
        apiBackboneObtenerDatosGeneralesProyectoSGP: 'SGP/PreguntasPersonalizadas/ObtenerDatosGeneralesProyecto',
        apiBackboneGuardarPreguntasPersonalizadasSGP: 'SGP/PreguntasPersonalizadas/GuardarPreguntasPersonalizadas',
        apiBackboneGuardarPreguntasPersonalizadasCustomSGP: 'SGP/PreguntasPersonalizadas/GuardarPreguntasPersonalizadasCustomSGP',
        apiBackboneDevolverCuestionarioProyectoSGP: 'SGP/PreguntasPersonalizadas/DevolverCuestionarioProyecto',
        apiBackboneObtenerConfiguracionEntidadesSGP: 'SGP/PreguntasPersonalizadas/ObtenerConfiguracionEntidades',

        apiBackboneDevolverProyectoSGP: 'api/proyecto/DevolverProyecto',
        apiBackboneValidarArchivosSgp: 'api/manejadorArchivos/ValidarArchivosSgr/',
        apiBackBoneCargarFirmaSgp: 'api/SGR/CargarFirma',
        apiBackBoneValidarSiExisteFirmaUsuarioSgp: 'api/SGR/validarSiExisteFirmaUsuario',
        apiBackBoneBorrarFirmaSgp: 'api/SGR/BorrarFirma',
        apiBackBoneFirmarSgp: 'api/SGR/Firmar',
        apiBackBoneEliminarFirmaSgp: 'api/SGR/EliminarFirma',

        apiBackboneFuenteFinanciacionVigenciaConsultarSGP: 'api/SGP/ObtenerFuenteFinanciacionVigenciaSGP',
        apiBackboneFuenteFinanciacionEliminarSGP: 'api/SGP/FuenteFinanciacionEliminarSGP',
        apiBackboneFuentesProgramarSolicitadoSGP: 'api/SGP/ConsultarFuentesProgramarSolicitadoSGP',
        apiBackboneGuardarFuentesProgramarSolicitadoSGP: 'api/SGP/GuardarFuentesProgramarSolicitadoSGP',
        apiBackboneDatosAdicionalesConsultarSGP: 'api/SGP/DatosAdicionalesObtenerSGP',
        apiBackboneDatosAdicionalesAgregarSGP: 'api/SGP/DatosAdicionalesAgregarSGP',
        apiBackboneDatosAdicionalesEliminarSGP: 'api/SGP/DatosAdicionalesEliminarSGP',
        apiBackboneFuenteFinanciacionAgregarSGP: 'api/SGP/FuenteFinanciacionAgregarSGP',
        apiBackBoneProyectoViabilidadInvolucradosAgregarSGP: 'SGP/Proyectos/GuardarProyectoViabilidadInvolucradosSGP',
        apiBackBoneProyectoViabilidadInvolucradosEliminarSGP: 'SGP/Proyectos/EliminarProyectoViabilidadInvolucradosSGP',
        apiBackBoneLeerProyectoViabilidadInvolucradosSGP: 'SGP/Proyectos/LeerProyectoViabilidadInvolucrados',
        apiBackBoneObtenerEntidadDestinoResponsableFlujoSGP: 'SGP/Proyectos/ObtenerEntidadDestinoResponsableFlujo',
        apiBackBoneObtenerEntidadDestinoResponsableFlujoTramiteSGP: 'SGP/Proyectos/ObtenerEntidadDestinoResponsableFlujoTramite',
        apiBackBoneLeerProyectoViabilidadInvolucradosFirmaSGP: 'SGP/Proyectos/LeerProyectoViabilidadInvolucradosFirma',

        apiBackboneObtenerProductosPoliticasSgp: 'api/SGP/ObtenerCategoriaProductosPoliticaSGP',
        apiBackboneGuardarDatosSolicitudRecursosSgp: 'api/SGP/guardarDatosSolicitudRecursosSGP',
        apiBackboneObtenerDatosIndicadoresPoliticasSgp: 'api/SGP/ObtenerIndicadoresPoliticaSGP',


        apiBackboneObtenerSectoresSGP: 'api/AdministradorEntidadSGP/ObtenerSectores',
        apiBackboneObtenerFlowCatalogSGP: 'api/AdministradorEntidadSGP/ObtenerFlowCatalog',
        apiBackboneObtenerMatrizEntidadDestinoSGP: 'api/AdministradorEntidadSGP/ObtenerMatrizEntidadDestino',
        apiBackboneActualizarMatrizEntidadDestinoSGP: 'api/AdministradorEntidadSGP/ActualizarMatrizEntidadDestino',

        apiBackboneActualizarHorizonteSGP: 'api/SGP/actualizarHorizonteSGP',
        apiCambiosFirmeObtenerJustificacionHorizonteSGP: 'api/SGP/ObtenerJustificacionHorizonteSGP',
        apiBackboneObtenerIndicadorProductoSGP: 'api/SGP/ObtenerIndicadoresProductoSGP',
        apiBackboneGuardarIndicadorSecundarioSGP: 'api/SGP/GuardarIndicadoresSecundariosSGP',
        apiBackboneEliminarIndicadorProductoSGP: 'api/SGP/EliminarIndicadorProductoSGP',
        apiBackboneActualizarMetaAjusteIndicadorSGP: 'api/SGP/ActualizarMetaAjusteIndicadorSGP',
        apiBackboneObtenerProyectosBeneficiariosSGP: 'api/SGP/ObtenerProyectosBeneficiariosSGP',
        apiBackboneObtenerProyectosBeneficiariosDetalleSGP: 'api/SGP/ObtenerProyectosBeneficiariosDetalleSGP',
        apiBackboneGuardarBeneficiarioTotalesSGP: 'api/SGP/GuardarBeneficiarioTotalesSGP',
        apiBackboneGuardarBeneficiarioProductoSGP: 'api/SGP/GuardarBeneficiarioProductoSGP',
        apiBackboneGuardarBeneficiarioProductoLocalizacionSGP: 'api/SGP/GuardarBeneficiarioProductoLocalizacionSGP',
        apiBackboneGuardarBeneficiarioProductoLocalizacionCaracterizacionSGP: 'api/SGP/GuardarBeneficiarioProductoLocalizacionCaracterizacionSGP',
        apiBackboneGuardarLocalizacionSGP: 'api/SGP/GuardarLocalizacionSGP',
        apiBackboneObtenerHorizonteSgp: 'api/SGP/ObtenerHorizonteSgp',
        //Definicion para la migracion de los servicios de fuentes de financiamiento y costos
        apiBackboneguardarFuentesFinanciacionRecursosAjustesSgp: 'api/SGP/guardarFuentesFinanciacionRecursosAjustesSgp',
        apiBackboneObtenerResumenObjetivosProductosActividadesSgp: 'api/SGP/proyecto/ObtenerResumenObjetivosProductosActividadesSgp',
        apiBackboneGuardarCostoActividadesSgp: 'api/SGP/proyecto/GuardarCostoActividadesSgp',
        apiBackboneAgregarEntregableSgp: 'api/SGP/proyecto/AgregarEntregableSgp',
        apiBackboneEliminarEntregableSgp: 'api/SGP/proyecto/EliminarEntregableSgp',
        //R_FirmaConceptoViabilidad
        idRFirmaConceptoViabilidad: '5947F7A2-61D8-4D51-99DF-4283143846C2',

        //TramiteSGP
        apiBackboneActualizarEstadoAjusteProyectoSGP: 'api/TramiteSGP/ActualizarEstadoAjusteProyecto',
        apiBackboneEliminarProyectoTramiteNegocioSGP: 'api/TramiteSGP/EliminarProyectoTramiteNegocio',
        apiBackboneEliminarInstanciaCerrada_AbiertaProyectoTramiteSGP: 'api/TramiteSGP/EliminarInstanciaCerrada_AbiertaProyectoTramite',
        apiBackboneObtenerContraCreditosSgp: 'api/TramiteSGP/ObtenerContracreditoSgp',
        apiBackboneObtenerCreditoSgp: 'api/TramiteSGP/ObtenerCreditoSgp',
        apiBackboneObtenerTiposValorPorEntidadSgp: 'api/TramiteSGP/ObtenerTiposValorPorEntidadSgp',

        //TramiteSGP - Información Presupuestal
        apiBackboneActualizarTramitesFuentesPresupuestalesSGP: 'api/TramiteSGP/GuardarTramiteInformacionPresupuestal',
        apiBackboneObtenerListaProyectosFuentesSGP: 'api/TramiteSGP/ObtenerListaProyectosFuentes',
        apiBackboneGuardarFuentesTramiteProyectoAprobacionSGP: 'api/TramiteSGP/GuardarFuentesTramiteProyectoAprobacion',
        apiBackboneObtenerListaProyectosFuentesAprobadoSGP: 'api/TramiteSGP/ObtenerListaProyectosFuentesAprobado',
        apiBackboneActualizarTramitesRequisitosSGP: 'api/TramiteSGP/GuardarTramiteTipoRequisito',
        apiBackboneObtenerProyectoRequisitosPorTramiteSGP: 'api/TramiteSGP/ObtenerProyectoRequisitosPorTramite',

        //TramiteSGP - Adición
        apiBackboneObtenerDatosAdicionSgp: 'api/TramiteSGP/ObtenerDatosAdicionSgp',
        apiBackboneGuardarDatosAdicionSgp: 'api/TramiteSGP/GuardarDatosAdicionSgp',
        apiBackboneEiliminarDatosAdicionSgp: 'api/TramiteSGP/EiliminarDatosAdicionSgp',

        //TramiteProyectoSGP
        apiBackboneObtenerProyectosTramiteNegocioSGP: 'api/TramiteProyectoSGP/ObtenerProyectosTramiteNegocio',
        apiBackboneGuardarProyectosTramiteNegocioSGP: 'api/TramiteProyectoSGP/GuardarProyectosTramiteNegocio',
        apiBackboneValidacionProyectosTramiteNegocio: 'api/TramiteProyectoSGP/ValidacionProyectosTramiteNegocio',
        apiBackBoneObtenerCategoriasFocalizacionJustificacionSgp: 'api/SGP/Ajustes/ObtenerCategoriasFocalizacionJustificacionSgp',
        apiBackBoneObtenerDetalleCategoriasFocalizacionJustificacionSgp: 'api/SGP/Ajustes/ObtenerDetalleCategoriasFocalizacionJustificacionSgp',
    });
})();


