//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.EncabezadoPie.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityTypeCatalogOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityTypeCatalogOption()
        {
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto { get; set; }
    }
}
