//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNP.EncabezadoPie.Persistencia.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MGAWebContextoEncabezado : DbContext
    {
        public MGAWebContextoEncabezado()
            : base("name=MGAWebContextoEncabezado")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntityTypeCatalogOption> EntityTypeCatalogOption { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<AlmacenamientoTemporal> AlmacenamientoTemporal { get; set; }
    
        public virtual int uspPostIdentificarEntidadDestino(Nullable<decimal> projectId, ObjectParameter entidadDestino, ObjectParameter entidadDestinoId, ObjectParameter errorValidacionNegocio)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostIdentificarEntidadDestino", projectIdParameter, entidadDestino, entidadDestinoId, errorValidacionNegocio);
        }
    
        public virtual int uspValidaciones(Nullable<decimal> proyectoId, ObjectParameter exitoso)
        {
            var proyectoIdParameter = proyectoId.HasValue ?
                new ObjectParameter("ProyectoId", proyectoId) :
                new ObjectParameter("ProyectoId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspValidaciones", proyectoIdParameter, exitoso);
        }
    
        public virtual int uspPostCambioEstadoProyecto(string bPIN, Nullable<System.Guid> nivelId, string usuario, ObjectParameter errorValidacionNegocio)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            var nivelIdParameter = nivelId.HasValue ?
                new ObjectParameter("NivelId", nivelId) :
                new ObjectParameter("NivelId", typeof(System.Guid));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPostCambioEstadoProyecto", bPINParameter, nivelIdParameter, usuarioParameter, errorValidacionNegocio);
        }
    
        public virtual ObjectResult<string> GetEncForm_PrioRec_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetEncForm_PrioRec_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> UspGetEncabezadoFormularioAlcance_JSON(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetEncabezadoFormularioAlcance_JSON", bPINParameter);
        }
    
        public virtual ObjectResult<string> uspPostIndicadoresValidarCapituloModificado(string bPIN)
        {
            var bPINParameter = bPIN != null ?
                new ObjectParameter("BPIN", bPIN) :
                new ObjectParameter("BPIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspPostIndicadoresValidarCapituloModificado", bPINParameter);
        }
    
        public virtual ObjectResult<UspGetEncabezado_Result> UspGetEncabezado(Nullable<System.Guid> idInstancia, Nullable<System.Guid> idFlujo, Nullable<System.Guid> idNivel, Nullable<int> idProyecto, string tramite)
        {
            var idInstanciaParameter = idInstancia.HasValue ?
                new ObjectParameter("idInstancia", idInstancia) :
                new ObjectParameter("idInstancia", typeof(System.Guid));
    
            var idFlujoParameter = idFlujo.HasValue ?
                new ObjectParameter("idFlujo", idFlujo) :
                new ObjectParameter("idFlujo", typeof(System.Guid));
    
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("idNivel", idNivel) :
                new ObjectParameter("idNivel", typeof(System.Guid));
    
            var idProyectoParameter = idProyecto.HasValue ?
                new ObjectParameter("idProyecto", idProyecto) :
                new ObjectParameter("idProyecto", typeof(int));
    
            var tramiteParameter = tramite != null ?
                new ObjectParameter("tramite", tramite) :
                new ObjectParameter("tramite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetEncabezado_Result>("UspGetEncabezado", idInstanciaParameter, idFlujoParameter, idNivelParameter, idProyectoParameter, tramiteParameter);
        }
    }
}
